### ISSUE TITLE
"simple_grant_type" appearing in grant details page

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#1001]
This is intended for internal use in the application (filtering) and needs to be excluded from the table which should only display fields from the grant record.

e.g. https://grantnav.threesixtygiving.org/grant/360G-NuffieldFdn-43019

**Comment by mariongalley** [comment]
Ah thanks @michaelwood - I'd assumed this was additional data from the publisher when I came across it
