### ISSUE TITLE
Provide static download instead when unfiltered search

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#1013]
We sometimes see very high loads on GrantNav's elastic search, this is usually caused by people or bots hitting download "Export search data: CSV/JSON" on the grant search page when there are no filters applied. Given that now requires streaming nearly a million rows of data to the user we may want to provide a static download link (such as the datastore's daily data) for people who want all the data.

**Comment by mariongalley** [comment]
Thanks @michaelwood Let's label all issues to do with downloads to be addressed when we do the new download interface

**Comment by michaelwood** [comment]
We now have an API that gives people a better experience for this kind of use case, we're also re-doing the downloads
