### ISSUE TITLE
GrantNav filters missing checks in checkboxes

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#1015]
**Describe the bug**
GrantNav filters missing checks in checkboxes

**To Reproduce**
1. Go to GrantNav
2. Click on any value in any filter
3. See that the selected state does not cause an x to appear in the checkbox

**Expected behavior**
I would expect an x to appear in the checkbox

**Screenshots**

Previous appearance:

![image](https://github.com/ThreeSixtyGiving/grantnav/assets/82958988/2434cc03-bd8e-4d66-91b9-35012cc7cebe)

Current appearance:

![image](https://github.com/ThreeSixtyGiving/grantnav/assets/82958988/4784404e-25a2-497e-b32b-23a844a01ba7)

**Comment by michaelwood** [comment]
The static files have moved and for some reason this one is hardcoded:

`checkmark-icon.svg:1   Failed to load resource: the server responded with a status of 404 (Not Found)`

`grantnav/frontend/static/css/main.css:1892:    background: url("/static/images/checkmark-icon.svg") no-repeat;`

**Comment by michaelwood** [comment]
Fixed & Deployed

**Comment by mariongalley** [comment]
@michaelwood This is also an issue in dev GrantNav that we're using to test Insights, should I raise it again there?
