### ISSUE TITLE
Make web adresses in GrantNav into links

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#103]
User stories ftw

**Comment by Bjwebb** [comment]
One security consideration here is that we really don't want to allow people to include arbitary javascript in their links. The best way to do this seems to be to whitelist that links must start with `http://` or `https://`

**Comment by stevieflow** [comment]
Example: in http://grantnav.threesixtygiving.org/grant/360G-EFF-10-1876 - make http://www.chapter.org clickable

**Comment by robredpath** [comment]
Also: would be good to make other URLs clickable, eg Grant Programme:URL in http://grantnav.threesixtygiving.org/grant/360G-wolfson-20510

**Comment by robredpath** [comment]
To be clear, the scope of this is fields in the standard that should contain web addresses (such as `Recipient Org: Web Address`) rather than trying to extract web addresses from text

**Comment by michaelwood** [comment]
We now do this on the org page for the relevant organisations where we have an external link.
