### ISSUE TITLE
Widgets - improve accessibility

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#1056]
A few accessibility issues with Widgets have been pointed out by a publisher, please can these be fixed:

- [x] 1. The TITLE tag gives all widget instances the page title "360Giving Widgets". Many screen reader set ups will use the title to tell the user about the contents of the frame so it helpful when this is descriptive. Is there a way to programmatically title the page with human readable content based on the data selected for display in the widget (e.g. "Grants data from Very Nice Foundation")?

- [x] 2. There is no language defined for the widget content. This is important to screenreaders (for pronunciation).

- [x] 3. The (extremely elegant) logo implementation creates no accessible title and therefore provides no navigation scent to screenreaders. Adding aria-label="some useful text here" to the A tag around the logo will solve this. (I am unclear whether you intend the logo to link the GrantNav homepage or to the relevant dataset for the trust, as it does now).

**Comment by michaelwood** [comment]
On the widget itself 

open in [GrantNav](https://grantnav.threesixtygiving.org/search)

Needs to be:

[open in GrantNav](https://grantnav.threesixtygiving.org/search)
