### ISSUE TITLE
Post dated grant causes GrantNav to fail

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#1063]
**Describe the bug**
A Funder called have added a post-dated grant. The guidance/DQT recommend but do not forbid having post-dated grants. This breaks GrantNav views that include the grant, returning a server error 500.

**To Reproduce**

The following views return the 500 error:

1. [All grants sorted by latest award dates](https://grantnav.threesixtygiving.org/search?sort=awardDate+desc)
2. [Grants filtered to the funder](https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&fundingOrganization=GB-CHC-1199596&fundingOrganization=GB-COH-13792350)
3. [Grants filtered to the funder via "Explore the data" link on their org page](https://grantnav.threesixtygiving.org/search?fundingOrganization=GB-CHC-1199596&fundingOrganization=GB-COH-13792350)

**Expected behavior**
It should show the grants as normal not returning an error

**Screenshots**
![image](https://github.com/ThreeSixtyGiving/grantnav/assets/82958988/861e1d15-6bb7-4e4b-936a-898b9c5bf226)

**Comment by michaelwood** [comment]
This was actually to do with a an issue with the grant id
