### ISSUE TITLE
As a user I want to the Default fields to be; required fields + recommended fields (publisher guidance) + fields shown in the filters (i.e. regranting)

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#1072]

**Comment by michaelwood** [comment]
https://docs.google.com/spreadsheets/d/1klj0PzxrlnBPhodpEQC7tD6aRNuEjVNeNHVRvIv66b4/edit?gid=957348413#gid=957348413

**Comment by michaelwood** [comment]
Currently missing

Beneficiary Location:Name
Beneficiary Location:Geographic Code
Beneficiary Location:Geographic Code Type

**Comment by mariongalley** [comment]
And Recipient Individual Name and Identifier @michaelwood
