### ISSUE TITLE
Gathering feedback - via a widget?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#108]
We are receiving feedback on the closed beta application via email and user workshops

@robredpath do we want to consider something else ?  One of those widgets: https://www.quora.com/What-is-the-best-website-feedback-widget-available-for-free ?

For user feedback it could be a valuable route - 

I dont know if this will be a disruption technically though

And - we might also have an overhead in terms of processes to setup

Thinking forward, it's likely that we will want _something_ in place for live

**Comment by morchickit** [comment]
I am closing this for now. We probably not going to do it in the future and we are gathering feedback in other ways. Please re-open if you think we should.
