### ISSUE TITLE
Helpsite to signpost to Intro to GrantNav workshops

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#1098]
We'd like to signpost to the Introduction to GrantNav workshops on the Helpsite, ideally in a way that can be seen across all pages.

Ideally we'd have some kind of banner at the top using an existing component like these banners in the Publisher Guidance
 
![image](https://github.com/user-attachments/assets/7322040b-f324-44b6-9777-189b1c7f690f)

It should say something like:
> **Want to learn more about how to use GrantNav?**
> Sign up to our [Introduction to GrantNav workshops](https://www.threesixtygiving.org/workshops/#free-tools-workshops) to get the most our of GrantNav's search and use it to answer your biggest grantmaking questions.

Also I think we should change this content at the bottom of the nav.

![image](https://github.com/user-attachments/assets/066b765c-42e3-4c4b-b451-4e875f39e213)

"Useful links" should have
- [Workshops](https://www.threesixtygiving.org/workshops/#free-tools-workshops)
- [Publish](https://www.threesixtygiving.org/publishing/)
- [Quality Dashboard](https://qualitydashboard.threesixtygiving.org/alldata)

And can we remove the Version stuff altogther?

**Comment by mrshll1001** [comment]
I've addressed this and built it, take a looksie here:

* https://help.grantnav.threesixtygiving.org/en/mm-signpost-intro-to-grantnav-workshops/refining_results/#

I'll open up a PR, which I can edit later if you need to change the copy etc.

**Comment by mrshll1001** [comment]
Also, just noting that I don't think I can turn off the versioning menu via the sphinx config. I will try to do this via readthedocs' interface.

**Comment by mariongalley** [comment]
@mrshll1001 Happy with the useful links change. Any luck with the bigger banner I suggested?
