### ISSUE TITLE
Replace Twitter with LinkedIn and place it before Github in tools footers

### ISSUE THREAD

**Issue by R2ZER0** [ThreeSixtyGiving/grantnav#1104]
From Ticket 50737

> Currently the footers of all the 360Giving tools have little Github and Twitter logos/links. We're promoting our LinkedIn instead, so please can this be replaced with a linkedin logo and a link to https://www.linkedin.com/company/360giving/

> And while we're at it please can we switch the Github logo to be after LinkedIn because Github is relevant to a narrower audience

**Comment by mrshll1001** [comment]
I've had a first stab at this. Lmk if I've seriously borked any CSS or SVG rendering.

**Comment by R2ZER0** [comment]
This is done
