### ISSUE TITLE
Use 360Giving instead of threesixtygiving in copy referring to the organisation

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#1111]
The Additional Data section of grants pages says "Additional data added by ThreeSixtyGiving"

This has been like this for some time but it's a problem for us as it exacerbates the problem created by our domain of people thinking we are called ThreeSixtyGiving.

1. Please can this be changed to 360Giving on all grants pages?
2. Is there a way to find out whether this is used elsewhere in copy in our tools? I tried doing a search but it threw up too many false positives as we list our contact email grantnav@threesixtygiving.org in the footer, which means every page gets flagged.

**Comment by mariongalley** [comment]
![Image](https://github.com/user-attachments/assets/412be095-b588-4f53-9100-89f23e4f808a)

**Comment by michaelwood** [comment]
There were two instances that I could find where were the org detail pages and grant detail pages. No particularly easy way to find as the github org matches "ThreeSixtyGiving" so any urls for that are also coming up. We'll have to keep an eye out for them.
