### ISSUE TITLE
Get rid of unwanted ads from Helpsite

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#1112]
Hello, we've started getting unwanted ads on the Helpsite. Can we get rid of these?

![Image](https://github.com/user-attachments/assets/165f4ad3-7d09-4060-be51-d2a441b77962)

**Comment by mrshll1001** [comment]
I've unchecked the box which says that Paid advertising was enabled. This was also checked on the 360G standard docs site. So I'm not sure why the help site started receiving ads when the standard docs didn't?

I can't see whether we pay for "Gold" membership or "Read the docs for business" for either of the docs sites. So I'm not sure if there's something else at play.

Apparently opting out only opts us out of paid advertising, and the docs site will still be subject to community advertising e.g. open source projects, conferences etc. I doubt this is what we want. I will ask RTD about what changes have occurred and whether they can illuminate what's went on.

**Comment by mariongalley** [comment]
@mrshll1001 The Standard docs had a bunch of work done to make them nicely styled so I wonder if that extra front end bit means RTD couldn't work out where to put an ad as easily?

**Comment by neelima-j** [comment]
@mrshll1001 emailed readthedocs support. The solution is for the 'opendataservices' user account to add the grantnav project as ad free, under their gold subscription. 

This is now done. Ads are still visible - I'll check in 24 hours and take action if needed.

**Comment by mariongalley** [comment]
Thank you @neelima-j

**Comment by neelima-j** [comment]
Ads no longer appear.
