### ISSUE TITLE
helpsite "Uncaught ReferenceError: SphinxRtdTheme is not defined"

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#1117]
The helpsite is currently reporting an error trying to set "StickyNav" to false.

Unclear as to when that stopped being able to be accessed/set or if this is an upstream issue.

```html
  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.StickyNav.enable(false);
      });
  </script>
```
docs/_templates/base.html:175

Which appears to be from the RTD theme : 

https://github.com/readthedocs/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/layout.html#L202

**Comment by michaelwood** [comment]
@mariongalley do you see anything looking wrong on https://help.grantnav.threesixtygiving.org/en/latest/ it may be that the "Sticky Nav" option for the helpsite theme is no longer relevant.

**Comment by mariongalley** [comment]
@michaelwood No I don't see anything wrong - I think this can be closed
