### ISSUE TITLE
Request URI too large if I add lots of filters

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#155]
If you add lots (30+ filters) then the URI gets too big. Click the link below, then add one more filter to see the error:

http://grantnav-big.grantnav-dev.default.opendataservices.uk0.bigv.io/search?json_query={%22aggs%22:+{%22recipientOrganization%22:+{%22terms%22:+{%22size%22:+50,+%22field%22:+%22recipientOrganization.id_and_name%22}},+%22recipientDistrictName%22:+{%22terms%22:+{%22size%22:+10,+%22field%22:+%22recipientDistrictName%22}},+%22fundingOrganization%22:+{%22terms%22:+{%22size%22:+50,+%22field%22:+%22fundingOrganization.id_and_name%22}},+%22recipientRegionName%22:+{%22terms%22:+{%22size%22:+20,+%22field%22:+%22recipientRegionName%22}}},+%22query%22:+{%22bool%22:+{%22must%22:+{%22query_string%22:+{%22query%22:+%22disabilities%22}},+%22filter%22:+[{%22bool%22:+{%22should%22:+[{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22The+Big+Lottery+Fund\%22,+\%22360G-blf\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Esm\\u00e9e+Fairbairn+Foundation\%22,+\%22GB-CHC-200051\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Lloyds+Bank+Foundation+for+England+and+Wales\%22,+\%22GB-CHC-327114\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Wolfson+Foundation\%22,+\%22GB-CHC-1156077\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Oxfordshire+Community+Foundation\%22,+\%22GB-CHC-1151621\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22The+Dulverton+Trust\%22,+\%22360G-dulverton\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Nominet+Trust\%22,+\%22NominetTrust\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Paul+Hamlyn+Foundation\%22,+\%22360G-phf\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22True+Colours+Trust\%22,+\%22360G-truecolours\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Greenham+Common+Trust\%22,+\%22GB-COH-03340350\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Indigo+Trust\%22,+\%22360G-indigotrust\%22]%22}},+{%22term%22:+{%22fundingOrganization.id_and_name%22:+%22[\%22Trafford+Metropolitan+Borough+Council\%22,+\%22E08000009\%22]%22}}]}},+{%22bool%22:+{%22should%22:+[{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Leonard+Cheshire+Disability\%22,+\%22GB-CHC-218186\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Contact+A+Family\%22,+\%22GB-CHC-284912\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22SCOPE\%22,+\%22GB-CHC-208231\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22North+Tyneside+District+Disability+Forum\%22,+\%22GB-CHC-1072475\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Every+Disabled+Child+Matters\%22,+\%22GB-CHC-258825\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Truro+Gateway+Club\%22,+\%22GB-CHC-222377\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Capability+Scotland\%22,+\%22GB-SC-SC011330\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Cheshire+Young+Carers\%22,+\%22GB-CHC-1077265\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Kent+Friendz\%22,+\%22GB-CHC-1152617\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Royal+British+Legion+(Upminster+and+Cranham)\%22,+\%22GB-CHC-219279\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Shape\%22,+\%22GB-CHC-279184\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Bromley+Mencap\%22,+\%22GB-CHC-800685\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Special+Olympics+Great+Britain\%22,+\%22GB-CHC-800329\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Foresight+(North+East+Lincolnshire)+Ltd\%22,+\%22GB-CHC-1095120\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Skipton+and+Craven+Action+for+Disability\%22,+\%22GB-CHC-1092511\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22ARC\%22,+\%22GB-CHC-285575\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Disability+Direct\%22,+\%22GB-CHC-1079831\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22ENABLE+Scotland\%22,+\%22GB-SC-SC009024\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Live!\%22,+\%22GB-CHC-1160972\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22PARC+(Essex)\%22,+\%22GB-CHC-1065854\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Fermanagh+Voluntary+Association+of+the+Disabled\%22,+\%22GB-COH-NI28501\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Latin+American+Disabled+People's+Project\%22,+\%22GB-CHC-1027205\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Learning+Disability+Experience+(LDX)\%22,+\%22GB-CHC-1041341\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Teesdale+Disability+Access+Forum\%22,+\%22GB-CHC-1111862\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Derbyshire+Coalition+for+Inclusive+Living\%22,+\%22GB-CHC-701563\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Inverclyde+Council+on+Disability+Limited\%22,+\%22GB-SC-SC028524\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22Short+Breaks+Network\%22,+\%22GB-CHC-1104216\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22The+Children's+Society\%22,+\%22GB-CHC-221124\%22]%22}},+{%22term%22:+{%22recipientOrganization.id_and_name%22:+%22[\%22The+Outsiders+Trust\%22,+\%22GB-CHC-283350\%22]%22}}]}},+{%22bool%22:+{%22should%22:+[]}},+{%22bool%22:+{%22should%22:+[]}},+{%22bool%22:+{%22should%22:+[]}},+{%22bool%22:+{%22should%22:+[{%22term%22:+{%22recipientRegionName%22:+%22London%22}},+{%22term%22:+{%22recipientRegionName%22:+%22North+East%22}},+{%22term%22:+{%22recipientRegionName%22:+%22Scotland%22}},+{%22term%22:+{%22recipientRegionName%22:+%22South+East+Coast%22}},+{%22term%22:+{%22recipientRegionName%22:+%22Wales%22}},+{%22term%22:+{%22recipientRegionName%22:+%22Northern+Ireland%22}},+{%22term%22:+{%22recipientRegionName%22:+%22South+Central%22}},+{%22term%22:+{%22recipientRegionName%22:+%22West+Midlands%22}},+{%22term%22:+{%22recipientRegionName%22:+%22Yorkshire+and+the+Humber%22}},+{%22term%22:+{%22recipientRegionName%22:+%22East+of+England%22}},+{%22term%22:+{%22recipientRegionName%22:+%22North+West%22}},+{%22term%22:+{%22recipientRegionName%22:+%22South+West%22}},+{%22term%22:+{%22recipientRegionName%22:+%22East+Midlands%22}}]}},+{%22bool%22:+{%22should%22:+[]}}]}}}

**Comment by robredpath** [comment]
This is related to #40

**Comment by morchickit** [comment]
@robredpath any way we can add this to the sprint as well? I got some complaints about it already.. :-)

**Comment by robredpath** [comment]
@morchickit I can discuss it with the team and see if there's an easy workaround (eg if we can increase the allowed request URI length). 

Do we know what people are trying to do that requires the application of so many facets? This took me a solid 5 minutes of clicking to reproduce back in 2016 (and I only did so to test a theory!), so I feel it's unlikely to occur much in normal use - which is why I'm interested in abnormal use!

**Comment by robredpath** [comment]
I wonder if a good workaround would be a custom 414 page that explained the issue (too many filters) and linked out to any resources we've got about analysing downloaded data?

**Comment by robredpath** [comment]
I discussed this with @morchickit today and we talked through some of the practical issues around shorter URLs. @kindly do you have any sense of if there are easy steps we could take to shorten URLs, for sharing-friendliness, as well as to help reduce this issue?

**Comment by robredpath** [comment]
We fixed this as part of the new GN work :)
