### ISSUE TITLE
Add facet to do range of dates

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#215]
Satisfies #152

**Comment by morchickit** [comment]
This is really needed and came repeatedly in face to face user feedback.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow GrantNav date facet to select a range of dates + be more granular](https://trello.com/c/bFihR7WQ/66-allow-grantnav-date-facet-to-select-a-range-of-dates-be-more-granular)

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by robredpath** [comment]
@mariongalley and I have decided - year + month. And we can change it if we need to later!

**Comment by robredpath** [comment]
We don't want the interaction to feel tricky - years could be a type-in or a drop-down, or there are some nice JS pickers available. We definitely don't want something that exposes days

**Comment by robredpath** [comment]
Also - we still want people to be able to pick just a near

**Comment by robredpath** [comment]
This is done
