### ISSUE TITLE
Visualise the grant date data, on the grant page

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#28]
(related to #15 )

I wanted to raise the potential that we might want to also provide some context to the data, based on some "analysis".

By this, I'm thinking about devtracker pages such as https://devtracker.dfid.gov.uk/projects/GB-1-203244.  Here, the IATI data is transformed slightly, so that the dates and budget values are put to a different use that just printing them on the page

In terms of 360 context, we might want to do similar with the Award Date - indicating how "old" a grant is.  That might be a first idea in terms of this - we could do more with different dates, I guess

**Comment by stevieflow** [comment]
Proposal:

- When a grant has dates / duration, provide a visual clue to "how old is this grant"?

**Comment by robredpath** [comment]
We now highlight grant value and date on the grant page, as part of the new design.
