### ISSUE TITLE
Collect additional specific stats about visitor behaviour

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#293]
From steering committee:

Look at collecting stats on length of average user visit, latency. Include as part of a regular (monthly?) stats report. Prepare a template report for GC and WP to review. Needs to include info that’s of interest to publishers, e.g. how many people have looked at your data?

**Comment by robredpath** [comment]
We're already tracking text of searches and we're adding piwik for classic analytics

**Comment by robredpath** [comment]
We've looked into tracking the funders but it's looking like several days' work to actually wire it all up, so we're not going to do it this sprint

**Comment by robredpath** [comment]
@Bjwebb what stats/analytics can we currently produce?

**Comment by Bjwebb** [comment]
The best answer to that atm is to click through the piwik.

I might be remembering, but did @idlemoor and @stevieflow produce a report based on the piwik stats? That might be useful to look at.

**Comment by idlemoor** [comment]
No, we simply gave them access to a Piwik login of their own (that can only see the Grantnavs). No reports were produced. They can already see everything we can see.

**Comment by morchickit** [comment]
I am closing this. We need to actually have a new issue on stats now that it's not Piwik.
