### ISSUE TITLE
Add js table sorter to the stats table

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/grantnav#33]
I've been copy/pasting into a spreadsheet to sort this in different ways, would be nice to do it in browser.

**Comment by stevieflow** [comment]
@Bjwebb did you mean http://grantnav.threesixtygiving.org/stats ?

**Comment by Bjwebb** [comment]
I think so.

**Comment by morchickit** [comment]
@robredpath - closing this, we turned off the stats page when ODS did the sprint about ES7.
