### ISSUE TITLE
GrantNav for Developers missing documentation about download file structure

### ISSUE THREAD

**Issue by caprenter** [ThreeSixtyGiving/grantnav#330]
http://grantnav.threesixtygiving.org/developers

I think we agreed we would give info about what data structures to expect from the various downloads available from the site.

i.e. json and csv on grants is 360Giving standard compliant, downloads from tables are not

**Comment by Bjwebb** [comment]
https://github.com/OpenDataServices/grantnav/issues/326

**Comment by morchickit** [comment]
@robredpath @michaelwood - do we still want this now that the datastore is working? Won't we want to tell developers to go to the registry or ask us for access?

**Comment by michaelwood** [comment]
This sort of depends on what 360's various "developer stories" are going to be.

My 2 cents are that the datastore would be the best tool for developers to use if they have a longer term project, but there may still be a place for developers who just need a quick local data dump to do some experiments with.

**Comment by robredpath** [comment]
Now that we've got data services, I'd encourage anyone developing anything new to talk to us and we can either support them to use the GN feeds or (ideally!) get them using data services.
