### ISSUE TITLE
Exclude Geographic Code Type from search?

### ISSUE THREAD

**Issue by ekoner** [ThreeSixtyGiving/grantnav#344]
This issue was raised via the helpdesk:

> Hi team
> 
> Just noticed the Tudor Trust coming up a lot with the search “open data”. Seems to be because Beneficiary Location: Geographic Code Type is coded as Open Data Communities Country. I don’t know if this is something you want to exclude from search results...
> 
> Cheers

This is an edge case, but let's discuss the implication of excluding Geographic Code Type from the search. Pros and Cons?

**Comment by stevieflow** [comment]
To clarify, when we search "All" , is a search run across all the data / all possible fields?

**Comment by Bjwebb** [comment]
> To clarify, when we search "All" , is a search run across all the data / all possible fields?

Yes

**Comment by robredpath** [comment]
I believe that when people enter a search term, they're only looking to search properties of the grant, not properties of the properties of the grant. If someone wants to search for a particular type of geographic code (and maybe a single, or range of values of that code), there is advanced search syntax to support that. I don't think that someone typing 'open data' into GrantNav is looking for data that's coded according to opendatacommunities.org 

 So I'd be in favour of excluding that field from search results.

**Comment by morchickit** [comment]
I am closing this since now you can have a search on titles and descriptions only. @robredpath please open this if you think this was not solved by that.
