### ISSUE TITLE
Some admin geography areas have a (B) in their name

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#345]
I noticed a few geo areas that include a `(B)` after them: 

http://grantnav.threesixtygiving.org/district/Doncaster%20District%20(B)

Is there a reason for this?

**Comment by stevieflow** [comment]
ping

**Comment by robredpath** [comment]
Looks like the (B) stands for Borough

**Comment by robredpath** [comment]
...and it's that way because that's what's in CodePoint Open. 

Labelled with DWI, we can attend to this next time we're devoting development resources to GrantNav

**Comment by robredpath** [comment]
This is in the loading script. We know how to do this.

**Comment by edugomez** [comment]
@robredpath @stevieflow Do we want to get rid of the _'(B)'_ s or replace them with _'Borough'_? Is not very clear in the ticket.

**Comment by robredpath** [comment]
@edugomez good point. I'd assumed we were removing the (B) but actually replacing with (Borough) could be useful for people.

**Comment by stevieflow** [comment]
Would the "Borough" end up in some long strings, and potentail line breaks/wrap?  I'd just lose the (B)

**Comment by robredpath** [comment]
@stevieflow there are already a couple of names where the lines wrap. But, if you don't think that it's useful for people (and, on reflection, using the (Borough) meaningfully feels like analysis, which is beyond the scope of GN), then we might as well remove it. 

@edugomez - let's go with removing the (B) entirely. If it's the wrong thing to do we can always change it!

**Comment by robredpath** [comment]
We removed the (B)
