### ISSUE TITLE
Add 'search recipients' label to funder page

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#347]

**Comment by stevieflow** [comment]
eg: http://grantnav.threesixtygiving.org/funder/GB-CHC-327114

![search](https://user-images.githubusercontent.com/1209944/27380478-2d0261ae-5677-11e7-8ab0-472b235d8276.png)

Change "Search" > "Search recipients"

**Comment by morchickit** [comment]
Wait, is this just a text change or do we need to create this function that is only on recipients? If it's just a text change, can we do it? Seems pretty straightforward no? @stevieflow @robredpath

**Comment by morchickit** [comment]
@robredpath and @BibianaC can we add this to the other text changes we do on the site now?

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav - Add 'search recipients' label to funder page.](https://trello.com/c/zOCS4gq3/68-grantnav-add-search-recipients-label-to-funder-page)

**Comment by BibianaC** [comment]
@morchickit I have added in the Trello board.

**Comment by BibianaC** [comment]
Should it be "Search recipients" or "Search Recipients"? @morchickit @stevieflow

**Comment by stevieflow** [comment]
@BibianaC "Search Recipients" - following what we have as a convention under the main search box

> Search All Fields Locations Recipients Titles & Descriptions
