### ISSUE TITLE
Odd sentry errors from the datatables pages

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/grantnav#348]
We'vec got a couple of Sentry errors related to the datatables AJAX calls:
https://sentry.io/open-data-services/grantnav/issues/169471258/
https://sentry.io/open-data-services/grantnav/issues/169471283/

These are not happening very often, so I don't think it's a big problem, but would be good to have a better idea of causing this. @kindly Are you able to maybe take a look this week, and see if you're able to eyeball what might be going on?

**Comment by kindly** [comment]
I can only assume that this is a bug in datatables not always passing the expected parameters along with the request.  However, I can not reproduce this error.

The only fix I see is to make the data tables views cope with any rubbish that gets sent to that endpoint and not fall over.  This will help with the 500 errors but not get to the root of the problem in datatables.

**Comment by morchickit** [comment]
Still relevant?

**Comment by michaelwood** [comment]
I'm going to say not, as we no longer have the original debugging information and it was on an older version of the software.
