### ISSUE TITLE
Preview text when sharing on social media is the cookie warning

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#356]

**Comment by robredpath** [comment]
![screen shot 2017-06-21 at 11 55 38](https://user-images.githubusercontent.com/641009/27380827-9522af18-5678-11e7-8d66-466b61258a20.png)

**Comment by morchickit** [comment]
Shouldn't this be closed? @robredpath @BibianaC

**Comment by robredpath** [comment]
Just tested on FB, and looks good now
