### ISSUE TITLE
If an organisation is both a funder and a recipient, both their grants in and funds out should appear on their organisation page

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#360]
From a report of a conversation that @ekoner had when demonstrating GrantNav.

Currently, there's no such thing as an organisation page - if an org is a funder, then they have a funder; if they're a recipient, they have a recipient page. 

If they're both, then there's nothing to tie them together. 

The ask here is to bring together funder and recipient pages that relate to the same organisation into a single page.

**Comment by stevieflow** [comment]
Need an example @ekoner

**Comment by ekoner** [comment]
Example: Nesta is both a [funder](http://grantnav.threesixtygiving.org/funder/GB-CHC-1144091) and a [recipient](http://grantnav.threesixtygiving.org/recipient/GB-CHC-1144091). 

Needn't be a single page, a link to the recipient page and vice-versa where data exists would also work.

**Comment by stevieflow** [comment]
Great, thanks @ekoner 

With @morchickit and @robredpath we also discussed the idea that GrantNav misses the concept of an "organisation page", onto which in and our grants could be consolidated.  This might be tricky to remodel though - although in this example we could imagine a page such as http://grantnav.threesixtygiving.org/org/GB-CHC-1144091

**Comment by morchickit** [comment]
I am coming back to the Organisation Page idea, since I think we have many pages that can be consolidated to show the same features (recipient and funder). Adding this to the UX list.

**Comment by mariongalley** [comment]
I also think an org page could help us solve the 2 publishers 1 funder and 1 publisher multiple funders issue, if we have a page that shows if they are a publisher and/or a funder and/or a recipient.

**Comment by robredpath** [comment]
@mariongalley I'm not sure if we've noted it anywhere, but we talked about the idea of having the org page include links to other orgs with the same or similar names in a "did you mean..." style. This could help with identifier advocacy! 

A potential development from that - which I'm not sure is realistic, but would be cool - would be to allow organisations to publish their own org-ids - if they have multiple - on their website - so that we could match the orgs automatically. Obviously there's potential for conflict, which would be interesting to resolve, but could be an interesting thing to explore.

**Comment by robredpath** [comment]
@mariongalley It does, but how we present that is a question of principle - in the same vein as how we separate out published and GN-added fields on the grants page. We could use it to power a "probably the same org" section on the org page, for example? That way it's still useful, but it's just that little bit more awkward than it would be if there was better org id infra. 

We also want to be really careful that we don't claim things that are untrue because of bad data - if FTC was wrong, for some reason, then we don't want to end up claiming that an org took funding from (or funded) someone that they didn't because of an upstream data error. Part of the reason that we don't have any way for people to report errors in GrantNav is that we just reproduce other people's errors! 

I just had a look at it does way more of it than I thought it did, which is cool - so definitely would be a useful thing.

**Comment by mariongalley** [comment]
Yeah we can definitely do a "Do you also want to include [charity] ?" It's a good space to include some copy explaining why we can't just automatically group them together even when we're sure they're the same org because it's the publisher's prerogative.
