### ISSUE TITLE
GrantNav assumes pounds for Amount Awarded filter

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/grantnav#373]
GrantNav assumes pounds for the Amount Awarded filter.

This is not true for some of Zing's grants ([example](http://grantnav.threesixtygiving.org/search?json_query=%7B%22sort%22%3A+%7B%22_score%22%3A+%7B%22order%22%3A+%22desc%22%7D%7D%2C+%22extra_context%22%3A+%7B%22awardYear_facet_size%22%3A+3%2C+%22amountAwardedFixed_facet_size%22%3A+50%7D%2C+%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%7B%22range%22%3A+%7B%22amountAwarded%22%3A+%7B%7D%7D%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%5D%2C+%22must%22%3A+%7B%22query_string%22%3A+%7B%22default_field%22%3A+%22_all%22%2C+%22query%22%3A+%22civicrm%22%7D%7D%7D%7D%2C+%22aggs%22%3A+%7B%22recipientOrganization%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+3%2C+%22field%22%3A+%22recipientOrganization.id_and_name%22%7D%7D%2C+%22fundingOrganization%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+3%2C+%22field%22%3A+%22fundingOrganization.id_and_name%22%7D%7D%2C+%22recipientDistrictName%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+3%2C+%22field%22%3A+%22recipientDistrictName%22%7D%7D%2C+%22recipientRegionName%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+3%2C+%22field%22%3A+%22recipientRegionName%22%7D%7D%7D%7D&page=1&page_y=318.8888854980469)).

**Comment by morchickit** [comment]
Is this connected to #380 ?

**Comment by morchickit** [comment]
@stevieflow - did you look at it yesterday?

**Comment by stevieflow** [comment]
I think we have two Issues on this issue

- this one: in terms of the facet filter
- the table view and £ assumption - which is the focus of: https://github.com/OpenDataServices/grantnav/issues/380

**Comment by morchickit** [comment]
Ok, sweet! Thanks!

**Comment by mariongalley** [comment]
This now works for other currencies - filter assumes you want GBP but if another currency is selected, it uses that. There are default rules when multiple currencies are selected (not sure on what basis, either the one with most grants in the dataset or some other order of preference). New bug discovered: selecting an amount range for GBP returns other currencies too #791
