### ISSUE TITLE
Currencies are not displayed correctly in GrantNav search results

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/grantnav#380]
Don Quixote's grants are all round numbers of USDs, but in GrantNav they're shown as the same round numbers of pounds:
http://grantnav.threesixtygiving.org/funder/US-EIN-39-1916960
https://archives.iupui.edu/bitstream/handle/2450/11391/Quixote%20Foundation%20Final%20Grants%20List_April2017%281%29.xlsx

**Comment by stevieflow** [comment]
Example: http://grantnav.threesixtygiving.org/grant/360G-quixote-0063300000ktDcsAAE

The grant record does state that this is USD - and nowhere on that page is GBP

In search results, we also get a USD declaration:
http://grantnav.threesixtygiving.org/search?json_query=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22must%22%3A+%7B%22query_string%22%3A+%7B%22query%22%3A+%22%2A%22%2C+%22default_field%22%3A+%22_all%22%7D%7D%2C+%22filter%22%3A+%5B%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22term%22%3A+%7B%22fundingOrganization.id_and_name%22%3A+%22%5B%5C%22Quixote+Foundation%5C%22%2C+%5C%22US-EIN-39-1916960%5C%22%5D%22%7D%7D%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%7B%22range%22%3A+%7B%22amountAwarded%22%3A+%7B%7D%7D%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%5D%7D%7D%2C+%22extra_context%22%3A+%7B%22awardYear_facet_size%22%3A+3%2C+%22amountAwardedFixed_facet_size%22%3A+3%7D%2C+%22aggs%22%3A+%7B%22recipientOrganization%22%3A+%7B%22terms%22%3A+%7B%22field%22%3A+%22recipientOrganization.id_and_name%22%2C+%22size%22%3A+3%7D%7D%2C+%22recipientDistrictName%22%3A+%7B%22terms%22%3A+%7B%22field%22%3A+%22recipientDistrictName%22%2C+%22size%22%3A+3%7D%7D%2C+%22recipientRegionName%22%3A+%7B%22terms%22%3A+%7B%22field%22%3A+%22recipientRegionName%22%2C+%22size%22%3A+3%7D%7D%2C+%22fundingOrganization%22%3A+%7B%22terms%22%3A+%7B%22field%22%3A+%22fundingOrganization.id_and_name%22%2C+%22size%22%3A+50%7D%7D%7D%2C+%22sort%22%3A+%7B%22_score%22%3A+%7B%22order%22%3A+%22desc%22%7D%7D%7D

Elsewhere though, we declare this grant as GBP with the £ character

- when on a recipient page: http://grantnav.threesixtygiving.org/recipient/360G-quixote-ORG0013300001pVGH2

- on the funders page: 
http://grantnav.threesixtygiving.org/funders

- the specific funder page
http://grantnav.threesixtygiving.org/funder/US-EIN-39-1916960

So flagging this against the table pages.  What do you think @robredpath ?

**Comment by Bjwebb** [comment]
The search results page also has a filter by Amount Awarded, where a 500USD grant is included in the "£500 - £1,000" filter, despite the fact it's actually smaller than that.

**Comment by robredpath** [comment]
Also worth noting: we omit the currency explicitly in https://github.com/OpenDataServices/grantnav/blob/df97d4f6467c1649448c9ba1e8a185abdc9af6ba/grantnav/frontend/templatetags/frontend.py#L58 

@stevieflow has hit the nail on the head (in different words) - any time when the server makes a decision about currency it's handled correctly, but any time the currency is handled by JavaScript, it's assumed to be GBP.

**Comment by Bjwebb** [comment]
The filter is done server side, and also assumes GBP.

**Comment by KDuerden** [comment]
Further feedback on this from new publisher - they are seeing their two non-GBP grants as £.

![jrct non-gbp grants](https://user-images.githubusercontent.com/20462640/28063912-b2826d2a-662a-11e7-958d-df324b174d0b.jpg)

Can you let me know what feedback I can give at this stage, on this issue, and likely timeline for fixes. Thank you!

**Comment by stevage** [comment]
Fwiw, just hit this as well. All our data is in AUD. For our needs, simply replacing the pound symbol everywhere with $ would be fine. :)

**Comment by robredpath** [comment]
We're going to:
- Add a currency selector to the Amount Awarded facet, which will allow a user to select a custom range of amounts in that currency. The results would then omit any results not in that currency. 
- When the currency selector is changed from 'any' to a particular currency, the page will refresh and the amount ranges in the facet will be updated to reflect the new currency, and a new search will be performed that omits any results not in that currency

And we'll see how that does!

**Comment by robredpath** [comment]
update: 

Defaults:
- currency selector will default to 'gbp', leaving smallest and largest blank will return all gbp results 
- ranges will be in GBP by default, changing the currency selector will change the ranges to usd and the numbers of grants in brackets would update.

**Comment by robredpath** [comment]
We're going to make the Smallest box be 0 by default, so selecting a currency and clicking Apply gives you everything in the target currency

**Comment by stevieflow** [comment]
Thanks @robredpath 

Just to be clear - I am understanding none of the above will *convert* values into the available currencies (GBP, USD. EUR and CHF according to http://grantnav.threesixtygiving.org/stats).  This is just a switch to only see grants with values in one of the currencies?

Also - 

> When the currency selector is changed from 'any' to a particular currency

Is "any" the setting that will show all values in all relevant currencies (as per current setup)?

Lastly:

> Add a currency selector to the Amount Awarded facet

So - if my search includes GBP and USD values, Ill just have a two facets that I could click to *deselect* the other currencies?  I know that this is how all the other facets work, but I'd be minded about how busy the facet area for Amount Awarded could now be - we're talking three functions in one area.  If this is a simple switch on/off of grants in certain currencies, then I'd explore a mechanism that is visibly different

**Comment by robredpath** [comment]
> I am understanding none of the above will convert values into the available currencies 

That is correct, we are not proposing any currency conversion at this stage

> Is "any" the setting that will show all values in all relevant currencies (as per current setup)?

Yes

> So - if my search includes GBP and USD values, Ill just have a two facets that I could click to deselect the other currencies?

This is probably easier to explain with a mockup, which I can do on Monday. The one thing that you won't be able to do is specify that you want to see grants in GBP and USD, but not CHF (for example). If that's an issue, then we need to consider other approaches.

**Comment by stevieflow** [comment]
> This is probably easier to explain with a mockup, which I can do on Monday.

Excellent, thanks @robredpath 

> The one thing that you won't be able to do is specify that you want to see grants in GBP and USD, but not CHF (for example). If that's an issue, then we need to consider other approaches.

OK - let's take a look.  I guess we should circle back up to the original observation / use case too:

> Currencies are not displayed correctly in GrantNav

**Comment by robredpath** [comment]
So, say you search for 'youth' from the front page and then select 'Quixote Foundation' and 'Lloyds Bank Foundation for England and Wales' in facets. Your results will look a bit like this (summary data blurred because we're dealing with that elsewhere): 
![screen shot 2018-01-08 at 17 47 28](https://user-images.githubusercontent.com/641009/34684165-21e92eb0-f49c-11e7-9de9-ed0b0c6d05c0.png)

Note that results are shown in both currencies, as is current behaviour.

If you click on the dropdown in the 'Amount Awarded' box, and choose USD, then clicked 'Apply':

![screen shot 2018-01-08 at 17 50 06](https://user-images.githubusercontent.com/641009/34684259-729364ca-f49c-11e7-9a28-46201f2ce66d.png)

Then you would get just one grant returned (in this fictional data set of 4 grants!), and the facet would update to start to support ranges of USD, with totals to match:

![screen shot 2018-01-08 at 17 57 38](https://user-images.githubusercontent.com/641009/34684594-8230fad6-f49d-11e7-9396-496798b29fc7.png)

> I guess we should circle back up to the original observation / use case too

Exactly - this is about ensuring that GrantNav doesn't misrepresent the data at all (for example, including a grant for 2,000 Yen in a search for grants of GBP 2,000+).

**Comment by stevieflow** [comment]
Great, many thanks @robredpath 

Just want to check 

> Note that results are shown in both currencies, as is current behaviour.

Would it make sense to have the "Any" value displayed as default, and then use the filters to narrow (this might be what you mean)

As for the original issue - I understand that we would now display each value with the relevant currency (as a character) *throughout* GrantNav - so this page http://grantnav.threesixtygiving.org/funder/US-EIN-39-1916960 would be USD, for example (have we got that covered?)

**Comment by robredpath** [comment]
> Would it make sense to have the "Any" value displayed as default, and then use the filters to narrow (this might be what you mean)

This is one of those awkward details. We're proposing that the default value of the dropdown be GBP, but that facet isn't applied until you click the 'apply' button. This allows us to keep the predefined ranges in GBP, matching the value of the dropdown. We felt that was probably what people wanted, instead of 'any' and currencyless ranges, which is potentially confusing. It would, of course, be configurable for other deployments of GN, but the 360 deployment is primarily aimed at a UK audience working in GBP. 

> I understand that we would now display each value with the relevant currency (as a character) throughout GrantNav

I'm going to make this issue specific to search results. I'll open a separate issue for grant pages. We've already got #387 for summaries.

**Comment by robredpath** [comment]
#420 is the issue for funder pages.

**Comment by robredpath** [comment]
After further discussion with @kindly , we're going to: 
- Add a currency facet
- Make the Smallest and Largest fields currency-specific to the most common currency in the results.

**Comment by robredpath** [comment]
This is #791

**Comment by mariongalley** [comment]
I think we can close this then as currency is displayed correctly on org pages now thanks to #819 as well as on the grant record and in search.
