### ISSUE TITLE
Download file - including the codes for admingeo areas

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#382]
In both the CSV and JSON download files, the relevant admin codes for each admingeo area are missing.  For example:

"recipientWardName":"Billesley Ward",
"recipientRegionName":"West Midlands",

The admingeo codes are unique - the names will not always be.  Secondly, the codes can be used by people to cross match with other areas

First of all - do we store the admingeo codes in GN?  It would be useful to know, to then understand if we can distribute them in the download files

**Comment by stevieflow** [comment]
This case study (that @KathernDuerden pointed out) kind of supports this,,, nearly: http://www.threesixtygiving.org/2016/12/16/putting-local-charities-on-the-map/ !

**Comment by robredpath** [comment]
What you download with the JSON or CSV download is everything we've got in GrantNav. 

The intention with providing regions and wards was to power the facets. GrantNav uses a few different strategies to work out where a grant is based on the geo data that's provided in the grant - for example, based on the recipient postcode if that's provided. Some publishers provide geocodes, and if they do, they're included in the download. 

From my quick look into it this morning, I believe that it would be possible to provide geocodes for more grants if we have some geo information to start with.

**Comment by stevieflow** [comment]
@robredpath thanks - but you miss the point slightly :)

When we load to GrantNav it is true that we convert certain data into ward, local authority and region admingeo areas.  In the CSV file - for example - we get the following in columns BJ to BL (which is the data GN has added to the source)


```
Recipient Region	Recipient District	Recipient Ward
West Midlands	Birmingham District (B)	Nechells Ward
West Midlands	Birmingham District (B)	Weoley Ward
West Midlands	Birmingham District (B)	Moseley and Kings Heath Ward
West Midlands	Birmingham District (B)	Nechells Ward
West Midlands	Birmingham District (B)	Moseley and Kings Heath Ward

```
What we are asking for is what ID / code is also available at source, which could be included alongside the string for the name of each area.

**Comment by robredpath** [comment]
@stevieflow sorry if I wasn't clear - if we have enough information to add those columns, then we have enough information to add geocodes for the columns that we currently have strings for. The codelist at https://github.com/OpenDataServices/grantnav/blob/03ebd5ed6e6bccb50686bfa3b264b29a9ee425e0/dataload/codelist.csv has everything we need to do that, so it's just a case of writing the code to do it!

**Comment by KDuerden** [comment]
I love this file! Means I can at least do lookups in the interim 😊

**Comment by stevieflow** [comment]
Excellent - thanks @robredpath !

Great - so the code *is* there , that's good

Therefore, this ticket is clear on task - to include the area ``code`` alongside the ``name`` in the download file

(when time is scheduled)

**Comment by robredpath** [comment]
We know how to do this. It's just a list of fields!

**Comment by edugomez** [comment]
@stevieflow I can see that geocodes for the ward and district are already in e.g. the CSV file (N and Q columns). Would you like to see these codes next to the columns "Recipient District" and "Recipient Ward" as well?

**Comment by stevieflow** [comment]
@edugomez so now Im confused - it seems that the original query of this issue has fixed itself?

> In both the CSV and JSON download files, the relevant admin codes for each admingeo area are missing

?

**Comment by KDuerden** [comment]
The N and Q geocodes are only present where the publisher has included this information themselves. 
We also want geocodes that relate to the District and Ward information added by GrantNav process (from a postcode or geocode lookup) to create the filter functionality.

**Comment by morchickit** [comment]
@robredpath - I believe this can be closed, yes?
