### ISSUE TITLE
Add a page - how does GrantNav work with 360Giving data

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#385]
We have some words to finish on this, which explain how GrantNav works with 360Giving data, and what it does with it etc

Ill try and get this into a PR

**Comment by stevieflow** [comment]
@BobHarper1 has reviewed this @morchickit , so Ill circulate the draft text

**Comment by morchickit** [comment]
Cool! Just shuffled it around for the sprint prep, but looking forward to it!

**Comment by morchickit** [comment]
I think this is done now. Closing this.
