### ISSUE TITLE
Are Region geocodes recognised by GrantNav Region filter?

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#391]
Can data where the Recipient Org: Location: Geographic Code is for regions (eg E12000007, E12000009) work with GrantNav filter functionality for Region?

**Comment by Bjwebb** [comment]
This doesn't work currently, but it's something that could be added.

**Comment by mariongalley** [comment]
This is now fixed, grants coded using region geocodes appear in the regions filter in #868
