### ISSUE TITLE
GrantNav handles identifiers with a / in two different ways

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#392]
(NB - I only have an example in staging atm)

If an identifier is structured as so: ``12345/678`` then GN handles it in two ways

Via search results - the link to this grant resolves to a page that is viewable - ie: ``grant/12345/678``

Via a table results page (eg Funder page) - the link resolves to a page that is not viewable - ie: ``grant/12345%2F678``

It could be an idea to fix the latter.  

NB: 360 will be providing guidance that identifiers should *not* include ``/``

cc/ @KDuerden @morchickit

**Comment by robredpath** [comment]
In the short term, we might want to fix this in the datagetter or the check_grantanv_assumption.py script that does the checks that data is GN-friendly

**Comment by KDuerden** [comment]
Are there any other places where / would be problematic? I've just seen data with titles which all include / so could this break those links?
Also any other characters that might break links - are dots ok?

**Comment by Bjwebb** [comment]
BTW, the link that is broken is created by a third party JavaScript library we're using for the table pages. This means that it's possibly more difficult to fix, and harder for us to say what characters may break it.

However, from experience slashes are a particular kind of problematic, so I wouldn't expect any other characters to break it. Dots should be fine.

**Comment by KDuerden** [comment]
Hi, returning to slash issue. Will this Funding Org ID (taken from Open Knowledge Public bodies list) cause issues with GrantNav?  XI-PB-gb/london-councils
http://publicbodies.org/gb/london-councils

**Comment by Bjwebb** [comment]
Yes, I'd expect that ID to cause a problem.

**Comment by robredpath** [comment]
@michaelwood @kindly is this relevant to the current data services sprint?

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data services should reject data with '/'s in](https://trello.com/c/yvNseaXs/30-data-services-should-reject-data-with-s-in)

**Comment by KDuerden** [comment]
@robredpath this has just cropped up with a new publisher - their grant identifier includes /. 
We will request a change but I wanted to check what the current situation is.
Data with slash in ID or Org ID will load into data services and GN but will break in ways described in the top post?

**Comment by morchickit** [comment]
HI @robredpath and @michaelwood - can you answer Katherin's question above please? :-)

**Comment by KDuerden** [comment]
I've got a new publisher case where XI-PB list is only external identifier available for them. Is a Funding Org:Identifier with / still potentially problematic? 
If it might be a problem - what are the options? Suggest replacing / with _ or ask them to use an internal ID?

**Comment by michaelwood** [comment]
> I've got a new publisher case where XI-PB list is only external identifier available for them. Is a Funding Org:Identifier with / still potentially problematic?
> If it might be a problem - what are the options? Suggest replacing / with _ or ask them to use an internal ID?

It should be fine, I did a quick test on my dev GN instance with an org id set to "GB-COH-064850/99" and the Grants list page worked correctly.

**Comment by KDuerden** [comment]
Thanks @michaelwood

**Comment by KDuerden** [comment]
A new publisher using XI-PB org ID (which employs slashes) data is now appearing in GrantNav.

If you navigate to their data via the [Funder summary pages](https://grantnav.threesixtygiving.org/funders) you get a 404: https://grantnav.threesixtygiving.org/funder/XI-PB-gb%2Fbord-na-gaidhlig

However the page is ok if you manually edit the url or navigate to it via the search results: https://grantnav.threesixtygiving.org/funder/XI-PB-gb/bord-na-gaidhlig

So it looks like it's just an issue with the way the hyperlinks from the funder list is working.

**Comment by michaelwood** [comment]
A fix for this has now been deployed.
