### ISSUE TITLE
Nicer search urls

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/grantnav#40]
Currently we just include an entire ElasticSearch json query block. This was straightforward to implement, but gives us a very long difficult to read url. We've just reconfigured our dev server to handle longer urls https://github.com/OpenDataServices/grantnav/issues/38 - but there's still issues with trying to share the links. However that isn't so bad, and fixing it will require some work, so one for a future iteration.

**Comment by morchickit** [comment]
Now that we have ES7, would this be easier to implement?

**Comment by michaelwood** [comment]
> Now that we have ES7, would this be easier to implement?

Unfortunately not. It is a design decision around the way the queries are built rather than anything else.

**Comment by robredpath** [comment]
We did this
