### ISSUE TITLE
Sort "Award year" filter differently

### ISSUE THREAD

**Issue by stevage** [ThreeSixtyGiving/grantnav#405]
These screenshots probably show the issue best:

<img width="210" alt="screen shot 2017-10-18 at 11 44 34 am" src="https://user-images.githubusercontent.com/678344/31695995-cf350e4c-b3f9-11e7-8f29-03b501f8ef65.png">

<img width="208" alt="screen shot 2017-10-18 at 11 45 23 am" src="https://user-images.githubusercontent.com/678344/31696000-dc0b7020-b3f9-11e7-8802-e453a9464309.png">

In the truncated view, only the three least useful filters are available.

**Comment by jontymorris** [comment]
Do you want the last three years?
Or do you want it to show the years with the most results?

**Comment by stevage** [comment]
I would probably suggest the three years with the most results, ordered reverse chronologically...

In this case: 2016, 2015, 2014

**Comment by mariongalley** [comment]
Filter no longer has a truncated view and looks like this:
![image](https://user-images.githubusercontent.com/82958988/137474647-466b1bf6-75fa-428a-931d-2b744cf892b7.png)

We do hide years with no results if they aren't surrounded by years with results:
![image](https://user-images.githubusercontent.com/82958988/137474916-9119d47a-f264-4b85-86a3-93b6154e681b.png)

In the case where there are years with no results surrounded by years with only a handful of results, you still get a pretty long list that doesn't necessarily show the most useful years first, but they would only be below the fold if all the useful data was really old, which I think is a bit of an edge case.

Closing issue.
