### ISSUE TITLE
Report IP addresses to Sentry

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/grantnav#433]
Internal issue #8732

This is due to how we talk to uwsgi https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/apache/grantnav.conf#L26

https://bugs.launchpad.net/ubuntu/+source/uwsgi/+bug/1501854 fixes this, so that we can use uwsgi's own protocol instead of http. We need to switch to 16.04 to take advantage of this.

**Comment by morchickit** [comment]
@Bjwebb - what is the status on this? Thanks!

**Comment by Bjwebb** [comment]
Looks like this is now fixed with the latest GrantNav servers.
