### ISSUE TITLE
Tell mobile users that GN isn't designed for small screens

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#443]
In https://forum.threesixtygiving.org/t/user-interface-for-mobiles/179/3, Rachel reports that GN doesn't work very well on a mobile screen - text appears outside of boundaries, elements don't scale properly, etc. This is expected behaviour as we didn't design for small screens - we expected iPads to be the smallest devices used to access GrantNav. 

On my phone (iPhone 6S), it looks ok in landscape mode. We should consider what we can do to help mobile users - whether to suggest landscape orientation or to simply inform them that small devices aren't really supported.

**Comment by michaelwood** [comment]
With the new design system the responsiveness of grantnav has definitely improved to being quite usable (that and mobile devices are huge theses days!). There is still work to do but I think we can close this as "overtaken by events"

**Comment by mariongalley** [comment]
Also we now do regularly see people pulling up GN on their phones at in person events :)
