### ISSUE TITLE
Add a 'last obtained time' date to bulk downloads

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#444]
Following on from https://github.com/OpenDataServices/grantnav/issues/394#issuecomment-360881896 , we'd like to have a service whereby developers of external applications that use the GN API-ish service can tell when data has been updated and thus check if they need to download the data again.

**Comment by morchickit** [comment]
That's actually pretty important, even now when it is updated daily. @robredpath @michaelwood  - how hard it is to add this?

**Comment by robredpath** [comment]
@morchickit now that we've got a data store, I think we probably want to be discouraging machine use of GrantNav - if someone's developing something new on top of 360 data, I'd rather be talking to them and seeing how we can support them via the data store. 

There's a further complication that the last updated time on GN might not actually be what you want, because we'll fall back to older versions of data - so the Indigo Foundation data (for example) that we loaded into GN today could be a few days out of date, if we've not been able to get their data for some reason. http://grantnav.threesixtygiving.org/datasets/#datasets-used has the last obtained dates for each data set. 

So, if we want to support machine use of GN, I'd suggest making that page available as a JSON feed so that it can be used alongside the bulk download. OR, we could add the 'last obtained' date into the bulk download.

**Comment by morchickit** [comment]
I was thinking mostly for people who has less tech capacity are using GrantNav GUI to download the search results for further analysis in CSV rather than the machine use and heavy data analysis (I want to know when this grant was available on the app). I think last obtain into the bulk download is a good idea.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add 'last obtained date' to bulk download](https://trello.com/c/Lxt0UQ9L/81-add-last-obtained-date-to-bulk-download)

**Comment by robredpath** [comment]
I've changed the title and added it to Trello :)

**Comment by robredpath** [comment]
We did this
