### ISSUE TITLE
Count of funders on front page and funders table page doesn't match

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#456]
Right now, the front page of GN shows 71 funders but the table page shows 69. h/t @andylolz for the spot in https://forum.threesixtygiving.org/t/grantnav-s-new-approach-to-currencies/197 

We *think* this is because it's only showing GBP funders, but we should either add the switching functionality we talked about, or add some copy to make it clear what the user's seeing.

**Comment by morchickit** [comment]
This still happens. Not sure though that we need the table page... keeping this open for now.

**Comment by mariongalley** [comment]
This is fixed by #819
