### ISSUE TITLE
 Explain that not all publishers are on GrantNav and link to the registry

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#480]
From #393

**Comment by morchickit** [comment]
Is this still relevant? I dont think so... `maybe we should just say that in theory we only show publishers that have valid schema?

**Comment by robredpath** [comment]
I think that if people are really interested in why some data doesn't appear, they'll either look at the [Data used in GrantNav](http://grantnav.threesixtygiving.org/datasets/) page or email us!
