### ISSUE TITLE
Flag when a recipient of a grant is also a funder

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/grantnav#486]
Some small amount grantees are also grantmakers. Based on the charity number field, flag on GrantNav visually when a grantee is also a grantmaker with data on GrantNav. 

This is simply to start flagging re-granting and should not create a new field in GrantNav. @stevieflow correct me here if I missed anything?

**Comment by stevieflow** [comment]
> Based on the charity number field

I dont think this is quite correct.  We would need to check for matches between the ``Recipient Org: Identifier``, and then the``Funding Org: Identifier``

Only when we find a match would we then be able to look at displaying something 

A useful example is Indigo Trust:

- Funder: http://grantnav.threesixtygiving.org/funder/GB-CHC-1075920 (GB-CHC-1075920)
- Recipient http://grantnav.threesixtygiving.org/recipient/GB-CHC-1075920 (GB-CHC-1075920)

It might be best to begin this by displaying such information on the Funder page - to share with people that this funder might also be a recipient.  I dont think it'll always be correct to imply this is about regranting though - all we are saying is that we have found the same identifier in two places (or two different fields of the 360 standard that describe organisations), across the data corpus

**Comment by KDuerden** [comment]
I did research by doing just - checking where a Funding Org:Identifier was in Recipient Org:Identifier column. I found examples of grants for re-granting but also many that were to pay costs, and joint work etc, so the wording does need to highlight that fact. I have a spreadsheet of examples I can share if that is useful.

**Comment by stevieflow** [comment]
> I found examples of grants for re-granting but also many that were to pay costs, and joint work etc, so the wording does need to highlight that fact.

I'd suggest that for now we just flag that there is a match.  We can link through an FAQ answer as to some of the possible reasons, but just want to reinforce that we should try to avoid trying to explain the match insitu

**Comment by mariongalley** [comment]
We've addressed this issue in 2 ways:

1. New For Regrant field & codelist
2. New Org pages that show for each org whether they appear in the data as a Funder and/or as a Recipient

That doesn't solve this case where we suggested fetching data from the charity commission about whether an org is a funder, but it's progress!
