### ISSUE TITLE
Transfer this repo to 360's GitHub Org

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#495]
We want to transfer this to 360's GH org and hand over copyright. We think this is probably quite straightforward, but want to check:
- Does the license let us do this?
- What do we do about the fact that it's current (c) Open Data Services?
- Is there anything contractual we need to do?

**Comment by odscjames** [comment]
We will look at this in 2 stages; transferring the repository and then transferring the copyright.

Me and @BibianaC will try to transfer the repository in the next few weeks.

**Comment by odscjames** [comment]
This has now been moved! https://github.com/ThreeSixtyGiving/grantnav

**Comment by morchickit** [comment]
We can close this now!
