### ISSUE TITLE
JSON download link on grant page

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#51]
Just a check / suggestion / idea - but how feasible / useful is it to be able to add .json to a grant page, to then see that grant data as..... JSON?!

**Comment by morchickit** [comment]
I am not sure this is a user need. We also don't offer it as a CSV on the grant page and we assume that more advance users would be using our datastore. Closing this for now. @stevieflow please re-open it if you think it's still valid for future iterations.
