### ISSUE TITLE
Add a hint to show data timestamp

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#513]
It would be nice to know when the grantnav data was last updated. Maybe in the footer next to "Running version"?

**Comment by Bjwebb** [comment]
BTW, the timestamps for when the data was *downloaded* are at https://grantnav.threesixtygiving.org/datasets/#datasets-used

**Comment by michaelwood** [comment]
> BTW, the timestamps for when the data was _downloaded_ are at https://grantnav.threesixtygiving.org/datasets/#datasets-used

Ah that's useful too - thanks!
