### ISSUE TITLE
Org ID with dots breaks in GrantNav

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#514]
org IDs taken from http://org-id.guide/list/XI-GRID include dots. The single example in GrantNav is a broken link: https://grantnav.threesixtygiving.org/recipient/XI-GRID-grid.5292.c
There are publishers in the pipeline funding universities overseas so this will crop up more in future.

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GN org-ids with dots in try to get served as files](https://trello.com/c/RqmkDPqk/107-gn-org-ids-with-dots-in-try-to-get-served-as-files)

**Comment by michaelwood** [comment]
- https://github.com/ThreeSixtyGiving/grantnav/blob/master/grantnav/frontend/views.py#L999
- https://grantnav.threesixtygiving.org/grant/360G-ptc-gr-02586

**Comment by BibianaC** [comment]
@KDuerden tomorrow afternoon the fix will be deployed.

**Comment by michaelwood** [comment]
@BibianaC I was doing some work on the ES backup cron job so have done a deploy for that which will also have updated grantnav.

**Comment by KDuerden** [comment]
Great news! :)

**Comment by BibianaC** [comment]
Yes, grantnav is now updated. Thanks @michaelwood.
