### ISSUE TITLE
Create Fixed name for funding orgs that have changed name

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#519]
Currently the load process means that the first Funding Org:Name that GN comes across is used as the main name to **display** for that particular Funding Org: Identifier.

We can implement fixed rules for particular Orgs that we know have changed their name and will want their new name to be displayed. This avoids changing the underlying data of old grants, meaning that the original name is still kept but the name under which they are displayed is the latest one.

**Comment by stevieflow** [comment]
To clarify - by "displayed" we mean specifically in the Funder facet search?  

We do not mean this in the grant record
