### ISSUE TITLE
Grant page - items in and not in the schema

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#52]
One suggestion for ordering the data elements in a grant page - put the data that is _not_ mapped to the 360Giving schema to the bottom - meaning more chance to work with fields that are in the schema in a structured way

(this doesnt make a lot of sense)

**Comment by stevieflow** [comment]
Moving to backlog and out of iteration 3

**Comment by robredpath** [comment]
This is fundamentally asking for some sort of visual signalling of which fields on a grant page are in the schema. eg in http://grantnav.threesixtygiving.org/grant/360G-blf-0030141081 the field BIGField_Organisation_Type should look different from the others.

**Comment by timgdavies** [comment]
Visually flagging this as 'Additional data provided by publisher' would be quite useful in communicating the idea that the standard is extensible - and that you can provide additional information if you want.

**Comment by robredpath** [comment]
We do this now
