### ISSUE TITLE
Stats page issues

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#528]
On the current grantnav live the stats page appears to be timing out(?) with the front end server giving a 500 error. In the ES7 version the stats page has been removed though possibly incorrectly (issue #510 )

**Comment by robredpath** [comment]
ES7 GN has now been deployed, so the stats page is now absent. 

https://github.com/ThreeSixtyGiving/grantnav/commit/86c930fddd41e0514c99807c65da1930edfd9f12#diff-462829b9fe1bf62ea30b2162fd9335cb is where it's removed. I'm not sure why - I vaguely recall something about ES7 not supporting stats like that any more?

**Comment by robredpath** [comment]
I think any stats that we need can be derived from the data store now

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review GN issues once ES7 + autoloading is live](https://trello.com/c/lunrGjAJ/22-review-gn-issues-once-es7-autoloading-is-live)

**Comment by michaelwood** [comment]
@KDuerden If memory serves me right I think you had talked about this issue.

Currently this is our last open issue on the Elastic7 upgrade work, I'm wondering if we can close this one if the function of the stats page now been replaced elsewhere in Data Services? thanks

**Comment by KDuerden** [comment]
The stats aren't needed for our purposes, so the only remaining issue is the GrantNav help page, which links to stats to get correct field names for advanced searches - https://grantnav.threesixtygiving.org/help#fields
We could direct to Standard docs instead, and explain how to update the field names to work for searching... although as we're doing the UX research it may be ok to leave it as is.

**Comment by michaelwood** [comment]
Ah I see, another idea is that to retrieve a list of fields, which is very easily to do so maybe a solution is to just add a sentence which contains the full list. 

Note to self: localhost:9200/threesixtygiving/_mapping?pretty

**Comment by KDuerden** [comment]
thanks @michaelwood 
Any thoughts/strong views on this @drkane @morchickit?

**Comment by morchickit** [comment]
I think that we can omit the stats page for now. I also think it was not that used, so happy to remove it from the help section and close this. @drkane ?

**Comment by drkane** [comment]
A full list of fields would be helpful, but it feels like a nice-to-have rather than a must-have. I think we could direct people to the standard docs instead (although I guess translating what the field will look like in elasticsearch is not straightforward).

I think the link to the stats page can definitely go.

**Comment by michaelwood** [comment]
I had a [quick look](https://github.com/ThreeSixtyGiving/grantnav/commit/9a7dabb05b147bf3745270e0a320447b349c4ba2) at how difficult the nice-to-have would be. We can generate a list that looks like this:

![Screenshot_2020-08-18 360Giving GrantNav](https://user-images.githubusercontent.com/493697/90546686-510c9a80-e182-11ea-8dbd-5e70ff884c22.png)

By just asking Elastic what it's current mappings are and putting this into the help page template. The only issue I see is that the dynamically added fields aren't listed.

Happy also just to remove the link!

**Comment by morchickit** [comment]
Ok, I think I am going to close this for now and wait for the user research to come with some answers about this, I don't want us to do double work, and I feel like we still need to do a lot of work with the help page as well, so let's park it for now.

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove broken stats link from grantnav help page](https://trello.com/c/sKbiRWm1/101-remove-broken-stats-link-from-grantnav-help-page)
