### ISSUE TITLE
GrantNav drops grants with non-standard fields (in certain circumstances)

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#529]
GrantNav can fail to import a grant with non standard fields. This happens when a grant is imported with a field that isn't in the standard but has been used by another funder. If the value in the field is of a different type to the existing data then elasticsearch can't save the data.

**Comment by michaelwood** [comment]
@kindly  I remember you saying you had an idea on fixing this

**Comment by robredpath** [comment]
@michaelwood I think https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html is what @kindly was talking about (see also https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html ). We don't want to disable dynamic mapping, I think, because we still want to be able to search on publishers' custom fields, but I think we can safely treat them all as `string` types because we're not going to be trying to do funky things with the data.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it so that differing types in non-standard (additional) fields don't cause GN to drop rows](https://trello.com/c/dEfhbV56/27-make-it-so-that-differing-types-in-non-standard-additional-fields-dont-cause-gn-to-drop-rows)

**Comment by michaelwood** [comment]
Two options:

1) We drop fields which don't have existing mappings (i.e. are not in the standard and are not in additional_data)
2) We do an initial pass of the data and add the mappings to a string type for all fields that we don't recognise (this will slow down the grantnav load), we're not sure if publishers expect to see their extra non-standard fields indexed/visible in GN

**Comment by KDuerden** [comment]
Thanks @michaelwood.
There is an expectation that non-standard fields will show. The extra project references are not that vital but there are plenty of other non-standard fields that do add value to the data, and we would want to be available for search.
Having all non-standard fields be treated as string types makes sense. I only know of one additional field which is formatted as a number and that could be formatted as text without any issues.

> this will slow down the grantnav load
How much will this slow things down? We tend to know about these extra fields in advance and once in a publishers data they are consistent over time, so could the format mappings be stored to speed up the process?

**Comment by kindly** [comment]
It looks like the way to fix this in elastic-search is to use dynamic templates
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html

We can use these to map all JSON possible types to string for any dynamic (not predefined) fields.  If we do it this way it should not slow anything down very much at all.  I have not used this before and seems a little fiddly to setup but seems like the right approach.

**Comment by drkane** [comment]
It also looks like you can set 

```json
{
  "mappings": {
    "date_detection": false,
    "numeric_detection": false,
  }
}

```

to disable detection of those in strings. Could we then rely on mapping date fields from the standard explicitly, and just making sure the numeric fields are passed as numbers in the json?

**Comment by kindly** [comment]
@drkane 
My impression is that using dynamic templates will supersede those options or more precisely if it detects a date or a numeric it will be converted to string anyway.  
However setting them to false would mean elasticsearch would not bother trying to detect them in the first place. 

Agreed that we should make sure all dates in the standard are explicitly defined in the mapping.
We are currently using `keyword` for some and `date` for others and I am not sure why.

**Comment by michaelwood** [comment]
@drkane 
I have deployed a test version with:
https://github.com/ThreeSixtyGiving/grantnav/commit/2ed5b23a9fa667d1e0c0d66f76117dd40b0f2e12

http://latest.es7.grantnav-dev.default.threesixtygiving.uk0.bigv.io/

Looks OK to me.

We get the results that normally get dropped, the possible downside is that we will need to make sure any fields we want are explicitly added to the mapping. However the up side is that a grant with any random fields won't cause the whole grant to be lost and we also somewhat protect ourselves against unexpected data being added to the elastic search index.

**Comment by drkane** [comment]
@michaelwood - looks good, although the test version isn't working this morning (it was last night, and I saw that the number of grants matched the number in the datastore).

Once it's back up there's a couple of things we can check - I'd like to double check the filters work, and check the CSV & Json outputs. But other than that it looks like it's working well.

**Comment by michaelwood** [comment]
Should be back up again. The server is struggling a bit, we could do with doing a tidy up as it has 8 versions of grantnav running on it..! In the meantime I have temporarily added it to our server monitoring.

**Comment by drkane** [comment]
Great - thanks! Can't find any issues with the change, so happy to approve.

I think we can remove the other versions - the only one that might have been used was the government one, but I think the plan is to create a new one for the government data later on.
