### ISSUE TITLE
Allow date range searches to become filter - like it does with amount awarded

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#532]
If I want to explore the data for a particular funder and they have financial year starting 1 April to 31 March, I can filter for these dates but that means I can't (at all, or at least not easily by a general low-tech user?) also search by keyword or similar.

Can award year function like amount awarded and be used to create a bespoke filter.

**Comment by morchickit** [comment]
Closing this, it's a duplicate with this issue #215
