### ISSUE TITLE
Internal fields appearing in grants

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#539]
Two fields which are added by the Datastore are appearing in the list of data for each grant. This makes it look like they were included in the original dataset.

Suggested solution would be to hide these entirely - they're internal fields that don't need to be shown to the outside world.

The fields are:

 - `additional_data_added`
 - `id_and_name`

![Screenshot_2020-02-26 360Giving GrantNav](https://user-images.githubusercontent.com/1049910/75347011-c2d0ef00-5897-11ea-8f7f-a56f459733f3.png)

**Comment by michaelwood** [comment]
Thanks - yes we need to add them to https://github.com/ThreeSixtyGiving/grantnav/blob/master/grantnav/frontend/templatetags/frontend.py#L66

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove internal fields from display](https://trello.com/c/FO4Ubu9m/35-remove-internal-fields-from-display)

**Comment by michaelwood** [comment]
(pending deploy to sever )
