### ISSUE TITLE
"Smallest" Table column in Funders view is sometimes hidden

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#540]
The "Smallest" column in the Recipients table for a Funder is not present in the table when the number of recipients < 15.

It is in the html but is set to display: none , see
```
$(td).show();
$(th).show();
```
Examples:
5 grants: https://grantnav.threesixtygiving.org/funder/GB-CHC-210291
15 grants: https://grantnav.threesixtygiving.org/funder/GB-CHC-1111360

Possible culprits: dataTables?

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav Funder table missing a column](https://trello.com/c/jsrpXFxD/41-grantnav-funder-table-missing-a-column)

**Comment by mariongalley** [comment]
Superseded by new orgs page
