### ISSUE TITLE
Add a banner to the COVID19 tracker 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/grantnav#549]
Can we add a temporary banner from GrantNav homepage to the COVID19 Tracker? I suspect people will look at it as well in GrantNav

**Comment by stevieflow** [comment]
I would suggest this needs to therefore be specified (what color, text, graphics, click action etc)

**Comment by morchickit** [comment]
THIS IS FOR @drkane To discuss with Anna.

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add banner to GN to refer to COVID tracker](https://trello.com/c/oQUJqxkY/93-add-banner-to-gn-to-refer-to-covid-tracker)

**Comment by michaelwood** [comment]
Something visually like this was suggested on our dev call today:

![covid-banner](https://user-images.githubusercontent.com/493697/92397652-1792d380-f11f-11ea-9be6-f92e56dc2de7.png)

**Comment by BibianaC** [comment]
[Link to COVID19 tracker](https://covidtracker.threesixtygiving.org/)

**Comment by BibianaC** [comment]
Comments from Anna:
- please can it be in Roboto font? 
- can you put a hyphen in 'COVID-19'? 
- can you remove 'New'? It's not new anymore
