### ISSUE TITLE
Facets: Add fields

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#568]
- It's clear how the world will be different when the work is completed

There will be facets in GN for fields that are faceted in Insights but not in GN. Exact scope tbc

Must include:
* Funding org type - we want people to be able include/exclude govt, lottery data
* Some geo stuff - region and district data from the data store

After that:
* Some recipient org stuff, detail tbc

- It's clear what will and won't be done

- Any uncertainty, assumptions, dependencies or constraints are recorded

- There's an order-of-magnitude estimate of how long it will take

hours per facet 

- The work's been approved by someone at ThreeSixtyGiving

- There are links to everything that's written down about the work - such as plan.io tickets, GitHub issues

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by mariongalley** [comment]
> Must include:
> 
> Funding org type - we want people to be able include/exclude govt, lottery data
> Some geo stuff - region and district data from the data store

This is done

> After that:
> 
> Some recipient org stuff, detail tbc

This is not done

**Comment by mariongalley** [comment]
Closing this - we had the option to introduce recipient org type filtering but we have very limited space - perhaps when we do Advanced Search
