### ISSUE TITLE
Facets: Make long facets more usable

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#569]
- It's clear how the world will be different when the work is completed

We'll have multi-select dropdowns for funding org, recipient org (+ any others that make sense) 

Blank search will show a few examples, so that we still get the benefit of showing people what they can look for

- It's clear what will and won't be done

We'll make multi-select dropdowns work, but styling can be done next sprint as this may require input from a graphic designer

- Any uncertainty, assumptions, dependencies or constraints are recorded

#571 probably needs to be done first, although doing this first might just result in needing to do some rework

- There's an order-of-magnitude estimate of how long it will take

hours per facet

- The work's been approved by someone at ThreeSixtyGiving

Yes 

- There are links to everything that's written down about the work - such as plan.io tickets, GitHub issues

**Comment by robredpath** [comment]
Note: recipient org facet only shows top X (currently 50, could be 1k or so). We should add some text to explain this!

**Comment by kindly** [comment]
This is has been attempted in #579.
Examples when blank have not been added yet but I see this as more a UI issue for another stage.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by robredpath** [comment]
We did this
