### ISSUE TITLE
Facets: "Everything but" workflow

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#570]
- It's clear how the world will be different when the work is completed

~~Users will be able to select all and search to remove from the list in facets that have a tendency to get long.~~

EDIT: A better interaction, we think, would be an include/exclude toggle in the facet, along with the search box

URLs will switch from using an 'include list' to an 'exclude list' 

- It's clear what will and won't be done

The JS will work out whether this is an include or an exclude model and will update the URL and results as appropriate 

- Any uncertainty, assumptions, dependencies or constraints are recorded

This does require #571 to be done first, in order to be implement this in the way that we plan. 

- There's an order-of-magnitude estimate of how long it will take

Days

- The work's been approved by someone at ThreeSixtyGiving

Yes

- There are links to everything that's written down about the work - such as plan.io tickets, GitHub issues

**Comment by kindly** [comment]
This is part of pull request #579 and is mostly done.

**Comment by robredpath** [comment]
This has been improved by the recent work
