### ISSUE TITLE
Make URLs more useable

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#571]
- It's clear how the world will be different when the work is completed

We'll be URLs of the form ?q="badgers"&FundingOrgs=["ABC","DEF"] etc throughout the site, and no JSON blobs in URLs. These will be generated as users interact with the facets on the search results page, so that the back button still works, URLs can be hacked around with, and sharing the URL results in the recipient seeing exactly the same thing as the 

- It's clear what will and won't be done

We'll build a translation layer so that the backend doesn't need to think about URL params. 

We'll make any necessary updates to facets to make this work. 

This does mean that GN doesn't work without JS; we're ok with this! 

- Any uncertainty, assumptions, dependencies or constraints are recorded

We don't really know how hard this will be; it feels like it could be quite straightforward, or really challenging. We'll check in regularly to make calls on priority. 

- There's an order-of-magnitude estimate of how long it will take

Depends on what's involved - this could be days to weeks, as it's a significant logical change 

- The work's been approved by someone at ThreeSixtyGiving

Yup!

- There are links to everything that's written down about the work - such as plan.io tickets, GitHub issues

https://github.com/ThreeSixtyGiving/grantnav/issues/40 is a previous issue on this

**Comment by kindly** [comment]
Pull request #577 fixed this.

The only deviation from the above issue is that on multiple facet selections (eg curruncy) the url looks like

```/query=*&currency=USD&currency=GBP```

This is the standard way of doing multiple selections using GET parameters however it is not as compact as doing something like

```/query=*&currency=USD|GBP```

This way was not chose currently as it requires an agreement about what delimiter to use and a check to see if the delimiter is somewhere in the data.
