### ISSUE TITLE
Exact match/best match mode switching

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#587]
A potential solution for the problem of how we let users know the scope of what they've searched for. Introduce the concept of "exact" and "best match" searching, with the option to switch between them.

"exact" searching would add quotation marks by default to the search query, or some other way of doing a more targeted search on es. "best match" would be a wider search, as with the current search term.

This is just an idea we had - would need testing and refining to see if it actually worked.

**Comment by michaelwood** [comment]
I think we have mostly covered this by adding in hint text if you use two words which is the usual case when quotes are needed. If one word is used the highest scoring match will be the single word anyway.

We also have the "Our guide to [targeting your search](https://help.grantnav.threesixtygiving.org/en/latest/search_bar/)"  which covers this .
