### ISSUE TITLE
Add facets - both existing fields and using additional data pulled in from data store

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#593]

**Comment by drkane** [comment]
Facets to add:

- Funder type (I think this should be the first one) - this has four options
- Type of recipient (up for discussion - might not be the right thing to do)

Facets to change:

- Region/Country/Local Authority/Ward - change to use the beneficiary location where available

**Comment by robredpath** [comment]
Thanks, @drkane . For "change to use the beneficiary location where available", do you mean adding some kind of "best available location" field which contains the beneficiary location, and if that's not specified then fall back to the recipient location, and then filtering based on that?

**Comment by drkane** [comment]
That's right - There's something similar used in the covid tracker (although it prioritises based on whether the data is at LSOA level first):

https://github.com/ThreeSixtyGiving/covid19-tracker/blob/3d8ff3dd57c8eb38b5205a3431afb3fd8fbf10ab/covidtracker/fetch_data.py#L100-L104

**Comment by drkane** [comment]
It might be worth us coming up with an "official" method for working out the location, and then implementing it in the datastore

**Comment by michaelwood** [comment]
I've added the Funding organisation type facet (based on the TSGFundingOrganizationType field). I need a bit more clarification (at the next meeting?) about what other facets are wanted and what fields to use. As mentioned the ideas around "best available" for a field would need to be implemented in the `additional_data` in the datastore, as those kinds of heuristic aren't able to be implemented in an elasticsearch query (afaik).

**Comment by drkane** [comment]
Good point. I think the datastore needs to have an opinion on Recipient Organisation Type - using the `RecipientOrgInfos` array

For geography, perhaps what we need to do is redo how `recipientWardNameGeoCode`, etc are worked out, to use the `locationLookup` list instead.

**Comment by michaelwood** [comment]
@drkane  I had a go at recipientOrgInfos with something simple like:

```python

    def update_additional_data(self, grant, additional_data):
        try:
            # Take the first active recipientOrgInfo's first organisation Type
            for org_info in additional_data["recipientOrgInfos"]:
                if org_info["active"]:
                    additional_data[self.ADDITIONAL_DATA_KEY] = org_info["organisationType"][0]
                    break
        except KeyError:
            print("errr")
            print(additional_data)
```

To add a dedicated key called `TSGRecipientOrgType` to `additional_data`. However there are a reasonable number of grants[1]  that don't have a value for recipientOrgInfo presumably due to not being able to find a match in the FTC data. Should we just set the value to "unknown" ?

[1]
```sql
select count(id) from view_latest_grant where jsonb_array_length(additional_data -> 'recipientOrgInfos') = 0 or additional_data -> 'recipientOrgInfos' = null;
```
`86,620 (out of 473,778)`

**Comment by drkane** [comment]
The wording used in insights for orgs without an organisation type is "Identifier not recognised". We spent a bit of time trying to work out what the best form of words is. The issue with the "unknown" values is they cover two different types:

- those organisations that don't have an identifier (eg because they are too small to be registered)
- those organisations where they have an identifier but the publisher hasn't included it.

It's tricky to come up with something that covers both of these. @KDuerden may have thoughts.

**Comment by KDuerden** [comment]
When we came up with "Identifier not recognised" I think we were trying to not get too technical.
However given the feedback that came via the GN user research about wanting to understand more what people are looking at, and understand gaps or quality issues, I think we could approach this as a teachable moment.

In publisher support we talk about 'internal' and 'external' org identifiers. If there is scope to include short guidance text to set out what we mean, that might be a way to approach it.

**Comment by robredpath** [comment]
@KDuerden the new GrantNav documentation is set to be significantly more discursive than the previous Help page ([sneak preview](https://grantnav.readthedocs.io/en/update-docs/#) so there's the opportunity to write things down there. The templates for the new design for GN give quite a lot of space for info links in appropriate places, so we can link to it from somewhere relevant in the interface.

**Comment by KDuerden** [comment]
That's great, I'll put aside some time to look at this properly!

I think we should label things with the question 'what am I looking at? / why is this data here?' in mind. So it might be easier to decide terms based on draft pages with the information in place (ie I can't 'picture things' based on the code atm)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by michaelwood** [comment]
Tidying up issues assigned to me - Think this issue is broadly resolved. Closing for now.
