### ISSUE TITLE
Work out how to make link to Insights work with additional data

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#598]
We want to make sure that people can click through to Insights from GrantNav, in order to use the Insights tools to understand their GrantNav search results. 

Currently, Insights re-does a lot of the work of the data store, because there's no way to tell it that the data's being sent with all of the necessary additional data included. 

We should make it so that Insights can use the appropriate additional data.

**Comment by michaelwood** [comment]
This data will be available to insights once https://github.com/ThreeSixtyGiving/datastore/pull/65 is merged

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Insights <> GrantNav integration](https://trello.com/c/Ug3lhP49/152-insights-grantnav-integration)

**Comment by robredpath** [comment]
This is done ^^

**Comment by mariongalley** [comment]
@robredpath Would it be worth opening a separate ticket to increase the size of search that can be opened from GrantNav above the current 1,000? I have a feeling that might already have been raised somewhere but not sure

**Comment by mariongalley** [comment]
Here it is #772
