### ISSUE TITLE
'Explore' button accessibility in new design

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#604]
In the new design on the Grantnav home page we have 3 x explore buttons, if you were using a screen reader/other accessibility software these would not be useful as they have no link context.

https://cdn.threesixtygiving.org/components/preview/grant-nav--default.html

Suggest that they are changed to 'Explore Grants'... 'Explore Funders' ... etc

**Comment by drkane** [comment]
we'll take a look at this. We've come up with a spreadsheet with all the "micro copy" on various pages to take a look at: https://docs.google.com/spreadsheets/d/1wg6VkwwIM2mr5vXKlpTr-x2XnEZicP39oFCcWNN1Lbg/edit#gid=1160001354

**Comment by robredpath** [comment]
I've put some comments in, @drkane

**Comment by Lathrisk** [comment]
The new button copy has now been added to the dev site, and the design PR: #603
