### ISSUE TITLE
Get Help link doesn't link to new docs site

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#606]
I've emailed @drkane to discuss the final location of the new docs. When we've got that set up, we should change the link, and remove the old help page.

**Comment by drkane** [comment]
The site is now pointing to https://help.grantnav.threesixtygiving.org/

**Comment by robredpath** [comment]
Homepage:

* About the data -> https://help.grantnav.threesixtygiving.org/en/update-docs/data.html# 
* Remove forum link - replace with "about 360giving" -> about 360 page on main site
* Get Help -> help site home (currently ok)

**Comment by robredpath** [comment]
Search results page:
* "our guide to refining your search" -> Search Bar page
* "Learn more about the filters" -> Refining Results
