### ISSUE TITLE
Funder page - icons not showing on table

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#609]
![image](https://user-images.githubusercontent.com/1049910/110493336-85c64c00-80ea-11eb-87cc-930a95878e9d.png)

Firefox 86, Windows 10

May also occur on other pages (recipient, region, etc)

**Comment by michaelwood** [comment]
Looks like the font 	font-family: 'Glyphicons Halflings'; isn't available for everyone and needs loading
