### ISSUE TITLE
Funder page - alignment of stats on right hand side

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#610]
![image](https://user-images.githubusercontent.com/1049910/110493711-c9b95100-80ea-11eb-929e-fcdc1f88fd7f.png)

Amounts should be right-aligned. Dates in the first column look odd.

Suggest this is upgraded to something based on the new stats box when this is available.

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav summary pages](https://trello.com/c/VMO0SMgO/155-grantnav-summary-pages)

**Comment by odscjames** [comment]
> based on the new stats box when this is available.

Can I ask if this is now available, and if so where I would see it? Not sure what "new" means.

**Comment by robredpath** [comment]
@odscjames it's at https://cdn.threesixtygiving.org/components/detail/search-summary.html

**Comment by odscjames** [comment]
Ok so looking at https://cdn.threesixtygiving.org/components/detail/search-summary.html this is intended to replace the search box on the normal search page. I'd either have to make code changes to pull both style of search box in at once, or I'd have to change both search boxes at once. 

**Should we change both search results summaries boxes at once?** 

https://github.com/ThreeSixtyGiving/grantnav/issues/597#issuecomment-783281674 comment says we shouldn't, so I'm not clear on what needs doing.

Or instead I could look into directly fixing the individual points mentioned at the top of this thread without bringing in the new style?

ps. This is about funder pages but I think also applies to Recipient pages now? http://grantnav.threesixtygiving.org/recipient/360G-cabinetoffice-org%3AMHCLG-PH-ID-0000016

**Comment by odscjames** [comment]
I posted a comment which I then deleted as I realised I was confused by something (if anyone is confused by email).

I noticed however something has to be renamed, so I did a small PR #736 to do that

**Comment by odscjames** [comment]
I've started trying to apply https://cdn.threesixtygiving.org/components/detail/search-summary.html but we are going to need much more spec details before we can finish this up. 

This design component assumes there are graphs on the left side and all stats are on the right:
* For Search, Funders and Recipient pages we need defined what graphs should be on the left?
* Currently our layout of stats is over 2 columns; so do we just put all these stats in the right hand column now?
* We also need to check the interaction of the currency modal with this new look

This could take a while to sort out; **in the meantime, should I just see if I can quickly fix the issues noted at the top of this thread in the existing boxes?**

ps. This is about funder pages but I think also applies to Recipient pages now? http://grantnav.threesixtygiving.org/recipient/360G-cabinetoffice-org%3AMHCLG-PH-ID-0000016

**Comment by odscjames** [comment]
#597 may be related

**Comment by drkane** [comment]
@odscjames - I think you're right that for the Funder and recipient pages we need a wider look at the layout & contents (including seeing if the search summary box is a useful component to use on the page) which is outside the scope of this issue.

I think in the meantime a quick fix to tidy up the layout would be enough.

For the search summary box on the search page we're a bit clearer on what we need (see issue #597) but there is still some refinement needed.

**Comment by odscjames** [comment]
Turns out @Lathrisk is actively working on #597 so I'll see how that goes - a quick fix may be unnecessary, but if it is we can look at that.

**Comment by mariongalley** [comment]
@odscjames @Lathrisk we're fairly keen to get a minor fix implemented on this as part of the current GrantNav work (i.e. this week, just to address the dates going over multiple lines regardless of display size). Would you be able to let me know if that'll be feasible?

**Comment by Lathrisk** [comment]
Hi Marion, we can definitely get this looked at this week. I've been off for a few days (apologies for not

**Comment by mariongalley** [comment]
No worries at all, I heard you were coming back today so just wanted to make sure you had as much advance notice as possible!

**Comment by Lathrisk** [comment]
I've included a fix for this in the Search Summary box work in #745 (#597) so that we can review that during the lunchtime meeting. It is also now deployed to the dev server.

**Comment by mariongalley** [comment]
Call with Jared, David R, Michael and David K: Change looks good.
