### ISSUE TITLE
Static pages - use prose module

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#612]
Static pages should use the prose module from the design system, this will set appropriate font sizes, etc.

Eg http://grantnav-dev.default.threesixtygiving.uk0.bigv.io/about

https://cdn.threesixtygiving.org/components/detail/prose.html

(the prose part of the design system doesn't seem to be in the CSS file - [see my comment](https://github.com/ThreeSixtyGiving/grantnav/issues/605#issuecomment-789868762))

**Comment by BibianaC** [comment]
Also check #631

**Comment by odscjames** [comment]
It's a bit hard to know what counts as a static page as some pages like /datasets are mostly static with one dynamic table.

Here's my list I've checked:

* about - already uses
* take_down_policy - already uses
* terms - already uses
* datasets - already uses
* developers -  already uses

Are there any pages that should count as static I missed? What pages should this ticket apply to?

**Comment by Lathrisk** [comment]
This is done
