### ISSUE TITLE
Search results - gap between "filters applied" and stats box is too small

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#613]
![image](https://user-images.githubusercontent.com/1049910/110494642-b35fc500-80eb-11eb-81fb-b55b2f0b2a38.png)

Inserting `<div class="spacer-3"></div>` before the filter panel seems to work.

**Comment by odscjames** [comment]
@drkane This seems to have been fixed by something else - can this be closed?

**Comment by Lathrisk** [comment]
On Dev
