### ISSUE TITLE
Currency modal needs updated 

### ISSUE THREAD

**Issue by Lathrisk** [ThreeSixtyGiving/grantnav#614]
**Describe the bug**
The currency modal doesn't work and is not updated to the new design.

**To Reproduce**
1. Go to `http://grantnav-dev.default.threesixtygiving.uk0.bigv.io/funder/GB-CHC-265647`
2. Click on the number beside `Total Non-GBP grants`
4. See error - no modal appears

**Expected behavior**
The modal appears with a table of all Non-GBP grants

**Comment by odscjames** [comment]
I now get this - is this already fixed?

![currency-modal](https://user-images.githubusercontent.com/37832009/120306708-05b71900-c2ca-11eb-8768-cfa52be54735.png)

**Comment by robredpath** [comment]
This now behaves as expected
