### ISSUE TITLE
Alignment of the text boxes and button is incorrect

### ISSUE THREAD

**Issue by Lathrisk** [ThreeSixtyGiving/grantnav#615]
**Describe the bug**
Alignment of the text boxes and button is incorrect

**To Reproduce**
Go to `http://grantnav-dev.default.threesixtygiving.uk0.bigv.io/search?query=%2A&default_field=%2A&sort=_score+desc`
Look at the currency form
It is misaligned

**Expected behavior**
Properly aligned boxes and buttons

**Comment by odscjames** [comment]
Can you provide a screenshot? I can't see any buttons in that form, and what is there looks correct to me.

**Comment by Lathrisk** [comment]
I think the issues was actually with the amount awarded filter, and it has been fixed already :tada:
