### ISSUE TITLE
The recipient and funder filters show more than 50 options

### ISSUE THREAD

**Issue by Lathrisk** [ThreeSixtyGiving/grantnav#616]
The previous design used dropdown boxes to show all filter options. This has been reverted to displaying only 50 options. The filters should be updated to show all options, either as a text box filter or the dropdown option.

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)
