### ISSUE TITLE
Long descriptions in grant summaries

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#618]
Some grants have a very long description, which ends up taking a lot of space in the search results. Should we cap the number of characters and add a "read more" link.

![Screenshot_2021-03-17 360Giving GrantNav](https://user-images.githubusercontent.com/1049910/111460722-35677380-8714-11eb-8d6c-6b552aa23db0.png)

**Comment by odscjames** [comment]
Related to #640

**Comment by odscjames** [comment]
See screenshot on https://github.com/ThreeSixtyGiving/grantnav/pull/702#issuecomment-851995490 - that has been merged in. Can this be closed now?

**Comment by robredpath** [comment]
@odscjames looks good - it looks a bit like it's inline with the sentence, though, so could we have it on another line and right-aligned?
