### ISSUE TITLE
Hyperlinks in Tables aren't clear

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#620]
The new table styling doesn’t distinguish between text that is a hyperlink and text that isn’t.

Recipient and Title are both hyperlinks, Amount and Description aren’t but all look the same.

![image](https://user-images.githubusercontent.com/1049910/111611158-0c0e1c80-87d4-11eb-9fbe-276a1574ceb6.png)

May be worth fixing in the design system first.

**Comment by drkane** [comment]
Just looked, and I think the colour variables referred to in theme.css:

```
a {
  color: var(--colors-alt);
  text-decoration: none;
  -webkit-text-decoration-skip: objects; }
  a:hover, a:focus {
    color: var(--colors-alt);
    text-decoration: none; }
  a:active {
    color: var(--colors-orange);
    text-decoration: none; }
```

aren't ever defined in the CSS file. ([see this comment](https://github.com/ThreeSixtyGiving/grantnav/issues/605#issuecomment-789868762))

**Comment by drkane** [comment]
Improvements in the design system should now fix this:

https://github.com/ThreeSixtyGiving/360-ds/blob/881bff7c94c470c7c216bcc42c21961d319aeca5/src/components/03-components/table/table.scss#L12-L16

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav summary pages](https://trello.com/c/VMO0SMgO/155-grantnav-summary-pages)

**Comment by BibianaC** [comment]
@drkane I see that this issue is already fixed. Can we close it?
