### ISSUE TITLE
"Filters applied" section doesn't show what category each of the filters are in

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#621]
This is usually obvious (eg London is a region, £100-£1000 is amount) but sometimes ambiguous - eg between recipient organistion, funding organisation and funding organisation type

![image](https://user-images.githubusercontent.com/1049910/111611517-74f59480-87d4-11eb-9613-14516bb66209.png)

Could do something like this to make it clearer:

![image](https://user-images.githubusercontent.com/1049910/111611803-c0a83e00-87d4-11eb-8a9b-94daf5b54093.png)

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by michaelwood** [comment]
Fixed this as part of the Geo types improvement work. Thanks
