### ISSUE TITLE
"Filters applied" section isn't shown if there are no results

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#622]
eg http://grantnav-dev.default.threesixtygiving.uk0.bigv.io/search?query=bananas&default_field=%2A&sort=_score+desc&fundingOrganization=GB-GOR-PB188&fundingOrganizationTSGType=National+Lottery&awardDate=2019&fundingOrganizationMore=true&recipientOrganizationMore=true&recipientRegionNameMore=true&recipientDistrictNameMore=true&fundingOrganizationTSGTypeMore=true&currencyMore=true&awardYearMore=true&amountAwardedFixedMore=true

The award date filter is set to `2019` but this isn't shown in the results, so not clear that the filter is also contributing to no results being found. The `fundingOrganizationTSGType` and `fundingOrganization` filters are also set but these aren't shown at all.

![image](https://user-images.githubusercontent.com/1049910/111612061-06650680-87d5-11eb-8b05-76a02940ba78.png)

This is different from the current behaviour.

**Comment by odscjames** [comment]
![filtersapplied](https://user-images.githubusercontent.com/37832009/122409602-298d8680-cf7b-11eb-82c2-3fd7d747b16c.png)

Can this be closed now?

**Comment by mariongalley** [comment]
Yes, I think that solves the problem of not being able to get any results without hitting the back button or starting over. Does that match what we discussed in the "GrantNav Filters" call @drkane @robredpath ?

**Comment by robredpath** [comment]
This is great, thanks @odscjames !

I've got some ideas about other things and how we link to the docs, but I'll put those in another issue (see #744)

**Comment by drkane** [comment]
Awesome, thanks @odscjames
