### ISSUE TITLE
Redundant info in the URL

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#623]
eg in `http://grantnav-dev.default.threesixtygiving.uk0.bigv.io/search?query=*&default_field=*&sort=_score+desc&fundingOrganizationTSGType=National+Lottery&fundingOrganizationTSGType=Grantmaking+Organisation&fundingOrganizationMore=true&recipientOrganizationMore=true&recipientRegionNameMore=true&recipientDistrictNameMore=true&fundingOrganizationTSGTypeMore=true&currencyMore=true&awardYearMore=true&amountAwardedFixedMore=true&fundingOrganization=false&fundingOrganization=GB-GOR-PB188&fundingOrganization=GB-GOR-PC390`

I don't think the `...More=true` items do anything with the new filters? So could be removed for cleaner URLs

They are:
- `fundingOrganizationMore=true`
- `recipientOrganizationMore=true`
- `recipientRegionNameMore=true`
- `recipientDistrictNameMore=true`
- `fundingOrganizationTSGTypeMore=true`
- `currencyMore=true`
- `awardYearMore=true`
- `amountAwardedFixedMore=true`

**Comment by odscjames** [comment]
This may have some crossover with @kindly work.

**Comment by odscjames** [comment]
I've done https://github.com/ThreeSixtyGiving/grantnav/pull/735 to remove this but I want @kindly to check this, as he originally did this and I'm not clear about the purposes of them.

**Comment by kindly** [comment]
These should be fine to delete now as they are not used anymore.  The facets now have a scrollable list and not a see more/ see less links.
