### ISSUE TITLE
Improvements to new filters

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#624]
For discussion/thinking:

 - Groups could be open all the time to show available filters (ie, the red bits, not the blue bits)
 - Apply button is inconsistent between filters - how do we show what is or isn't needed
 - Difference in response depending on whether it's an "apply" filter or not - redirect vs javascript.

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by mariongalley** [comment]
Agree that having an "Apply" button in some cases but not others is odd, could we make it consistent so it's always/never there? Or let you change as many filters as you want and have a global refresh search type of CTA?

**Comment by robredpath** [comment]
Today, we:
* Said that we will do the groups open all the time thing
* Will be consistent within facet types wrt: apply buttons
