### ISSUE TITLE
Static pages needs some design attention

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#631]
- space at the bottom of copy
- review copy + links (eg where icons come from)

**Comment by BibianaC** [comment]
@robredpath who would be the appropriate person to review this?

**Comment by BibianaC** [comment]
Also check #612

**Comment by odscjames** [comment]
I have started looking at the "space at the bottom of copy" issue but the "review copy + links (eg where icons come from)" issue needs clarification.

**Comment by robredpath** [comment]
@mariongalley will ask Katie (comms at 360) to review the copy on those pages for branding and language/tone etc. @odscjames - don't wait for that to happen before moving on to other things; we'll deal with applying the changes when we're ready. 

Any technical content that may be superfluous should be reviewed by ODSC before removing - I can advise the best person on a case-by-case basis. 

We should remove the line "Forum and help icons are from Icons 8" from the datasets page, because that's not true any more.

**Comment by odscjames** [comment]
> We should remove the line "Forum and help icons are from Icons 8" from the datasets page, because that's not true any more.

Done and merged in

**Comment by BibianaC** [comment]
Space at the bottom of the copy is now done and deployed.

What is left is the review copy.

**Comment by BibianaC** [comment]
Open new ticket for what is left. 
https://github.com/ThreeSixtyGiving/grantnav/issues/730
