### ISSUE TITLE
Add a link to the search bar help from the home page - above and to the right of the search bar

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#633]

**Comment by Lathrisk** [comment]
Potentially use wording from results page on the home page

**Comment by BibianaC** [comment]
Link: https://help.grantnav.threesixtygiving.org/en/latest/search_bar.html

**Comment by odscjames** [comment]
How is this? (narrow and wide screens)

![633-2](https://user-images.githubusercontent.com/37832009/120474129-ba6f3a00-c39f-11eb-9bd0-27e49173d247.png)


![633-1](https://user-images.githubusercontent.com/37832009/120474132-bb07d080-c39f-11eb-8a0a-e2a0c2639f01.png)

**Comment by mariongalley** [comment]
Yep, looks great
