### ISSUE TITLE
"No Results" page isn't very helpful

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#634]
If someone has refined their search to the point that there are no results, we don't help them much. 

We should look at wording and suggestions for that.

**Comment by drkane** [comment]
See also #622

**Comment by mariongalley** [comment]
Add:
In the list of "Try something like"
- Removing some filters
- To clear your search, click here (link back to homepage)

Also in the sentence "Your search - ""gfhdif;jdsi;nkl;"" - did not match any records.", we could include details of the filters applied in addition to the search, as these also narrow it down.

Could we hide facets that won't do anything e.g. here I have the Amount facet even though I can't use it as there are no results:
![image](https://user-images.githubusercontent.com/82958988/120499740-32e1f500-c3b8-11eb-8a33-3a8381653248.png)

**Comment by mariongalley** [comment]
Suggest we add the bullet points as part of this design issues work. If we can add detail of the filters that would be great, but anything too complex we should leave until a future iteration.

**Comment by odscjames** [comment]
There is a pull request to add the 2 bullet points.

Other things: I can remove the Amount facet by simply adding the following code to grantnav/frontend/views.py,  get_amount_facet_fixed func, just after `results = get_results(json_query)`

    # If there are no documents at all, don't show this facet as it is useless
    any_results = [True for bucket in results["aggregations"]["amountAwardedFixed"]['buckets'] if bucket['doc_count']]
    if not any_results:
        del(main_results["aggregations"]["amountAwardedFixed"])
        return

In the case of searching for a string that does exist but then selecting a amount facet with zero results, this works - the facet is still there so user can change filter.

In the case of searching for a nonsense string we now get: 

![noresultsnofacets](https://user-images.githubusercontent.com/37832009/122208678-81ed5700-ce9b-11eb-8922-49980524429c.png)

What do you want to do here - make that live as is? Remove some/all of the content in the left hand column first? (may require changes to design system and thus take longer)

**Comment by drkane** [comment]
Thanks @odscjames. I think a key part of this discussion is #622 - whether the filters that are applied are shown back to the user when it says there aren't any results.

I think it's important that the current filters are displayed as part of the context of the no results, and also that if we're saying that removing the filters can help that there's a way of them doing that (without having to use the back button).

**Comment by odscjames** [comment]
I've had a look at part of this - The idea was to put the same filters applied line you get when there are results on the no-results page:

![filtersapplied](https://user-images.githubusercontent.com/37832009/122409602-298d8680-cf7b-11eb-82c2-3fd7d747b16c.png)

This is done by going to grantnav/frontend/templates/search.html and adding in:


            {% if selected_facets %}
              {% include 'components/filter-summary.html' %}
              <div class="spacer-4"></div>
            {% endif %}


But it doesn't work fully; the facet you have previously selected is not always returned:

* Search "Dogs", put in amount £1 to £2  - Filter does appear :green_circle: 
* Search "parrots", select £50,000-£100,000 - Filter does appear :green_circle: 
* Search "Parrots", filter from 2011 Jan to 2011 Jan - Filter does appear :green_circle: 
* Search "Dogs", select 2021, search "Parrots" - Filter does not appear :red_circle: 
* Search "Dogs", select "Yorkshire and humber", search "Parrots" -  Filter does appear :green_circle: 
* Search "Dogs", select "Southwark London Boro", search "Parrots" -  Filter does appear :green_circle: 
* Search "Dogs", select "Devolved Goverment", search "Parrots" -  Filter does appear :green_circle: 
* Search "Dogs", select funding org to include "Suffolk Community Foundation", search "Parrots" -  Filter does appear :green_circle: 
* TODO a test for exclude a funding org
* Search "Dogs", select recipient org to include "Dogs first", search "Parrots" -  Filter does appear :green_circle: 
* TODO a test for exclude a recipient org

**Comment by odscjames** [comment]
> Search "Dogs", select 2021, search "Parrots" - Filter does not appear :red_circle:

I have managed to fix this and this is now merged to master - and the screenshot above (the "no results" page with the "filters applied" line is done)

The only thing left to look at is what appears in the left hand column

**Comment by odscjames** [comment]
Ok, I've just done a manual test using the test scripts from the comment above to see how the left hand column behaves on the no results page. Unfortunately, about half of the search options have problems of some kind or other. Each of these will need to be fixed separately, so this will be a bit of work. 

Given this, **I'm going to suggest for now we remove the left hand column entirely on the no results page, close this issue, and spin off a new issue to discuss and prioritise what should be in the left hand column on the no results page.**

**Comment by odscjames** [comment]
#747 removes the left column:

![noleftbar2](https://user-images.githubusercontent.com/37832009/122548647-88113e00-d029-11eb-86fd-0773126d90ad.png)
![noleftbar1](https://user-images.githubusercontent.com/37832009/122548649-88a9d480-d029-11eb-9361-f76c4a3913d0.png)

**Comment by robredpath** [comment]
Heh. I did not realise that those were two separate pages. 

I've created #748 for us to look at the latter at some point.

**Comment by odscjames** [comment]
@mariongalley @drkane I'm going to close this now? I think we have picked up immediate things and we have #748 and #744 for more.

Changes aren't fully live yet but will be soon (It's Friday afternoon)
