### ISSUE TITLE
Remove "Search results" header as it now duplicates "your search returned"... 

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#636]

**Comment by michaelwood** [comment]
It's not quite the same thing as the "your search results" contains the field searched. "Your search ‘moo’ returned 10 results in ‘Recipients’". Agree the duplication though, needs some design.

**Comment by BibianaC** [comment]
Something that could be removed is `Displaying xxxx grants` in `Search results`. As this is the part that looks duplicated to me.

![Screen Shot 2021-05-21 at 13 50 19](https://user-images.githubusercontent.com/9610927/119139961-8446c780-ba3b-11eb-8a89-8a9b3319522b.png)

**Comment by robredpath** [comment]
@odscjames let's leave this until after the search summary card gets worked as that will change how this whole area looks
