### ISSUE TITLE
Pagination should show correct number of pages 

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#637]

**Comment by robredpath** [comment]
(also should use new URL syntax. And might not be showing the last page).

**Comment by odscjames** [comment]
The title is a bit unclear but I'm taking it to mean "should show **Total** number of pages"

How about putting the number of the last page at the end, like this?

![paging](https://user-images.githubusercontent.com/37832009/120358530-7a0baf80-c2fe-11eb-84f6-b591535041b5.png)

**Comment by robredpath** [comment]
@odscjames if you search for "donkeys" then you get this:

![Screenshot 2021-06-02 at 11 35 16](https://user-images.githubusercontent.com/641009/120466122-9b1fdf00-c396-11eb-84ae-c5c671cb0cf3.png)

even though there are two pages of results. 

> How about putting the number of the last page at the end, like this?

I don't think that helps here - in the case of "donkeys" (2 pages of results), we wouldn't want the dots between the first and second page number, I think.

**Comment by robredpath** [comment]
@odscjames #711 may be related

**Comment by mariongalley** [comment]
Sounds like we want to always include:
- the first x pages
- the last page
- dots to indicate truncation in the list of page numbers if they aren't all displayed based on the above rules
- PLUS y additional pages either side of the current page (including the current page the user is on) if they aren't already being displayed based on the above rules

Looks like y = 5 in the above screenshot, and I'd imagine x is a similar number?

**Comment by odscjames** [comment]
> if you search for "donkeys" then you get this: even though there are two pages of results.

Yes, I've picked up on that and think I have a fix for that already. 

Ah, ok, I just got confused if "correct" meant something else then. Think it was the "Also" in the first comment that set me looking for something unrelated. And I see how it's happened - the title used to be "Pagination shouldn't show if there's only one page of results" - is that still a requirement? 

Sounds like we have several different things about pagination here - do we want to look at the pagination system in general here? (I've actually set up unit tests for this and it feels like a good opportunity to tackle this all in one go, including #711)

Currently the rules are actually:

* If current page not 1 and more than 5 pages , show a "First" link
*  If current page not 1 and more than 1 page, show a "Prev" link
* If needed, show an elipsis
* Show current page as explicit number, and up to 2 other pages as explicit numbers either side of it
* If needed, show an elipsis
* If page not last page, show "next" link
* If page not last page and more than 5 pages, show "Last" link

So:
* We don't always show "the first x pages" and "the last page" as a number, if that's what you mean - you can see they aren't show in the screenshot in my last comment
* Currently there is no indicator of how many pages in total there are.

**Comment by mariongalley** [comment]
Ah thanks James for providing the current rules!

**Re: current rules**
- I'm happy with the current logic for first/last/previous/next i.e.
  - If current page not 1 and more than 5 pages , show a "First" link
  - If current page not 1 and more than 1 page, show a "Prev" link
  - If page not last page, show "next" link
  - If page not last page and more than 5 pages, show "Last" link
- I'm happy with the current logic for truncating the list of page numbers i.e. 
  - If needed, show an elipsis before current page (and its adjacent pages)
  - Show current page as explicit number, and up to 2 other pages as explicit numbers either side of it
  - If needed, show an elipsis after current page (and its adjacent pages)

**Is the only change required to avoid confusion** (minus the URL syntax issue):
- EITHER always show the last page as a page number (might be useful so the user knows the total number of pages, I think this may be my preference)
- OR only show the last page as a page number if the number is low (per Rob's first comment)
- OR something else (based on your comment mentioning you may have a fix for that already)?

**Re: Pagination shouldn't show if there's only one page of results"**
- Not sure if this is a requirement as it predates me. I don't have a strong view on it personally.

**Comment by robredpath** [comment]
> Re: Pagination shouldn't show if there's only one page of results

Personally, I quite like it if a paged interface shows me something to indicate that it is a paged interface, but that there is only one page of results, because it reassures me that i'm not missing anything. 

But I also don't think anyone cares that much, so if it's easier to make it disappear, then doing that is fine!

**Comment by robredpath** [comment]
@odscjames can you share what your fix is for the 2-page issue? To avoid scope creep, if that fix is good, then we can just leave it there instead of reworking pagination too much. But, depending on what the fix is, then a wider look at pagination right now.

**Comment by odscjames** [comment]
> Pagination shouldn't show if there's only one page of results

Personally I also disagree. Having the indicator that there is only 1 set of pages is good. Tho, I would point out it currently looks like this, and maybe this would confuse some people? 

![page1](https://user-images.githubusercontent.com/37832009/120638751-6ed49300-c468-11eb-9c9a-7385bc5cce7f.png)

> To avoid scope creep, if that fix is good

Fair point - I think I can separate it out - I'll have a look.

**Comment by odscjames** [comment]
> can you share what your fix is for the 2-page issue? To avoid scope creep, if that fix is good

That is now merged in

**Comment by mariongalley** [comment]
That's great that the fix is merged in, could you let me know what the fix was? Just want to understand what's been done to address the issue where there are only 2 pages of results and whether it affects the pagination logic for different numbers of pages, so we can decide whether we need/want to make any additional updates at a later date (as Rob said, to avoid scope creep during this round of changes).

**Comment by odscjames** [comment]
> That's great that the fix is merged in, could you let me know what the fix was?

It was an off-by-one error when working out whether to show the 2 next page numbers or not. 

> whether it affects the pagination logic for different numbers of pages

It will affect other numbers of pages. However at the same time I've added 9 new automatic tests to test pagination, which helps us 

* be sure that this fix is correct 
* check any future code changes do not introduce bugs in this area.
* be very clear about and test any changes we make to the rules we use for displaying pagination in the future.

On this issue, the next thing to look at is:

> should use the new URL syntax

**Comment by michaelwood** [comment]
Close pagination page number error. 

Open: https://github.com/ThreeSixtyGiving/grantnav/issues/729
