### ISSUE TITLE
Add earliest / latest to award year

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#638]
Including exact dates so that people can choose by FY

**Comment by BibianaC** [comment]
@robredpath in the filters?

**Comment by robredpath** [comment]
@BibianaC there's three things we could do here. 

First would be to keep the existing granularity (calendar year) but allow people to choose a start and end year, rather than having to select every intermediate year in the range that they're interested in. That might be drop-downs, or a year picker. 

Second would be to allow people to specify down to a lower level of granularity - such as month, or even day. That would be more powerful, but also potentially awkward if you're just trying to get a broad idea of the data. Right now, you can refine to a 24-month period with two clicks, which is valuable if you're trying to refine what you're seeing with a more exploratory mindset. 

The third option would be to try and design something that meets some more specific needs. I *suspect* (with limited data) that the most common things to look for are calendar, financial and academic years, and so we could probably design an interface which made those quite easy to choose. 

@mariongalley do you have a sense of which of these are worth exploring? My instinct would be to add year-pickers for the start and end years, and *maybe* make it a month picker - but then to stop and see if we get any feedback.

**Comment by mariongalley** [comment]
@robredpath I'd be keen to hear @drkane's view on this too as my recollection is that we didn't reach a complete consensus on it during our call re: filters. However I'm inclined to agree with you and start with allowing a date range that's analogous to the smallest/largest amounts picker. Providing a month picker would get us pretty far I think in terms of allowing people to manually select calendar vs financial vs academic years so I'd opt for that.

**Comment by robredpath** [comment]
See also #215

**Comment by Lathrisk** [comment]
The date picker has been added.
