### ISSUE TITLE
Add search box to funding org filter

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#639]
We've removed the drop-down library we were using, so this disappeared. 

We can live without it for a while, because conveniently, the top funders are the ones that people need to remove

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by robredpath** [comment]
Making this about funding org only; #688 addresses recipients

**Comment by robredpath** [comment]
This is done
