### ISSUE TITLE
Move divider on results card to the right

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#641]
to make better use of the space

**Comment by odscjames** [comment]
How about 70%? (Note this is with the description truncating feature of #618 & #640 too, which is still a WIP) 

![70-percent](https://user-images.githubusercontent.com/37832009/120311246-2f267380-c2cf-11eb-9953-123e285b6c42.png)

**Comment by robredpath** [comment]
@odscjames 70% looks good - can you just double check that it still looks ok on smaller screens?

**Comment by odscjames** [comment]
Huh - so I had just read the CSS before and thought it would be fine (it has a breakpoint in) but now I actually test small screens I find a issue. However this is an issue that exists at both 50% and 70% so I've spun off #717 to deal with it separately.
