### ISSUE TITLE
Issues with help site

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#652]
There's some parts of the help site that need fixing (can split into separate issues if needed):

- logo says "360 Standard" - should be the GrantNav logo (this one's a showstopper)
- needs a prominent "Back to GrantNav" link on every page.
- need to change the top right nav items to the same as GrantNav
- incomplete content here: https://help.grantnav.threesixtygiving.org/en/latest/export.html#
- help site homepage has placeholder text: https://help.grantnav.threesixtygiving.org/en/latest/#

**Comment by robredpath** [comment]
@drkane I've opened #661 which hopefully addresses each of these. They're all in individual commits, so should be relatively easy to swap around / change on a point-by-point basis if needs be. 

I've also opened #662 because I think we've slightly broken CSV export
