### ISSUE TITLE
Geographic filter box "closes" after selecting a value

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#657]
**Describe the bug**

When I select a geographic filter, the results refresh accordingly, but the facet selection box then "closes".  If I want to select another geographic facet, I have to reopen said box - rinse and repeat.  

This makes for a frustrating experience, as selecting facets should be quick and easy.  Understood that the Geographic facet box may be "closed" by default, but it should then remain open once a facet has been applied.

**To Reproduce**

Make a search
Unlock the Geographic facet box
Make a selection
Check the Geographic facet box (back to closed)

**Expected behavior**

I would expect the Geographic box to remain open, after one value has been selected

**Screenshots**

![Screenshot from 2021-03-30 11-22-19](https://user-images.githubusercontent.com/1209944/112975371-736c8a80-914b-11eb-8eec-0f10d0f1dda7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome

**Additional context**

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by robredpath** [comment]
We think this is a bug on this specific filter, which we can fix

**Comment by Lathrisk** [comment]
It was also suggested that we leave the geography group open all of the time which would resolve this issue.
