### ISSUE TITLE
CSV download doesn't contain additional fields

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#662]
**Describe the bug**
When you download a CSV of the search results, the additional fields (eg Recipient Region) aren't populated any more

**To Reproduce**
* Filter a search using a geo filter (eg Wales)
* Filter down a bit further to get a usable-sized CSV file (eg £0-£500)
* Click the CSV button

**Expected behavior**
Recipient Region (+ other geo fields) would be populated

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Presumably this is because the relevant data is now in the additional_data object and we haven't updated the CSV generation stuff to use that

**Comment by robredpath** [comment]
@michaelwood @drkane ^^

**Comment by michaelwood** [comment]
Note for dev https://github.com/ThreeSixtyGiving/grantnav/blob/master/grantnav/csv_layout.py#L75 fields need to be prefixed with additional_data .
