### ISSUE TITLE
Classifications field not included in search results

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#664]
**Describe the bug**
Some funders have used the classifications field to indicate that a grant is related to covid-19. Particularly the Scottish Government. However, a search for "Covid-19" does not include those grants.

**To Reproduce**
1. [Show all grants from Scottish Government](http://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&fundingOrganizationTSGType=Central+Government&fundingOrganizationMore=true&recipientOrganizationMore=true&recipientRegionNameMore=true&recipientDistrictNameMore=true&fundingOrganizationTSGTypeMore=true&currencyMore=true&awardYearMore=true&amountAwardedFixedMore=true&fundingOrganization=false&fundingOrganization=GB-GOR-DA1020)
2. Check that over 5,000 grants appear. Opening an individual grant shows "Coronavirus (COVID-19)" in the `Classifications: Title` field.
3. [Search within these grants for Covid-19](http://grantnav.threesixtygiving.org/search?query=%22COVID-19%22&default_field=%2A&sort=_score+desc&fundingOrganization=GB-GOR-DA1020&fundingOrganizationTSGType=Central+Government&fundingOrganizationMore=true&recipientOrganizationMore=true&recipientRegionNameMore=true&recipientDistrictNameMore=true&fundingOrganizationTSGTypeMore=true&currencyMore=true&awardYearMore=true&amountAwardedFixedMore=true) - only 3 results are returned. 

**Expected behavior**
I would expect the classifications fields to be included in the search fields

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Classifications field not included in search results](https://trello.com/c/vDTrwWMN/164-classifications-field-not-included-in-search-results)

**Comment by drkane** [comment]
This has come up for a different field as there is some information in `fundingOrganization/0/description` that needs to be searched.

It looks like this is probably because these fields are not in the [elasticsearch index](https://github.com/ThreeSixtyGiving/grantnav/blob/master/dataload/import_to_elasticsearch.py#L88-L209)

We can have a look through and see which fields should be added to the index by default. Our starters would be:

- `fundingOrganization -> description`
- `grantProgramme -> description`
- `fundingType -> title`
- `classifications -> title`
