### ISSUE TITLE
Docs site: additional text under the table 

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#665]
via drkane :
>There's an issue with some additional text under the table on this page >https://help.grantnav.threesixtygiving.org/en/latest/refining_results.html# - but it looks like it mgiht be tricky to fix.

**Comment by BibianaC** [comment]
@michaelwood @drkane do you mean where it says `header rows ...`? I guess the text shouldn't appear.

**Comment by drkane** [comment]
> @michaelwood @drkane do you mean where it says header rows ...? I guess the text shouldn't appear.

That's right - I think it's some formatting information from somewhere

**Comment by stevieflow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Working down post new design GrantNav issues](https://trello.com/c/Yz3uiR88/147-working-down-post-new-design-grantnav-issues)
