### ISSUE TITLE
broken link / no content in help for Zero value grants

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#668]
**Describe the bug**
The ? tool tip link doesn't lead to anything.
https://grantnav.threesixtygiving.org/help#zero_value_grants
There doesn't seem to be copy carried over the new help pages (term zero didn't show results)

**To Reproduce**
1. go here: https://grantnav.threesixtygiving.org/grant/360G-cabinetoffice-GA-042797

**Expected behavior**
The link should go to help/guidance about zero value grants. Or the tool tip should be removed to avoid confusion.

**Screenshots**
![image](https://user-images.githubusercontent.com/20462640/113316636-7cee2200-9306-11eb-9085-d702145d230a.png)

**Additional context**
The zero value grants tool tip isn't appearing in the search results pages. Is this intentional?

![image](https://user-images.githubusercontent.com/20462640/113317119-f5ed7980-9306-11eb-99a1-92821d0b09f0.png)

**Comment by robredpath** [comment]
The content is now at https://help.grantnav.threesixtygiving.org/en/latest/search_results.html?highlight=%C2%A30#some-grantmakers-publish-grants-with-0-or-negative-values
