### ISSUE TITLE
Search results don't show grant date anymore

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#673]
**Describe the bug**
Search results are missing date information.

**To Reproduce**
see this link [https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&fundingOrganizationMore=true&recipientOrganizationMore=true&recipientRegionNameMore=true&recipientDistrictNameMore=true&fundingOrganizationTSGTypeMore=true&currencyMore=true&awardYearMore=true&amountAwardedFixedMore=true](url)

**Expected behavior**
The results used to show the date to the right of the grant title.

**Screenshots**
![image](https://user-images.githubusercontent.com/20462640/114361459-0eaf2800-9b6e-11eb-85f5-6a53702a0781.png)

**Additional context**
Knowing the date of the grant results is important, for assessing whether the results are relevant to the user.

**Comment by michaelwood** [comment]
I have a fix that will allow the date to appear as so:
![Untitled](https://user-images.githubusercontent.com/493697/114878675-652f9700-9df8-11eb-8901-0c2a14071d45.png)

The date in the template data is in a string format of Y-m-d at the point we have the results, we could write a little parser to display it in other formats as per the design prototype e.g. "22 Aug 2017" , there obviously would be some computation on every grant displayed, which may be a tiny bit slower to show results,(or we could do it client side in JS..  ), let me know if we do want to change how the date is displayed.

**Comment by robredpath** [comment]
> there obviously would be some computation on every grant displayed, which may be a tiny bit slower to show results,(or we could do it client side in JS.. ),

Could we do it in the datastore, as part of preparing the package?

**Comment by KDuerden** [comment]
Definitely think that "22 Aug 2017" format would be better than the y-m-d.

**Comment by michaelwood** [comment]
> > there obviously would be some computation on every grant displayed, which may be a tiny bit slower to show results,(or we could do it client side in JS.. ),
> 
> Could we do it in the datastore, as part of preparing the package?

Ideally we need a python datetime object so, the way we interact with elasticsearch means we just have the string representation of the date in the json document back from elastic. We could curate a new field in the elastic document with specifically that date format, creating it on import as we do with the Y-m-d version. We would then have awardDate in there 3 times though, which would have to be excluded later on... which is fine, just getting a bit more involved.

**Comment by robredpath** [comment]
In general, I think it's good for us to do as much processing as possible in the datastore - all those tiny operations add up, after all. There's some complexity trade-off, of course, but I don't think that it's introducing any new concepts or operations, right? It's adding a field where we already add fields, and it's excluding a field where we already exclude fields. 

In this particular case, I'm not too fussed - as long as it happens, I guess!

**Comment by michaelwood** [comment]
Fixed and deployed, turned out this was a problem already solved with a template filter that just needed re-implementing in the new design templates.
