### ISSUE TITLE
Footer link to Github does not link to the repo

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#679]
This isn't a "bug", but neither is it a feature request

The footer link for GitHub is to https://github.com/threesixtygiving/.  This then requires me to navigate to where I think grantnav code/issues might be

I can understand if the github logo/link is being used for wider context, but this doesnt seem right.  If you're linking me from grantnav to GitHub, I'd expect to get to https://github.com/ThreeSixtyGiving/grantnav/

Or - even better - I'd probably expect some text to explain that the code is on GrantNav, and then a link to https://github.com/ThreeSixtyGiving/grantnav/issues/ for me to log any feedback...

**Comment by drkane** [comment]
Agreed, this is definitely worth thinking about - and there may be a better place to put the links for raising issues. 

We also used to have a link to the exact build being currently used - it might be useful to put this back into the footer.

**Comment by mariongalley** [comment]
Agree it makes more sense to link specifically to the GrantNav Github rather than general 360Giving Github in the footer of GrantNav.

Re: linking the exact build being currently used, beginner question here @drkane but is that something that would need regularly updating, or would it dynamically update?

We also have copy saying to email the grantnav@ inbox with questions or feedback, which could plausibly cover the same kinds of issues one might raise in Github. We've discussed elsewhere having clearer language about when to email which inbox (e.g. support@ or info@ rather than grantnav@), so we could update the footer copy to indicate what kinds of issues we expect to see raised in Github vs via email as well?

**Comment by stevieflow** [comment]
Thanks @drkane - hi @mariongalley !

OK - so this looks to be:

- link to the correct github repo - agreed
- reinstate the build number - agreed.  @mariongalley in the previous GrantNav this was autogenerated
- contact workflow for issues and feedback:  I'd advocate for both a link to the *existing* issues and detail on how to contact 360 directly.  The advantage of having access to the open issues is that people can see what has already been logged and suggested - and so may find their issue is the same/similar.

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Working down post new design GrantNav issues](https://trello.com/c/Yz3uiR88/147-working-down-post-new-design-grantnav-issues)

**Comment by BibianaC** [comment]
@stevieflow What does exactly need to be done with `contact workflow for issues and feedback`.

**Comment by stevieflow** [comment]
Thanks @BibianaC 

> What does exactly need to be done with contact workflow for issues and feedback

@mariongalley @drkane this doesn't seem to be something we can implement, without some content / guidance from 360 (which in turn might rest on a few 360-wide things being in place).  To help with issue management and specificity, shall we raise a new issue on this, so that we can close this one ? Thanks!

**Comment by mariongalley** [comment]
I'm happy for you to close this one and raise the remaining point separately if we don't think we can easily reach a solution on it.

It might be quite a simple fix though:
* The suggestion you made was "I'd advocate for both a link to the existing issues and detail on how to contact 360 directly."
* Currently the footer says: "If you have questions or feedback, please email grantnav@threesixtygiving.org"
* Do you think we need to do more than just change that wording to: "If you have questions or feedback, please email grantnav@threesixtygiving.org or raise an issue in Github. The existing list of issues can be found [here]." (or similar)

**Comment by stevieflow** [comment]
Hi @mariongalley 

Great - yes, I think

>  "If you have questions or feedback, please email grantnav@threesixtygiving.org or raise an issue in Github. The existing list of issues can be found [here]." 

... would address the whole issue!

@BibianaC to add that in the footer?

**Comment by odscjames** [comment]
I think this can be closed now? The footer has a link to issues, and the issue about the build number was spun out to #683?
