### ISSUE TITLE
Summary pages - box is very "small" (on 2560 x 1440)

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#680]
If I go to a page such as http://grantnav.threesixtygiving.org/recipient/GB-CHC-220949 , here's what I see

![360Giving-GrantNav (2)](https://user-images.githubusercontent.com/1209944/115586643-b80bc180-a2c4-11eb-966c-0ea64197889c.png)

Granted (!) my resolution is 2560 x 1440.  But - is there anything in place for GrantNav to understand my resolution, and alter the display gracefully?  It seems like a real waste of screenspace , currently

**Comment by stevieflow** [comment]
Note - the info box stats on this page are also rather squished up  -- in the first column of data

**Comment by drkane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav summary pages](https://trello.com/c/VMO0SMgO/155-grantnav-summary-pages)

**Comment by mariongalley** [comment]
Solved by new org pages
