### ISSUE TITLE
Reinstate the build number / link to the footer 

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#683]
Via https://github.com/ThreeSixtyGiving/grantnav/issues/679

> We also used to have a link to the exact build being currently used - it might be useful to put this back into the footer.

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Working down post new design GrantNav issues](https://trello.com/c/Yz3uiR88/147-working-down-post-new-design-grantnav-issues)

**Comment by odscjames** [comment]
Can this be closed now?

**Comment by BibianaC** [comment]
This is now deployed.
