### ISSUE TITLE
GrantNav export recipients data page as CSV  giving error

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#685]
On https://grantnav.threesixtygiving.org/recipients there is a link to download all the data as a CSV https://grantnav.threesixtygiving.org/funder_recipients_datatables.csv

Due to the size of the data now this query to ElasticSearch exceeds the default `search.max_buckets` value and errors out. As a short term fix we can update this limit to `search.max_buckets: 200000` in the elasticsearch config. For these larger tables we may want to look at how to do offline processing to create the files and serve them statically.

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav export recipients data page as CSV giving error](https://trello.com/c/h8g88gRq/160-grantnav-export-recipients-data-page-as-csv-giving-error)

**Comment by odscjames** [comment]
I've done 2 commits on branches (see above) - I can work with someone next week to get these live carefully.
