### ISSUE TITLE
Does anything link to /developers ?

### ISSUE THREAD

**Issue by odscjames** [ThreeSixtyGiving/grantnav#698]
We have a static page /developers on the site.

But I can't find anything that links to it.

"Developers" in the footer links to https://help.grantnav.threesixtygiving.org/en/latest/developers.html#

Should this static page exist? Should the URL redirect people to the help site page instead?

**Comment by robredpath** [comment]
@odscjames Good spot - that page has now been deprecated by the help site. I've realised that the help site doesn't include all of the info, though, so I've opened #701 for us to address that in the future

**Comment by robredpath** [comment]
@odscjames you can remove this page now
