### ISSUE TITLE
Help site doesn't include full dataset links

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#701]
The previous /developers page included links to download the whole dataset. The new equivalent - https://help.grantnav.threesixtygiving.org/en/latest/developers.html# - doesn't. 

The previous text was:

> Programmatic access to data
> 
> In order to make it easier to prototype and develop applications that use 360Giving data, we offer access to the entire GrantNav data set as CSV or JSON:
> 
> http://grantnav.threesixtygiving.org/api/grants.json
> 
> http://grantnav.threesixtygiving.org/api/grants.csv
> 
> The whole data set is several hundred MB and growing, so we recommend that you store the data locally for your own application to work from. The data is updated at most once a day (except in case of an error), and usually once per month. A list of all data sets and the date on which they were last updated can be found at http://grantnav.threesixtygiving.org/datasets/#datasets-used
> 
> The GrantNav data set contains data that has been published by organisations. Not all 360Giving data is included - any that fails validation, or isn't available under a suitably open license (ie, one that permits re-use for any purpose) isn't included. This means that all data in GrantNav is valid against the 360Giving Data Standard, and is available for re-use for any purpose. The data set also contains augmented data that is not present in the original data set - for example, additional location data such as 'ward' and 'region' are added to grant records in order to enable some of GrantNav's filtering options to work. See the Data used in GrantNav page for a full reference of all the data used in creating GrantNav, and the license under which the GrantNav data can be used.

**Comment by odscjames** [comment]
Is the following meant to replace that section?

> If you'd like to explore 360Giving data in more detail and would benefit from access to a database with more features than GrantNav offers, please get in touch with us to talk about gaining access to the [360Giving Datastore](https://www.threesixtygiving.org/data/360giving-datastore/).

**Comment by mariongalley** [comment]
Is the proposed solution then to get rid of the copy that says you can download the full dataset and replace it with the copy that says you can request access to the datastore? Is there anything else that needs changing e.g. links?

**Comment by odscjames** [comment]
https://help.grantnav.threesixtygiving.org/en/latest/developers.html# already has the text about requesting access.

This issue is about putting back some text about "Programmatic access to data".

But I suspect we don't actually want that?

If not, then this issue can be closed with no work needed and we can progress #698

**Comment by robredpath** [comment]
We didn't intend to hide the fact that you can download the whole GrantNav dataset via a couple of special endpoints - that was an accidental deletion. 

@mariongalley @odscjames https://github.com/ThreeSixtyGiving/grantnav/pull/713 is what I think we should do - it was easier to make a PR than try to describe it!

**Comment by robredpath** [comment]
Closed as PR merged
