### ISSUE TITLE
On results card on medium screens, divider line is not aligned any more

### ISSUE THREAD

**Issue by odscjames** [ThreeSixtyGiving/grantnav#717]
![not-aligned](https://user-images.githubusercontent.com/37832009/120634795-937a3c00-c463-11eb-9c2d-fa51742fa7ac.png)

The CSS rule of of a % is still there, but I guess something in the text is overriding it.

On smaller screens (mobile) it changes to a vertical layout.

We could:
* Try and fix this
* Change the breakpoint so it goes over to vertical layout on medium screens, which may be better anyway?

**Comment by robredpath** [comment]
> Change the breakpoint so it goes over to vertical layout on medium screens, which may be better anyway?

Yeah, I've just looked at it on my iPad and it feels a bit clunky; I'd like to see what it would look like in a vertical layout on that size of screen. With GrantNav we don't really try to support phone-sized screens, but tablet-sized screens we do.

**Comment by michaelwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Search result cards divider positioning moves on small screens](https://trello.com/c/rJRbTmZX/216-search-result-cards-divider-positioning-moves-on-small-screens)

**Comment by mariongalley** [comment]
Note to self, this relates to #641

**Comment by odscjames** [comment]
Have done a PR that fixes the current behaviour so the size now stays constant - adding 30% explicitly to right hand side did it. We can get this fix in first.

Regarding 

> Yeah, I've just looked at it on my iPad and it feels a bit clunky; I'd like to see what it would look like in a vertical layout on that size of screen. With GrantNav we don't really try to support phone-sized screens, but tablet-sized screens we do.

Changing the breakpoint from $medium to $large is an very easy change & may be preferred - once the basic fix is in I can put a demo thing up somewhere for that.

**Comment by odscjames** [comment]
The fix is merged in and will be deployed soon.

We can change the breakpoint to regular or large - see screenshots below (bar at top tells you what size they are) and comment with your preference! (including leave as is)

# Regular breakpoint

![regular-break3](https://user-images.githubusercontent.com/37832009/142244649-5c9af51a-e3a4-421a-bc36-ad9cf6168237.png)

![regular-break3a](https://user-images.githubusercontent.com/37832009/142244672-3bee4497-1620-409f-b5c0-329201515196.png)

![regular-break4](https://user-images.githubusercontent.com/37832009/142244703-f5066485-1f40-43bd-b977-90570a614a87.png)

![regular-break5](https://user-images.githubusercontent.com/37832009/142244732-b34a1b61-7abb-4bcd-a00a-e3ef82a4e0bc.png)

![regular-break1](https://user-images.githubusercontent.com/37832009/142244754-0d8d6038-8ed2-4cab-b0f4-b5cf48433162.png)

![regular-break2](https://user-images.githubusercontent.com/37832009/142244772-d5d792fd-ea2c-48ed-9fef-20599e032fd6.png)

![regular-break6](https://user-images.githubusercontent.com/37832009/142244790-bb0ea1d1-7c5a-4646-9990-c3397fcc902a.png)

![regular-break7](https://user-images.githubusercontent.com/37832009/142244799-c27c2e26-9b92-4423-859d-d25795ba3222.png)

# Large breakpoint

![large-break3](https://user-images.githubusercontent.com/37832009/142244868-8f11ac5c-3987-4476-9353-98d7b85e5649.png)

![large-break3a](https://user-images.githubusercontent.com/37832009/142244887-23bc141b-8405-4c62-b9dc-8849032d6609.png)

![large-break4](https://user-images.githubusercontent.com/37832009/142244899-885e54c4-13ad-4581-b5e4-d0662f7fd835.png)

![large-break5](https://user-images.githubusercontent.com/37832009/142244910-99615211-a8b9-4f08-b51d-a7fa2ab22cba.png)

![large-break1](https://user-images.githubusercontent.com/37832009/142244937-cea882fa-4760-4106-aa58-ed1fb4f1bab4.png)

![large-break2](https://user-images.githubusercontent.com/37832009/142244948-a37e34e8-291e-4e4b-a6f6-d5e845e1fbc2.png)

![large-break6](https://user-images.githubusercontent.com/37832009/142244963-b8d92832-e074-4104-ac90-15d31a0c1bce.png)

![large-break7](https://user-images.githubusercontent.com/37832009/142244972-696d44c1-c7b8-473a-88c1-90d2303c44b6.png)

**Comment by odscjames** [comment]
Closing in favour of #803 so the question is clear
