### ISSUE TITLE
Funder name doesn't appear in "360Giving datasets used" list

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#726]
**Describe the bug**
Instead of displaying the funder name, in the table listing all the 360Giving publishers, it says {{ funder_name }}
If you hover over this, it does hyperlink to funder page, so it seems like it is just the name that is missing.

**To Reproduce**
1. Go to https://grantnav.threesixtygiving.org/datasets/

**Expected behavior**
The funder name, or names should appear in a list, as per the table in the publisher specific pages:

https://grantnav.threesixtygiving.org/publisher/360G-cabinetoffice
or 
https://grantnav.threesixtygiving.org/publisher/360G-coopgroup

**Screenshots**
![image](https://user-images.githubusercontent.com/20462640/121311898-c22d6200-c8fc-11eb-867c-4b46d2ed104c.png)

**Desktop (please complete the following information):**
 - Browser chrome or firefox gives the same result.

**Comment by BibianaC** [comment]
@KDuerden this one is fixed. We will deploy the fix this week, normally tomorrow.

**Comment by BibianaC** [comment]
@KDuerden the fix is now deployed.
