### ISSUE TITLE
Clicking on the result card details links to apply filter

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#749]
As a user my initial assumption was that clicking a result card detail item was going to apply a filter to the current results. 
![Screenshot 2021-06-21 at 12-48-54 360Giving GrantNav](https://user-images.githubusercontent.com/493697/122757211-497cbd00-d28f-11eb-8e8b-de70f19e5f4c.png)

**Comment by mariongalley** [comment]
Do you mean you expected that clicking on the Region for e.g. would take you to a Search Results page with your current search + the addition of the region you clicked on as a filter? And instead it takes you to a region page for that region.

**Comment by robredpath** [comment]
This was highlighted in the very early user research as being an inconsistency - the same words (such as regions, or funders) appear on both the left and right-hand sides of the page and do very different things. 

I think we could address this through design - such as moving those links to a full-width box at the bottom of the card, with some text (such as "see all grants in ..."?")

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clicking on the result card details links to apply filte](https://trello.com/c/avUaP5hl/188-clicking-on-the-result-card-details-links-to-apply-filte)

**Comment by mariongalley** [comment]
#203
