### ISSUE TITLE
Search Summary: Smallest Grant > 0

### ISSUE THREAD

**Issue by Lathrisk** [ThreeSixtyGiving/grantnav#760]
In #597 the option to display the grant which is smallest but also > 0 was requested. This will likely require an additional query to elasticsearch. This presents additional complexity and at present the performance implications are unknown.

We can look into this further but it is unlikely this is achievable for the current deadline (28th June 2021).

**Comment by mariongalley** [comment]
Just a bit of background: the rationale here is that grants worth £0 or < £0 aren't really real grants, and so it sort of undermines the helpfulness of the highlighted "smallest grant" and might confuse users. We can discuss it tomorrow at our catch up and see what the team thinks about it on Monday. Might be that we have to come up with a short-term workaround (worst case scenario is we hide smallest grant, if the risk of confusion is estimated to be very high).

**Comment by Lathrisk** [comment]
Thanks Marion. I've noted this in Pull Request #745, and will postpone merging this until we have decided what direction to take, hopefully this lunchtime.

**Comment by mariongalley** [comment]
Options are:
- Hide the smallest grant if it's <1 (we pick this one)
- Leave it as is showing a £0 or negative amount for smallest grant

Also - is it a good idea in the long term to try and only show smallest grants > £0?
It will be very complicated. It's possible but too big a performance hit.
We will not do this - can close the issue once we've done the short term fix.

**Comment by Lathrisk** [comment]
#745 now includes a conditional render for the smallest grant so this field is only displayed if the grant value is > 0

**Comment by Lathrisk** [comment]
This currently looks like this, but can be changed if having it as a standalone label is preferable.

![pagination-marker](https://user-images.githubusercontent.com/517804/123279201-8a7b0880-d4ff-11eb-8b60-47654b30f3ef.png)

**Comment by Lathrisk** [comment]
> We will not do this - can close the issue once we've done the short term fix.
