### ISSUE TITLE
Show where you are in in the search results

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/grantnav#761]
**Is your feature request related to a problem? Please describe.**
Showing clearly that you're on page X of search results

**Describe the solution you'd like**
Something near the "Search results" header that says "Page X of Y"

**Describe alternatives you've considered**
There is a pagination bar at the bottom but it's not clear when you first see the results

**Comment by Lathrisk** [comment]
Add to #745

**Comment by Lathrisk** [comment]
This currently looks like this, but can be changed if having it as a standalone label is preferable.

![pagination-marker](https://user-images.githubusercontent.com/517804/123279201-8a7b0880-d4ff-11eb-8b60-47654b30f3ef.png)

**Comment by mariongalley** [comment]
Nice, I think it looks good there personally
