### ISSUE TITLE
Search summary: Date awarded graph improvements

### ISSUE THREAD

**Issue by Lathrisk** [ThreeSixtyGiving/grantnav#771]
Consider ways of visualising the data before a given date. 
~~Suggested 20 years is visualised~~, with an additional bar for all grants before that date.

**Comment by Lathrisk** [comment]
The recent pull request updates the graphs so that the past 20 years are shown based on today's date.
There is not currently a bar to show grants from before this date - the graph is currently laid out automatically based on the numerical order of years so the bar position and label will need to be manually entered.

**Comment by Lathrisk** [comment]
@mariongalley - I have had a quick look at the years awarded graph. I'm trying to work out the best format for showing the data before our 20 year cut off. This is what I have so far. The tricky part is working out the best copy for the bar. I've currently opted for `1996+` where the range is shown in more detail in the tooltip. If I add both years to the x-axis labels then they take up too much space really.

Any suggestions?

![early_years](https://user-images.githubusercontent.com/517804/125302340-c1388780-e323-11eb-84f6-bdd551a9a504.png)

![early_years_tooltip](https://user-images.githubusercontent.com/517804/125302350-c3024b00-e323-11eb-8081-6a8cd708bb78.png)

**Comment by Lathrisk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Summary Stats updates: Years](https://trello.com/c/J76566pW/186-summary-stats-updates-years)

**Comment by mariongalley** [comment]
> I'm trying to work out the best format for showing the data before our 20 year cut off. This is what I have so far.

That's absolutely perfect, exactly what I had in mind!

> The tricky part is working out the best copy for the bar. I've currently opted for 1996+ where the range is shown in more detail in the tooltip. If I add both years to the x-axis labels then they take up too much space really.

Agree, I don't think it's necessary to add both years. I would have probably put "Pre-2003" or similar rather than "1996+" because then it's more obvious that it's all the data before the years already displayed, even if it's in some way less informative as we already know 2003 is the earliest year being displayed. Or we could say "Older data", for consistency with the Dashboard:
![image](https://user-images.githubusercontent.com/82958988/125313150-debe1f00-e32c-11eb-9b65-cc30c98eb977.png)

**Comment by Lathrisk** [comment]
@mariongalley I've updated with Older data, it is a noticably longer string, but if I adjust the size of the charts it works ok:

![adjusted_margins](https://user-images.githubusercontent.com/517804/125453973-e5bc8975-2ad0-498e-8b21-56c00041e9a6.png)

For reference, here is `pre-x`:

![Pre-year](https://user-images.githubusercontent.com/517804/125454074-52458e2e-0a03-4a2e-8be2-2831dc85bd1f.png)

**Comment by mariongalley** [comment]
@drkane @KDuerden Do you think it's more important to be consistent with the Dashboard to to avoid reducing the space available for the gralph?

**Comment by KDuerden** [comment]
As the dashboard is still in development I go with what makes most sense in this design/space available.
We could then always make dashboard mirror that.

**Comment by Lathrisk** [comment]
@mariongalley @KDuerden 

I've updated the graph to just show 'Older'. This leaves some interpretation as to whether we are talking about `Grants` or `Data`, but I think it should be clear from the context and the graph is meant to be simple and indicative so hopefully this present enough information to get a lay of the land.

Please let me know if you'd feel something else would be more suitable.

![search-summary-years](https://user-images.githubusercontent.com/517804/126133995-38f97899-48be-4987-8b6b-bc32b3e6da1e.png)
