### ISSUE TITLE
Hint displayed for a search with a hyphen isn't that helpful

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#792]
If you search for `covid-19`, you get lots of results that match `19` because we split on the hyphen. 

To quickly improve the user experience, we display the `If you're looking for a specific phrase, put quotes around it to refine your search. e.g. "youth clubs"` hint to users, now. 

I'm not sure that it's obvious that the hint is relevant to the search, so I'd suggest that we change it to more customised text. My suggested wording is:

`Search terms that contain a hyphen should have quotes around them so that they are treated as a single term. For example, "covid-19". `

An alternative could be that we don't split on hyphens, but that probably is a bigger job because we'd have to mess around with elastic's settings.

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Covid-19 Hint displayed for a search with a hyphen isn't that helpful](https://trello.com/c/ffaRvBrt/242-covid-19-hint-displayed-for-a-search-with-a-hyphen-isnt-that-helpful)

**Comment by BibianaC** [comment]
Relates to change done in issue https://github.com/ThreeSixtyGiving/grantnav/issues/663

**Comment by mariongalley** [comment]
Based on rarity of these searches, closing issue
