### ISSUE TITLE
Dockerfile is Python 3.6, not 3.8

### ISSUE THREAD

**Issue by odscjames** [ThreeSixtyGiving/grantnav#800]
https://github.com/ThreeSixtyGiving/grantnav/blob/master/Dockerfile#L1

Currently this will only affect dev environments

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dockerfile is Python 3.6, not 3.8](https://trello.com/c/FWuLE95N/241-dockerfile-is-python-36-not-38)
