### ISSUE TITLE
Results cards divider - which breakpoint should it change at? (For tablet screens)

### ISSUE THREAD

**Issue by odscjames** [ThreeSixtyGiving/grantnav#803]
**Is your feature request related to a problem? Please describe.**

From https://github.com/ThreeSixtyGiving/grantnav/issues/717

> Yeah, I've just looked at it on my iPad and it feels a bit clunky; I'd like to see what it would look like in a vertical layout on that size of screen. With GrantNav we don't really try to support phone-sized screens, but tablet-sized screens we do.

**Describe the solution you'd like**
It is very easy to change breakpoint to one of 2 other options; this will follow the Design System.

See https://github.com/ThreeSixtyGiving/grantnav/issues/717#issuecomment-971767072 for options.

**Describe alternatives you've considered**
None others as other solutions would involve changing the design system (tho that is possible if really wanted)

**Additional context**
See https://github.com/ThreeSixtyGiving/grantnav/issues/717

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Results cards divider - which breakpoint should it change at? (For tablet screens)](https://trello.com/c/sDfHck6m/238-results-cards-divider-which-breakpoint-should-it-change-at-for-tablet-screens)

**Comment by mariongalley** [comment]
I can't reproduce the issue anymore, I think this is fixed now

![image](https://github.com/user-attachments/assets/a5db2226-5b46-4c1c-9653-b2dd4114bc9a)
