### ISSUE TITLE
Make it more obvious that GrantNav understands geography even when the loaded data doesn't help

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#810]
This isn't a bug, but is potentially undesirable behaviour. 

If the data that's loaded into GrantNav doesn't have the right kind of geo data, we don't display the Region or District links on the grant card:

<img width="1183" alt="Screenshot 2022-01-05 at 09 02 36" src="https://user-images.githubusercontent.com/641009/148190220-f9c7dd14-b38e-4337-b9ab-4b3cff851d13.png"> (all the rest of the front page cards are from the same funder) 

This is despite the grant record containing *some* geo data - just not the *right* geo data. The grant is https://grantnav.threesixtygiving.org/grant/360G-SomersetCF-A350096 - we've got `additional_data: locationLookup: rgnnm` but not an `additional_data: recipientRegionName`. 

These links are, IMO, part of how a user intuits that GrantNav understands geography: they're nice and obvious geo terms. There are geo filters on the left, but they're all closed by default, and you have to scroll to get to them: I think I'd find them easy to miss as a new user. 

So, we could:
* Make one of the geo filters open by default, to make it more obvious
* See if we can use the new geo data from the datastore to put more geo info on to the cards where we do actually have it

**Comment by robredpath** [comment]
(and yes, the grant in question does have geo data - https://grantnav.threesixtygiving.org/grant/360G-SomersetCF-A350096 )

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make it more obvious that GrantNav understands geography](https://trello.com/c/ADeoYX7Z/237-make-it-more-obvious-that-grantnav-understands-geography)

**Comment by mariongalley** [comment]
We have moved the filters up and the Region/Country filter is expanded by default, which solves some of this issue. We also now show "Undetermined" when we weren't able to determine the geography, either because no geodata was provided, or because we couldn't interpret the geodata that was provided. I think this resolves this issue.
