### ISSUE TITLE
No results page has a no context "click here" link

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#813]
https://grantnav.threesixtygiving.org/search?query=oijoijoijoijwofjwef&default_field=%2A&sort=_score+desc

"To clear your search, [click here](#)"

This could be something more like

"[Clear your search query](#)"

**Comment by mariongalley** [comment]
This is fixed 
![image](https://github.com/user-attachments/assets/1de9f897-07ee-4718-b9c4-6864601457c9)
