### ISSUE TITLE
Change colours of tables on Org page

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#820]
On the Org page, please can the recipients table in the Funder section be Yellow (rather than current orange) and the Funder table in the Recipients section be Teal (rather than the current Orange)

**Comment by mariongalley** [comment]
Nice-to-have

**Comment by michaelwood** [comment]
@mariongalley  Do we have a teal table available? I see orange/yellow in the design system but can't find a teal one. If not this would also need some design work.

**Comment by mariongalley** [comment]
Ah right, I didn't realise that would be needed. In that case don't worry about it - it's not important!

**Comment by mariongalley** [comment]
I think this would look bad actually - closing issue.
