### ISSUE TITLE
Copy to explain a bit more on the Org page

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#825]
We need some additional copy on the Org page to explain:

- "As Funder"/"As Recipient"
    - These cards would benefit from a brief introductory sentence that says something like "This organisation appears in the 360Giving data as a [funder/recipient]. Here is some additional information about grants they have [funded/received]."
    - The Recipients table could do with a little copy too e.g. "Here is a list of all Recipients this organisation has funded."
    - Same for the Recipients Funders table e.g. "Here is a list of all Funders that have funded this organisation."
- Org IDs/Other names
   - This top section would benefit from some information about this e.g. "This organisation has been referred to using several organisation identifiers in the 360Giving data. This may be because they have both a charity number and company number." and "This organisation has been referred to using several names in the 360Giving data. This may be because their name can be abbreviated or written in various ways, or because it has changed over time, or because one charity number is shared by several bodies receiving distinct grants."
   - It would be great if we could link to some explanation either in the standard docs or the data quality tool about use of Org IDs

**Comment by michaelwood** [comment]
Reference:
e.g. http://grantnav.360dev1.vs.mythic-beasts.com/org/GB-CHC-1010656
grantnav/frontend/templates/org.html

**Comment by mariongalley** [comment]
I have reviewed this and am happy with is. The only issue is it now says "As Recipient**s**" rather than "As Recipient".

Can this be fixed? Then happy to close.

![image](https://user-images.githubusercontent.com/82958988/163168250-e1393623-2ae0-4be9-bd85-0f6289b3bd1e.png)

**Comment by michaelwood** [comment]
Recipients->recipient now done

http://grantnav.360dev1.vs.mythic-beasts.com/org/360G-cabinetoffice-0014J00000K6jRcQAJ
https://github.com/ThreeSixtyGiving/grantnav/commit/21fa92520073e29e996e65972c3add0e20989018
