### ISSUE TITLE
Improve design of the As funder/As recipient cards on the Org page

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#826]
The overview stats are a bit hard to read as there's a value then the label below, and they're in 3 columns with a lot of white space.

Not sure what's the best way to improve the design, it might be easier if they were just in list form i.e.
- [label] : [value]
- [label] : [value]
- [label] : [value]

Or possibly in a table similar to the GrantNav search summary table

**Comment by mariongalley** [comment]
- Styling of the "open in GrantNav" button should be similar to the buttons in Insights and the Data Quality Tool, and look similar to the button on the Funder/Recipient Search pages.

**Comment by michaelwood** [comment]
I've done quite a bit of tidying up of this page as well as moving labels around, justifying all the content, using some more of the existing design paradigms and fixing buttons.
Preview on dev site: http://grantnav.360dev1.vs.mythic-beasts.com/org/GB-CHC-1087053

Hopefully this is the direction to go in in terms of rationalising the design, and the approach I can take with other new pages.

(the before screenshot)
[Screenshot 2022-03-16 at 19-05-59 360Giving GrantNav](https://user-images.githubusercontent.com/493697/158668412-f44a1a2f-59af-420b-b4f8-f7d548341409.png)

**Comment by michaelwood** [comment]
> * Suggest removing Smallest Amount as it is sometimes misleading (£0, negative values) and not all that useful as long as you have the max and average

wrg to this suggestion. We had a discussion previously about negative values and decided it was important to display the data as-is. This also makes it a consistent approach with whatever tool/method the user is viewing the data with.

**Comment by mariongalley** [comment]
Thanks for this - I definitely think it looks better. Could we get rid of the "Smallest Amount" fields for each currency please?

**Comment by michaelwood** [comment]
- Removed smallest amount
- Added Explore grants button to be above tables

**Comment by mariongalley** [comment]
@michaelwood Shall we close this ticket if all the issues within are addressed and raise new tickets for any design feedback from this upcoming round of testing?

**Comment by michaelwood** [comment]
> @michaelwood Shall we close this ticket if all the issues within are addressed and raise new tickets for any design feedback from this upcoming round of testing?

Yep I think so
