### ISSUE TITLE
If an Org is both a funder and recipient, add button to open all their grants to Org page

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#828]
If an Org is both a funder and recipient, add a button to open all their grants either as a funder or as a recipient to their Org page

**Comment by mariongalley** [comment]
Don't think this is particularly viable - currently can't select both an org's grants where they are either the Funder OR the Recipient.

**Comment by robredpath** [comment]
@mariongalley we could construct a query to do this but the user experience wouldn't be particularly nice: this could be something that we write some help for?

**Comment by mariongalley** [comment]
Yeah it's OK - I'm not sure there's a compelling user story for this to be honest
