### ISSUE TITLE
Ability to switch to table view in search incl org search

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#854]
Can do "cards" view with the pretty layout or table view for ease of skimming.

Relates to #818 which removes funder and recipient pages and #853 which makes cards prettier.

**Comment by mariongalley** [comment]
TBC what the fields will be but assume it'll be the same as the cards except for long description which can be not displayed or truncated

**Comment by mariongalley** [comment]
@Lathrisk The tabular view looks good within the widget preview. Would you or @michaelwood be able to deploy it to the general Grants Search page in dev grantnav along with a control that lets you switch between it and the cards?

**Comment by Lathrisk** [comment]
@mariongalley as per email, I'll take a look at the search page table switching today

**Comment by KDuerden** [comment]
Bug identified with table view hyperlinking to old format urls for recipient/funders and current GN (not dev) grant view #870

**Comment by mariongalley** [comment]
Bug identified with table view sorting #872

**Comment by mariongalley** [comment]
Bug identified with table view not being persistent #874

**Comment by mariongalley** [comment]
Bugs identified #918 #906 #901

I think this can be closed nonetheless @Lathrisk @michaelwood

**Comment by mariongalley** [comment]
@KDuerden In this ticket I'd initially said you should be able to switch to table view in the organisation search as well as main search. I don't know how it will be used by others but generally I'm only looking for 1 org at a time (or 1 org + a handful of duplicates) so it doesn't seem as useful in hindsight.

**Comment by KDuerden** [comment]
agreed - I can't see an obvious use case for this.

**Comment by mariongalley** [comment]
Adding bugs to project board and closing issue
