### ISSUE TITLE
Footer links & Policies

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#859]
1. Replace the privacy policy on the GrantNav site with a link to https://www.threesixtygiving.org/privacy/ (we need to get rid of the existing page entirely)
2. Replace the cookie policy on the website with a link to https://www.threesixtygiving.org/cookie-policy/ (we need to get rid of the existing page entirely)
3. Delete everything in the Terms and Conditions between "How we use cookies" and "Links to other websites". Insert a heading before "Links to other websites" called "Problems with the data" and insert the following paragraph: 360Giving and GrantNav are not directly responsible for any of the data on this site. If you see a problem with data on this site this should be reported directly to the relevant organisation. To find out how to contact them, see the "Where is this data from?" section at the bottom of each GrantNav grant page. GrantNav is covered by the 360Giving Take Down policy for requests to remove data that is published to the 360Giving Data Standard: http://www.threesixtygiving.org/take-down-policy/

**Comment by codemacabre** [comment]
@mariongalley Would you like the **Terms** and **Take Down Policy** links on the left (under **Links**) removed, as they're both duplicated in the links further below?
![image](https://user-images.githubusercontent.com/49149591/197759100-ed252400-129b-4381-8da1-b98794cb35a1.png)

**Comment by mariongalley** [comment]
@codemacabre Yes that makes sense thanks, will make the footer a bit less tall too

**Comment by mariongalley** [comment]
Have tested this and all looks good, thanks!
