### ISSUE TITLE
Widgets MVP

### ISSUE THREAD

**Issue by Lathrisk** [ThreeSixtyGiving/grantnav#861]
- It's clear how the world will be different when the work is completed

Grantnav will contain a distinct django app for building and serving widgets.

- It's clear what will and won't be done

The MVP will include the builder page, a tabular grants view, and a graph or two.
We will progress as far as possible the allotted time.

- Any uncertainty, assumptions, dependencies or constraints are recorded

There is uncertainty around the load that widgets may place on Grantnav. If widgets are placed on high traffic pages this could create an unsustainable load for Grantnav. This risk will need to be monitored.

- There's an order-of-magnitude estimate of how long it will take

We have a budget of 4 days.

- The work's been approved by someone at ThreeSixtyGiving

@mariongalley 

- There are links to everything that's written down about the work - such as plan.io tickets, GitHub issues

[User Stories](https://docs.google.com/spreadsheets/d/1LyzRsgii9zwqdvpyHyC0rS7CB1eAxhJnovNeS4YeU3I/edit#gid=0)
[Brief](https://docs.google.com/document/d/1Oo315Ci78ryf1ZeBDt2FqHAkRlerPtvHJepLeCuOKc4/edit)
[Plan.io Issue](https://opendataservices.plan.io/issues/35118)

**Comment by Lathrisk** [comment]
@mariongalley 
I've tried to use components from the design system as much as possible, and I'm currently using assets from insights (e.g. the header image). I hope to have a preview of the tabular grants widget soon, but will likely integrate the filters after getting some basic functionality working. I've also been thinking about a small preview area, but won't invest too much time in that if it becomes a timesink.
   
A preview of the current state of the builder page:

![Screenshot from 2022-09-09 14-54-35](https://user-images.githubusercontent.com/517804/189366628-a23feee1-cfa1-42d0-8b18-df0eca3edd2c.png)

**Comment by mariongalley** [comment]
See also https://github.com/ThreeSixtyGiving/dataquality/issues/59

**Comment by Lathrisk** [comment]
@mariongalley @KDuerden @michaelwood 

A [dev deploy is available](http://grantnav.360dev1.vs.mythic-beasts.com/widgets?query=potato&default_field=%2A&sort=_score+desc)

This uses the existing search page. This will reduce duplication of the filters and facets, and provide all of the context that we need for generating tables and graphs.

We will likely need to consider passing useful configuration options to the graphing elements as I suspect we don't want them to look like the little summary box visualisations we already have. There are also some quirks with the grants tables view that will need to be ironed out.

**Comment by Lathrisk** [comment]
@mariongalley 
Thanks for flagging that. The URL used for the select2 filters - all of the text search filters - was hard coded in the data so I've updated to redirect to the current page, and that has been deployed to the dev site.

The biggest time sink for this work is handling all of the filters correctly, and ensuring that they are correctly preserved when we hand them between URLs, including the new widgets.

**Comment by mariongalley** [comment]
@Lathrisk I've finally got round to testing the actual embed itself on our staging site - it seems to throw a Page Not Found error within the iFrame itself, which I'm not sure if it's user error or a failure of the widget.

**Comment by Lathrisk** [comment]
@mariongalley I've just pushed another small fix for that. It was set to only work on the origin domain, so the path to the widget was relative to the current domain. I've updated it so that it will reference the dev server domain in the code snippet.

Let me know if you have any other problems with the demo.

**Comment by Lathrisk** [comment]
Update on the Widgets MVP:

We have a demo page on the dev server, this includes:

- widget builder based on the Grantnav search page
- grants table widget
- amount awarded graph widget (unstyled)
- date awarded graph widget (unstyled)

This work is currently sitting on top of the `new-orgs` branch. The following work would be required before we can consider the widgets branch ready for a live deploy:

- Code review and potential refactor
- Restyling of the graph widgets (amount awarded and date awarded)
- Limiting access to the widgets builder (password protected, obfuscated URL, etc - tbc)
- Deployment of the org work is a dependency

Once this additional work is completed we can start to create additional widgets. It is likely these will be based on insights visualisations in the first instance.

**Comment by mariongalley** [comment]
Widgets - minor changes #873

**Comment by mariongalley** [comment]
Update:

- [ ] - [ ] Code review and potential refactor
- [ ] Restyling of the graph widgets (amount awarded and date awarded)
- [ ] Limiting access to the widgets builder (password protected, obfuscated URL, etc - tbc)
- [ ] Deployment of the org work is a dependency

**Comment by mariongalley** [comment]
@michaelwood Limiting access is still do to. Then I think this can be closed, all non MVP work is documented in separate issues, including #908

**Comment by mariongalley** [comment]
@michaelwood Any chance password protection can be done this morning?

**Comment by mariongalley** [comment]
Adding bugs to project board and closing issue
