### ISSUE TITLE
Explore Grants CTA opens up grants search but Funder filter is uneditable

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#865]
**Describe the bug**

When you click Explore Grants on a Funder in the Funder search page, the resulting search has the funder filter appearing as though nothing is selected and with no ability to change the selection (or change the funding org type selection).

When you click Explore Grants on a Recipient in the Recipient search page,  the resulting search has the funder filter with no ability to change the selection (or change the funding org type selection), but the Recipient does appear selected in the Recipient filter and it is possible to change the Recipient selection.

**Expected behavior**

You should be able to change the Funder/Funding Org type selection in both cases, otherwise the user is stuck at a dead end where they only way to clear/change their search is by returning to the home page.

Also for consistency if you can add/remove recipients after Exploring a Recipient's grants, you should be able to add/remove funders after Exploring a funder's grants, for consistency.

**Screenshots**

![image](https://user-images.githubusercontent.com/82958988/193838234-273d92c4-11ab-44bd-a434-cf4ff4c80685.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by mariongalley** [comment]
Update: You also can't change the Funder selection in the widget builder interface, so I think it has nothing to do with the Explore Grants CTA and is an issue with dev GrantNav more generally.

**Comment by michaelwood** [comment]
This was an issue with the data exported from dev datastore missing the additional data TSGOrgtype field, this is now present and the offending if-condition on the filter removed. Note on the dev site the "funding Org type" is empty as I've not done a new data run for this.
