### ISSUE TITLE
Increase the number of location fields handled by GrantNav

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#868]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

Grants from Publishers who provide geocodes for Country or Region do not appear in location searches in GrantNav

**Describe the solution you'd like**

Make GrantNav able to handle the same location fields as Insights, including Region and Country geocodes.

**Describe alternatives you've considered**

**Additional context**

**Comment by KDuerden** [comment]
My understanding is that UK-wide country codes are not used in Insights map or filters but England, Scotland, Wales and NI are, as well as English regions are. This would be the expected behaviour for GrantNav filters too.

**Comment by mariongalley** [comment]
@KDuerden Could you share the example of a funder who shared Region level data that's mapped in Insights but not GrantNav?

**Comment by KDuerden** [comment]
Only example of region level recipient location I know of is The Fore's older grants (2013-2017) - [this is the grants filtered in Insights](https://insights.threesixtygiving.org/data?awardDates.max.month=07&awardDates.max.year=2017&funders=GB-CHC-1123081)

![image](https://user-images.githubusercontent.com/20462640/203360956-944b01dd-0835-4d8b-803d-f101f0be5277.png)

If you open the view in [GrantNav, there is no location data](https://grantnav.threesixtygiving.org/search?max_date=07%2F2017&fundingOrganization=GB-CHC-1123081).

There are lots of examples of funders sharing beneficiary location at region/country level but as GN doesn't know how to use that data yet, this is probably better like for like comparison.

**Comment by michaelwood** [comment]
I think this is fixed now that insights and grantnav are using the same geo location mechanism & data. The example in @KDuerden 's comment seems to work well now.

**Comment by mariongalley** [comment]
Agreed, thanks @michaelwood (please reopen if this is wrong @KDuerden )
