### ISSUE TITLE
GrantNav org pages development - Links from table direct to wrong destination

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/grantnav#870]
**Describe the bug**
Hyperlinks in New table view in GrantNav search link to old format urls, rather than new url format.

Table view in main search - hyperlink to Funder, Recipient or Grant view is using old url pattern, so gives null result - or directs to current GN.

For example if you view this search in table view:

http://grantnav.360dev1.vs.mythic-beasts.com/search?query=%22mental+health%22&default_field=%2A&sort=_score+desc&min_date=04%2F2022&max_date=05%2F2022&recipientDistrictName=County+Durham

![image](https://user-images.githubusercontent.com/20462640/195400728-9d748133-c95d-4638-a605-ce9a3814035c.png)

Recipient
Currently linking to: http://grantnav.360dev1.vs.mythic-beasts.com/recipient/GB-CHC-1187899
Should be linking to: http://grantnav.360dev1.vs.mythic-beasts.com/org/GB-CHC-1187899

Funder
Currently linking to: http://grantnav.360dev1.vs.mythic-beasts.com/funder/GB-GOR-PB188
Should be linking to: http://grantnav.360dev1.vs.mythic-beasts.com/org/GB-GOR-PB188

Grant links - I assume are correct format for the url, but are set to live rather than dev site - eg https://grantnav.threesixtygiving.org/grant/360G-tnlcomfund-0045455879

**Comment by Lathrisk** [comment]
@KDuerden @mariongalley 
I've updated this on the dev server so that grant links are now relative to the current domain, and funder and recipients link to the org pages. These links are hard coded in the javascript but should now be correct.

**Comment by mariongalley** [comment]
This is fixed in the Widgets branch, but in that branch the Region & District page tables are broken. @michaelwood Will there be an opportunity to test the Org pages, Widgets & Table view all grouped together have all the bug fixes applied before putting it live?
