### ISSUE TITLE
Title sorting in table view not behaving as expected

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#872]
**Describe the bug**

Sorting on Amount, Date, Funder and Recipient is behaving as expected, but sorting on title changes the order in a way that looks quite random and isn't alphabetical.

**To Reproduce**

- Make any search in GrantNav, for example ["mental health"]](http://grantnav.360dev1.vs.mythic-beasts.com/search?query=%22mental+health%22&default_field=%2A&sort=_score+desc)
- Switch results to table view
- Click on the sort control for the Title column
- Results change order but not based on any discernible logic

**Expected behavior**

Results should appear alphabetically in asc/desc order

**Screenshots**

![image](https://user-images.githubusercontent.com/82958988/195799232-906ba992-92aa-4af0-a525-14bc87501c40.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lathrisk** [comment]
@mariongalley 
I think this column might be sorted based on a 'score' metric. I believe the score is a search relevance metric generated by Elasticsearch. I'll either get it working as an alphabetical sort, or remove sorting options for that column.

**Comment by mariongalley** [comment]
@Lathrisk Thanks Jared, I guess Relevance is probably the most useful sort order for this field (alphabetical on Title is a bit pointless really), but switching to Least Relevant is not useful, so happy to just remove the sort function on the column altogether.

**Comment by mariongalley** [comment]
@Lathrisk Update: I've realised that removing Title sort means you can't go back to relevance sorting after you've decided to sort by any other column. Might need to add a "relevance" button or similar?

**Comment by Lathrisk** [comment]
@mariongalley yes, I actually think that might have been why I kept that sort option. It was frustrating to sort by amount or date and then have no way back, it also means that the card view and table view move out of sync. That might not matter, but as you say, it's nice to have a way to revert to the original sorting.

**Comment by mariongalley** [comment]
@Lathrisk I wonder if there's a way to make it clear that it's by relevance? I appreciate it breaks with the pattern of having an unlabelled sort button with an arrow by each column header, but I think in this instance it's needed. Maybe just a button labelled "Relevance" that doesn't allow you change the sort direction as least relevant isn't needed.

**Comment by Lathrisk** [comment]
@mariongalley We could just parenthesis the sorting option. Is that clear enough?

![Screenshot from 2022-10-18 15-34-04](https://user-images.githubusercontent.com/517804/196461571-d0592094-ed58-4911-bad1-e1f4d38f74b4.png)

**Comment by mariongalley** [comment]
@Lathrisk Hmmm, maybe... Could it be right-aligned and made grey so that it's clearer it pertains to the sort and isn't part of the column header?

**Comment by Lathrisk** [comment]
@mariongalley I'm not sure if I have that level of customisation control in that table library we're using, but I'll investigate options and update soon.

**Comment by robredpath** [comment]
> that level of customisation control in that table library 

I don't think we're that attached to that table library, and maybe @kindly even looked into alternatives?

**Comment by mariongalley** [comment]
My preference, if possible, would be to replace sorting button on the Title column with a single button that says "Best Match".

**Comment by mariongalley** [comment]
Suggest removing table sorting altogether and bringing in the Sort drop-down from the Classic view which sorts all data not just the data displayed in the table

**Comment by mariongalley** [comment]
I think this is fixed @michaelwood

**Comment by michaelwood** [comment]
> I think this is fixed @michaelwood

Yeah the original issue does look fixed, I noticed a nice-to-have improvement and have logged it https://github.com/ThreeSixtyGiving/grantnav/issues/901
