### ISSUE TITLE
Table view - make it 'sticky'

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#874]
**Describe the bug**

**To Reproduce**
1. Go to GrantNav search
2. Click on Table view
3. Apply any filter
4. See search results have switched back to "Card" view

**Expected behavior**

Expect the view selector to work more like a filter and persist rather than making the user select it again each time they amend their search. Assume that people who prefer table view will want to use it for their whole session and not just one search.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lathrisk** [comment]
I've set this up on the branch so that the view selection is preserved in the query string. This has not yet been deployed to the dev server.

**Comment by michaelwood** [comment]
Now deployed to dev server. We now depend on the session database and need to add this to the requirements for running grantnav (this is the case in live but needs to be added to the install docs).
