### ISSUE TITLE
Table view: minor changes

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#875]
- [x] Remove "search all fields" search bar in table view - main search box should be used in this instance
    - This might be a hangover from the table view being used elsewhere?
- [x] Rename "Card view" to "Classic view" or similar
    - Suggestions for alternative names include Classic view, Simple view or Default view. Gmail calls the less compact view "Comfortable" view but that seems a bit silly. Any other suggestions or preference between the options listed?

![image](https://user-images.githubusercontent.com/82958988/196732456-89b09ec3-382b-47a5-89a9-0f6ef4f31c2e.png)

**Comment by codemacabre** [comment]
These changes are now on dev. 🎉
