### ISSUE TITLE
De-duplicate orgs using ftc data

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#877]
(mechanism actually lives in the datastore, but tracking here for org pages work)

Fix regression in de-duplication mechanism

**Comment by mariongalley** [comment]
@michaelwood Since these have the same org ID should they not be one record?

![image](https://user-images.githubusercontent.com/82958988/201912846-4d0a3e55-b18a-4e03-8614-d2e59bf08590.png)
