### ISSUE TITLE
As Publisher - Datasets table is missing information from ‘Funders Covered’

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#882]
**Describe the bug**

On the As Publisher section, where it's available, the Datasets table column for Funders Covered is blank. It should contain a list of all the Funders covered in the dataset, as in live GrantNav.

**To Reproduce**
1. Go to Funder search
2. Select any funder with a Publisher section, e.g. Sport England
3. Scroll to As Publisher section to view Datasets table

**Expected behavior**

The Datasets table Funders Covered column should contain a list of all the Funders covered in the dataset, as in live GrantNav.

**Screenshots**

Dev GrantNav Publisher section - Sport England:

![image](https://user-images.githubusercontent.com/82958988/197545169-94a9c5d4-0f9f-442a-8d3d-0991db3f79d5.png)

Live GrantNav Publisher page - Sport England:

![image](https://user-images.githubusercontent.com/82958988/197545910-01cdc907-4eb2-4248-a202-033c0fe661ce.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by michaelwood** [comment]
Now fixed http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/org/GB-COH-RC000766 (this was actually a data directory location issue on the dev server but I've improved the code to be agnostic of the directory location so now works regardless)

**Comment by mariongalley** [comment]
Thank you!
