### ISSUE TITLE
Need error pages for Funder and Recipient search

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#883]
**Describe the bug**

Currently user is taken to the main search error page, with the orange background. This is confusing, so it should take users to new error pages with teal/yellow backgrounds.

**To Reproduce**

See for example [this query](http://grantnav.360dev1.vs.mythic-beasts.com/recipients?sort=currencyTotal.GBP+desc&json_query=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22must%22%3A+%7B%22query_string%22%3A+%7B%22query%22%3A+%22*%22%2C+%22default_field%22%3A+%22*%22%7D%7D%2C+%22filter%22%3A+%5B%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%5D%7D%7D%2C+%22sort%22%3A+%7B%22grants%22%3A+%7B%22order%22%3A+%22desc%22%7D%7D%2C+%22aggs%22%3A+%7B%22currency%22%3A+%7B%22terms%22%3A+%7B%22field%22%3A+%22currency%22%2C+%22size%22%3A+5000%7D%7D%7D%7D)

**Expected behavior**

When there is an error, take users to new error pages with teal/yellow backgrounds.

**Screenshots**

![image](https://user-images.githubusercontent.com/82958988/197551953-3cce457b-0345-4e4c-857a-211cf5c4ff50.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by michaelwood** [comment]
Thanks. Fixed (happened to be in that bit of code), fix applied on new dev server: http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/
