### ISSUE TITLE
Funder search and funding org type not available in dev GrantNav

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#884]
**Describe the bug**

It is not possible to use the Funder filter in the main search in dev GrantNav as the Funding Org type and Funding Org filters aren't rendered.

**To Reproduce**
1. Go to all grants search
2. Scroll down filters to Funder filter
3. See that it is not possible to expand Funding Org type or Funding Org

**Expected behavior**

Allow expanding Funding Org Type and Funding Org as in Live GrantNav.

**Screenshots**

Dev GrantNav:

![image](https://user-images.githubusercontent.com/82958988/197556398-3487148d-0cbc-411b-b32e-eb8442f8dc02.png)

Live GrantNav:

![image](https://user-images.githubusercontent.com/82958988/197556539-25275a53-b8b4-476d-9424-39386b1303fe.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by michaelwood** [comment]
Thanks for the screenshots. Believed fixed/explained in https://github.com/ThreeSixtyGiving/grantnav/issues/865#issuecomment-1291895407

**Comment by mariongalley** [comment]
Agreed, funder search now working. Funding org type not working but consistent with your explanation in #865

**Comment by mariongalley** [comment]
Funding org type still not working in dev GrantNav @michaelwood - testing at this URL: http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/search?query=%2A&default_field=%2A&sort=_score+desc

**Comment by mariongalley** [comment]
OK - if you do that will it be OK for us to test it in the morning before agreeing to go live?
