### ISSUE TITLE
Table view - major error

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#898]
**Describe the bug**

Clicking on table view on a GrantNav search returns an error page.

**To Reproduce**

1. Go to GrantNav
2. View all grants or filter data
3. Click table view
4. Get error

http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/search?view_mode=table

**Expected behavior**

Grants should appear in a nice table

**Screenshots**

Lots of screens of errors

![image](https://user-images.githubusercontent.com/82958988/201144423-ad25e0b3-d117-4df9-8519-1dfc474aec6f.png)

![image](https://user-images.githubusercontent.com/82958988/201144775-f9d4c70c-886d-4697-b4b0-c4c181ae9b4c.png)

**Comment by michaelwood** [comment]
Fixed (dev site needed user session database rewriting after changes)
