### ISSUE TITLE
Table view - reduce amount of scrolling

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#906]
**Is your feature request related to a problem? Please describe.**
It's frustrating how much you have to scroll when in Table view in Grants search

**Describe the solution you'd like**
1) I'd suggest making the table itself taller so it at least extends as low as the left-hand filters
2) Perhaps it needs pagination instead of infinite scroll?

**Describe alternatives you've considered**
Open to other alternatives, not committed to pagination as the solution, but not sure what the options are

**Additional context**
Lots of white space whereas the filters continue down the side

![image](https://user-images.githubusercontent.com/82958988/201871964-ae04052b-d9a2-4368-9bb9-b4cd4d4bf9a5.png)

**Comment by codemacabre** [comment]
@mariongalley There are a few possible solutions to this; pagination is probably the simplest and potentially the most accessible.

1. Adding pagination gives a drop-down to select how many rows to show, which selects a pre-defined height:
   ![image](https://user-images.githubusercontent.com/49149591/205003493-5d3ebee2-6404-4ea0-a779-b14d5fdedf8d.png)

   So 10 rows is roughly the same height as the table is at the moment, whereas 100 rows extends the table beyond the filter side-panel.

   And we can style the pagination however we like:

   ![image](https://user-images.githubusercontent.com/49149591/205001770-861ba526-ba8b-4952-93fb-704474e02704.png)

2. Keeping the scroll behaviour and increasing the height of the table is, by default, a hard-coded value. At the moment it's 300px, but we can use around 1200px to make it roughly the same height as the filter side-panel. The height relation between table and filter panel will vary depending on filters available, user selections, etc., but it will show around 33 rows.

3. Keeping the scroll behaviour and increasing the height of the table responsively (i.e. so it automatically fills available space) is possible but will require a bit of extra CSS work.

**Comment by mariongalley** [comment]
Thanks for explaining the options so clearly @codemacabre - I think option 1 is probably best.

1. Can we make it default to 25 rows as this is closest to the ~ 33 needed to fill out the page on a large screen?
2. Can the pagination by styled identically to in Classic view for consistency?

![image](https://user-images.githubusercontent.com/82958988/205015530-f16524a9-b702-41e6-b3dc-144a2a5043b1.png)

**Comment by codemacabre** [comment]
>     2. Can the pagination by styled identically to in Classic view for consistency?
I can try to get it as close as I can, but it won't be identical, as the pagination for the table is generated by the table itself. While it does have several customisation options, it has a different HTML structure, so styling can only do so much to make it match.
