### ISSUE TITLE
Move widgets urls to something namespaced

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#907]
We currently provide widget outputs on the root url:

```python
  url(r'^widgets', views.search, {'template_name': 'search_widgets.html'}, name='search.widgets'),
    url(r'^widgets.api', views.search_wrapper_xframe_exempt, name='widgets.api'),
    url(r'^tabular', views.search_wrapper_xframe_exempt, {'template_name': 'widgets/tabular_grants.html'}, name='widgets.tabular'),
    url(r'^amount_graph', views.search_wrapper_xframe_exempt, {'template_name': 'widgets/amount_graph.html'}, name='widgets.amount_graph'),
    url(r'^date_graph', views.search_wrapper_xframe_exempt, {'template_name': 'widgets/date_graph.html'}, name='widgets.date_graph'),
```
https://github.com/ThreeSixtyGiving/grantnav/blob/Nov2022/grantnav/frontend/urls.py#L13

To be able to easily filter/identify the widgets output urls from the widget builder page in order to do some access control we need to put them on their own url end point such as `/widget-render/tabular` `/widget-render/date_graph`  so that we can specify access allowed on `/widget-render/*` 

Needs to be done before widgets are used otherwise we'll need to maintain redirects for the rest of time.

**Comment by mariongalley** [comment]
Thanks @michaelwood , Widgets won't be used until next week earliest - is this achievable by then?

**Comment by michaelwood** [comment]
> Thanks @michaelwood , Widgets won't be used until next week earliest - is this achievable by then?

Do I still have time to make this change? - It would impact anyone who already has a widget embedded. It is mostly for neatness so no worries if that ship has sailed/not possible now.

**Comment by mariongalley** [comment]
@michaelwood Yep go for it!
