### ISSUE TITLE
If you download a search in Table mode - it's the entire dataset

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#915]
**Describe the bug**

If you download a search in Table mode - it's the entire dataset.

GN doesn't apply the filters so you get http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/search.csv

When it is in classic mode the url for the download is so the specific filter is embedded: http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/search.csv?fundingOrganization=GB-CHC-200051&view_mode=card

**To Reproduce**
1. Go to GrantNav search
2. Switch to Table view
3. Apply filters
4. Download your search
5. See that the download is unfiltered

**Expected behavior**
The download should be filtered to the user's search

**Comment by mariongalley** [comment]
@michaelwood How complex is this to fix?

**Comment by michaelwood** [comment]
@Lathrisk Any ideas? possibly just the parameters are missing but I didn't think it had a separate download mechanism..

**Comment by mariongalley** [comment]
@michaelwood Suggestion from Katherine that if this can't be fixed today we just hide the download buttons while in table view and don't let it block go live. I saw you've proposed a fix so we'll wait and see if that works first, but good to have a backup plan I think.

**Comment by michaelwood** [comment]
Fix now merged and is on dev site.

**Comment by KDuerden** [comment]
Thank you, I've tested too and I can see it is working now.
