### ISSUE TITLE
Table view: View-switching radiobuttons and Download buttons are off-screen on smaller widths

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#918]
**Describe the bug**

In classic view, you can see the radiobutton to switch views and the download buttons on smaller screen widths.
In card view, you have to use the scrollbar to scroll horizontally to see them.

**To Reproduce**
1. Go to GrantNav search
2. Make your screen narrower
3. Switch to card view
4. Radiobuttons and download buttons are no longer visible

**Expected behavior**

- [x]  I'd like to be able to see the buttons on any screen size
- [x]  I'd also like the Insights button to appear in Table view

**Screenshots**

Table view

![image](https://user-images.githubusercontent.com/82958988/202224476-5edf5b12-813e-41f9-94aa-4d7c362de6a5.png)

Classic view

![image](https://user-images.githubusercontent.com/82958988/202224706-d229a75c-717b-41ea-bd94-852c9914b67a.png)

**Comment by codemacabre** [comment]
> **Expected behavior**
> 
> * [ ]   I'd like to be able to see the buttons on any screen size
> 
> * [ ]   I'd also like the Insights button to appear in Table view

Fixing the table responsivity (i.e. the top item) involves changes to the design system; adding an Insights button involves changes to grantnav's `grants_table.html`, so this will require a couple of PRs to complete.
