### ISSUE TITLE
Sort order to be selectable in widget builder

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#923]
**Describe the bug**

Picking a sort order in the widget builder has no effect no the sort order in the widget itself. Widget defaults to Best Match.

**To Reproduce**

1. Go to widget builder
2. Make a selection of data and pick sort order "Latest date"
3. Embed widget on a web page
4. Selected sort order is ignored and defaults to best match

**Expected behavior**

Selected sort order should carry through to the widget

**Screenshots**

![image](https://user-images.githubusercontent.com/82958988/203349173-c98d7711-e82b-4a97-bac4-77a992ab7e77.png)

**Comment by codemacabre** [comment]
I'm going to move the "Sort By" dropdown out of the preview and into the settings card. This should make it more intuitive and work as expected.

<img width="400" src="https://user-images.githubusercontent.com/49149591/204311129-3c74c0d6-eb43-4f10-9538-47f80ef1227f.png" alt="Screenshot of the widget builder with the sort by dropdown removed from the preview card and inserted into the settings card. Red annotations highlight the applicable changes." />

**Comment by mariongalley** [comment]
> I'm going to move the "Sort By" dropdown out of the preview and into the settings card. This should make it more intuitive and work as expected.

Can it be in the preview as well as it needs to still be in the widget itself and people interacting with it should still be able to change the sort order?

**Comment by codemacabre** [comment]
Like this?
<img src="https://user-images.githubusercontent.com/49149591/204515473-88c3d03f-e06c-4399-8e98-8a8bf63242ee.png" width="400px" alt=""/>
