### ISSUE TITLE
Add Funding Type field to GrantNav download

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#928]
**Is your feature request related to a problem? Please describe.**
Currently the Funding Type field doesn't appear in the GN download

**Describe the solution you'd like**
Add Funding Type field to GrantNav download

**Additional context**
In future we could add a filter

**Comment by mariongalley** [comment]
Here are all the fields that are in the download https://github.com/ThreeSixtyGiving/grantnav/blob/master/grantnav/csv_layout.py

**Comment by michaelwood** [comment]
Could the exact field name wanted be added to this issue (viewing the additional data on a grant and copying the required field name can help find it). We have `additional_data: TSGFundingOrgType` in there currently but guess that's not the one you're wanting?

**Comment by mariongalley** [comment]
@michaelwood This isn't an additional data field, it's one of the core standard fields which as far as I can tell is called exactly "Funding Type" https://standard.threesixtygiving.org/en/latest/technical/reference/#funding-type

**Comment by michaelwood** [comment]
Ah great, thanks. `grant.fundingType` is a `Classification` object, is it one field of that object needed or all?

There is also `fundingOrganization.0.organisationType` which is just a `string`

**Comment by mariongalley** [comment]
Thanks @michaelwood , just the Title field for grant.fundingType please
