### ISSUE TITLE
Remove js debug function grants_tables_scripts.html

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#937]
Reminder issue to remove unused debug function in grants_tables_scripts.html template component :

```javascript
    table.on('responsive-display', function ( e, datatable, row, showHide, update ) {
    });
```

**Comment by codemacabre** [comment]
This was done in https://github.com/ThreeSixtyGiving/grantnav/commit/d0abf1c8c764eee51ab35b8da7c98289a7032e1d
