### ISSUE TITLE
Main search grants count doesn't match org page grants count

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#938]
**Describe the bug**
The number of grants for a given funder is lower in the main grants search than it is in the org page. Main search seems to be excluding some data.

**To Reproduce**
1. Go to main search
2. [Filter to Foyle Foundation](http://grantnav.360dev1.vs.mythic-beasts.com/search?query=%2A&default_field=%2A&sort=_score+desc&fundingOrganization=GB-CHC-1081766)
3. View grants count in grant summary (1,235)
4. Click on [Org page](http://grantnav.360dev1.vs.mythic-beasts.com/org/GB-CHC-1081766)
5. View grants count on As Funder section (1,915) - this matches live GrantNav)

**Expected behavior**
The grant counts should match live (where there hasn't been new data recently added) and the org pages

**Screenshots**
![image](https://user-images.githubusercontent.com/82958988/205966920-b0f8710f-5f57-437f-a150-312d9620daf0.png)

![image](https://user-images.githubusercontent.com/82958988/205966802-eceabed4-a61c-4d70-9da9-d76fa0b169fc.png)

**Comment by mariongalley** [comment]
@michaelwood Are you able to look into this issue?

**Comment by michaelwood** [comment]
I think we fixed this as a data loading issue. live seems to be correct for the example given
* https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&fundingOrganization=GB-CHC-1081766
* https://grantnav.threesixtygiving.org/org/GB-CHC-1081766
