### ISSUE TITLE
Scotland, NI, Wales missing from Country and Region filter

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#939]
**Describe the bug**
Scotland, NI and Wales missing from Country and Region filter and the summary cards

**To Reproduce**
1. Go to Main search
2. Click on Country and Region
3. See Scotland, NI and Wales are missing
4. Select a District in Scotland, NI or Wales
5. See the District appears but not the Country/Region on a result card

**Expected behavior**
The devolved nations should appear in the Country and Region filter and on result cards.

**Screenshots**
![image](https://user-images.githubusercontent.com/82958988/205967830-12e6eba0-7f1b-4366-a55a-eec82ae4e04a.png)

![image](https://user-images.githubusercontent.com/82958988/205968165-6758e576-e9f2-43a5-b392-ed1d0447e86d.png)

**Comment by michaelwood** [comment]
@mariongalley This behaviour is now updated and data reloaded on the dev grantnav

**Comment by mariongalley** [comment]
@michaelwood Just to note that I couldn't open [a search filtered to England](http://grantnav.360dev1.vs.mythic-beasts.com/search?query=%2A&default_field=%2A&sort=_score+desc&recipientRegionName=England) in [Insights](https://insights.threesixtygiving.org/data/6dee5735-459d-4b51-8030-1dcd87a4425a).

**Comment by michaelwood** [comment]
It isn't/shouldn't be possible to open any dev grantnav searches in the live insights without us specifically authorising dev grantnav (https://github.com/ThreeSixtyGiving/360insights/blob/live/insights/settings.py#L136). We can do this but it will require adding configuration and restarting live insights.

**Comment by mariongalley** [comment]
Confirmed that it won't be necessary to test opening searches in Insights.
