### ISSUE TITLE
Scrolling search results but not facets

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/grantnav#94]
(or vice versa) 

Currently GrantNav has one scroll for the whole page.  How can we scroll just the results. for example?

**Comment by kindly** [comment]
I  want to avoid separate scrolling as it is messy to implement and can end up with something more confusing.  If it is done, I would wait till the last minute (i.e after every other design decision has been made) as once you put it in it is hard to maintain with other design changes.

**Comment by robredpath** [comment]
Closing. Re-open if we get strong support from the community for this!

**Comment by stevieflow** [comment]
I want to keep this open, as it was strong feedback we received already - it could also be picked up in user observations

**Comment by robredpath** [comment]
@stevieflow can we close this now? We dealt with the underlying need by shortening facets.

**Comment by stevieflow** [comment]
Push to backlog? But - cant see the a backlog category now

**Comment by robredpath** [comment]
@stevieflow the backlog is split between 'ideas and reports' and 'ready'. This is definitely in the category of 'ideas and reports'.

**Comment by stevieflow** [comment]
This needs user testing

**Comment by robredpath** [comment]
We've shortened facets further, and this didn't come up in the last round of user testing. Closing.
