### ISSUE TITLE
Downloads not working

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#955]
**Describe the bug**
Clicking the download button on the GrantNav search page attempts but does not succeed in downloading the data. This is the case whether it's an empty search or a filtered search.

**To Reproduce**
1. Go to https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc
2. Click on 'Export search data:' CSV or JSON button
3. See the download start but never complete

**Expected behavior**
I would expect the file to download

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro version 21H2
 - Browser: Chrome
 - Version: Version 109.0.5414.75

**Comment by mariongalley** [comment]
Wasn't able to reproduce the issue, and user reports being able to download the data also

**Comment by mariongalley** [comment]
They were using the links shared on our website https://www.threesixtygiving.org/data/using-the-data/technical-users/#GrantNav_data which return 500 errors.

Are these links out of date @michaelwood ?

**Comment by mariongalley** [comment]
@michaelwood Yeah I'd be OK with just replacing the links on our website personally. Maybe we should check with @drkane if those links have been widely shared/are widely used in case it causes issues if we deprecate them?

**Comment by robredpath** [comment]
@michaelwood the hack of having `/api` in GN has lasted far longer than I ever expected! Given that an actual API is now on the roadmap, it's probably a good time to deprecate it...

**Comment by mariongalley** [comment]
Vicky is going to update the links on our website very soon - is there a task to deprecate /api still needed?

**Comment by michaelwood** [comment]
> Vicky is going to update the links on our website very soon - is there a task to deprecate /api still needed?

Yes will be a good idea to now remove it.
