### ISSUE TITLE
Add recipient individuals count to home page headline stats

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#957]
Add the count of recipient individuals to the headline stats. 

Some design thought is needed here on the home page. Space is quite limited, we will want to avoid the wrapping like, or if it does wrap make sure we can make them all align the same:

![image](https://user-images.githubusercontent.com/493697/214682330-6d8388cf-b3a7-4117-ab31-9f71114f1a94.png)

Removing the word recipient:

![image](https://user-images.githubusercontent.com/493697/214682787-1aec797d-8bae-4809-ac15-154058db5a3b.png)

Slightly left field suggestion - We could also make it into a sentence:

![image](https://user-images.githubusercontent.com/493697/214684649-09b68341-ccad-44d2-8e86-221e6b1d9221.png)

This is likely going to be an issue across all the tools, "organisations" and "individuals" being rather long words.

**Comment by michaelwood** [comment]
*across  / with

**Comment by michaelwood** [comment]
I think multiple rows might be good option. We could neaten that up by making it a square, the grid system in the 360-design system is a little overly space-y so we could also compress that with a custom style too.

![image](https://user-images.githubusercontent.com/493697/215120453-1d549bb9-60d5-4653-8167-558dfcf867cb.png)

Or using the existing headline stats widget that we use elsewhere could also work:

![image](https://user-images.githubusercontent.com/493697/215126250-79ae2c74-ce64-4691-a457-2f67555c1132.png)


Another option is also scaling the whole headline stats to be smaller so that it won't wrap - smaller font size and so on. They start to loose their headline ability though.

**Comment by michaelwood** [comment]
Also if someone can come up with a longer word than "all" in "Search All grants" then that helps with the symmetry :)

**Comment by KDuerden** [comment]
Very good, these look nice.

I also like the the first option best, and I agree on the rearrangement of the links to have Funders & Grants first, with the two recipient types below.

**Comment by michaelwood** [comment]
Just to double check (forgot to number the options!) first option as in (and not one in a previous message):

> I think multiple rows might be good option. We could neaten that up by making it a square, the grid system in the 360-design system is a little overly space-y so we could also compress that with a custom style too.
> 
> ![image](https://user-images.githubusercontent.com/493697/215120453-1d549bb9-60d5-4653-8167-558dfcf867cb.png)
>

**Comment by mariongalley** [comment]
Yes, correct, the first option in [this comment](https://github.com/ThreeSixtyGiving/grantnav/issues/957#issuecomment-1406672197)

**Comment by mariongalley** [comment]
Just realised, we also need to update the summary table - separate issue for that maybe?
![image](https://user-images.githubusercontent.com/82958988/217222108-c2d05ddc-a4ff-4d4f-94f0-ae17593e5abd.png)

**Comment by michaelwood** [comment]
Yep thanks spotted that one :) https://github.com/ThreeSixtyGiving/grantnav/compare/master...mw/std_updates_1#diff-678480b1b0158a60a5e64fd6e498e4915ce09c6fac1c3598176c5ab0ed4704ed

**Comment by mariongalley** [comment]
Ah great - does that just add an extra row to the summary table then?

**Comment by michaelwood** [comment]
Yeah, looks like this: 

![image](https://user-images.githubusercontent.com/493697/217231421-f09f3a22-d7f0-4737-8c82-0aebc7a75a9d.png)

**Comment by mariongalley** [comment]
@michaelwood Is it possible to reduce this bit of white space so that the second row of stats isn't below the fold on common screen sizes?

![image](https://user-images.githubusercontent.com/82958988/220164813-cbf77d2e-f2b7-4fa9-874a-d3e2cbe98bad.png)

**Comment by michaelwood** [comment]
I had a short go (about an hour) at changing various rules for the white space, it's surprisingly difficult. Unfortunately removing the padding for a grid item means that the content below also gets shunted up so we end up with buttons and the covid banner right up against each other. If it wasn't a responsive design we could get away with fixed sizes but this grid is designed to re-flow based on available window size (e.g. on mobile it will go into a single column). 

We could possibly be able to design a new grid just for the front page. One of the things to consider with deviating from the design system (and this is true of most design systems) is that all spacing is consistent and usually multiples of a base size, so to change needs a bi more design work to avoid fragment the UI. @codemacabre may have some better suggestions.

**Comment by michaelwood** [comment]
Spotted that if a `recipientIndividual.id` is duplicated it won't be counted as the totals are the aggregate . This is probably not what we want so investigating

**Comment by KDuerden** [comment]
> Spotted that if a recipientIndividual.id is duplicated it won't be counted as the totals are the aggregate . This is probably not what we want so investigating

Thanks for flagging this. Is not wanting this related to data protection? It will be impossible for an individual ID to be shared across different funders, but a single funder may fund a person multiple times, so the data may include a single recipient ID with multiple grant records. I had assumed if this was the case the counts would be unique counts.

**Comment by mariongalley** [comment]
Agree with Katherine - I'm happy for multiple grants with the same individual recipient ID to result in only 1 individual being counted - we've told funders that they may use the same ID if one individual received multiple grants, although many indicated this is rare

**Comment by mariongalley** [comment]
> In the filters for recipient type we are saying "this is the total number of grants made to type: individuals" and "this is the total number of grants made to type: organisations" both those add up to the total number of grants in the system.

Yes absolutely when we're filtering we're showing the count of grants - we can't aggregate here.

> I do wonder about this assertion though, specifically with individuals ids, as we can't say that each individual id is "an individual". For example, 360G-XYZFunder-123456 could be the same individual as 360G-GHIFunder-123456.

Yes that's true, but we can't assert this about the organisations either, so it has the same weight.

Are you happy to close this issue or is there more we need to do on it?

**Comment by michaelwood** [comment]
> 
> > I do wonder about this assertion though, specifically with individuals ids, as we can't say that each individual id is "an individual". For example, 360G-XYZFunder-123456 could be the same individual as 360G-GHIFunder-123456.
> 
> Yes that's true, but we can't assert this about the organisations either, so it has the same weight.

If the org-ids are used correctly this can be a safe assertion though.

> 
> Are you happy to close this issue or is there more we need to do on it?

Yep happy to close. To summarise what we're going for is: summary stats count the total number of unique individual ids. Filters count the total number of grants made out to either type.
