### ISSUE TITLE
Ability to limit the grants table to a small number of rows instead of showing the full results of the query

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#959]
**Is your feature request related to a problem? Please describe.**
Publishers want to show e.g. the 10 most recent grants, and no more, in the widgets table, to avoid pagination and scrolling.

**Describe the solution you'd like**
In the widgets builder, ability to limit the amount of rows shown for the table view.

**Describe alternatives you've considered**
Users can currently show 25, 50, 75 or a hundred rows.

**Comment by codemacabre** [comment]
@mariongalley Would you like the existing ability to show 25, 50, 75 or 100 rows to be disabled / hidden when reducing the widget to `x` number of rows?

**Comment by mariongalley** [comment]
@codemacabre Good question - yes I think so. The publisher in question wanted to limit the rows to stop people having an overwhelming amount of data, so yes I think the users shouldn't have the option to add more
