### ISSUE TITLE
Regranting type filter

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/grantnav#977]
> Add Regranting yes/no/both - display low down the list of filters Presence of any code is an umbrella for doing regranting This logic will apply to other codelists in future.

**Comment by michaelwood** [comment]
@mariongalley this option comes for "free" as we have the existing code/widgets for it

![image](https://user-images.githubusercontent.com/493697/220970350-4e9ac8b0-0f17-487f-b623-f73f10e4f4d3.png)

Does this do what is needed, or shall I write a new widget to collapse the options?

**Comment by mariongalley** [comment]
@michaelwood I think we don't want to expand the regrant type options as they aren't intuitive necessarily, we we'd prefer to group them all together

**Comment by michaelwood** [comment]
Wasn't sure on the copy for this, but have added the collapsing functionality. 

![image](https://user-images.githubusercontent.com/493697/221000974-2f02a46b-41ea-421b-bb5c-a30b9d82febf.png)

http://grantnav.360dev1.vs.mythic-beasts.com/search

**Comment by mariongalley** [comment]
@michaelwood Suggest Direct grant rather than Regular grant but will need to run this past the team.

**Comment by mariongalley** [comment]
@michaelwood Confirmed Direct grant is suitable, and please can we call the filter Grant type rather than Regrant type?
