### ISSUE TITLE
Universal cookie does not remember user saying no to cookies

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#982]
**Describe the bug**
If I click No to cookies on a threesixtygiving site, I expect not to be asked again within a short time frame.

**To Reproduce**
1. Go to a 360Giving tool
2. Decline cookies
3. Wait 1 day
4. Go to the same or a different 360Giving tool
5. Warning pops up again

**Expected behavior**
Remember users declining cookies

Browser: Chrome, but same issue happens in Firefox

**Comment by codemacabre** [comment]
It looks like the cookie expiry isn't set, which means the browser deletes it depending on what it defines as a session. @mariongalley how long would you like the cookie to be set for? A month seems about right to me.

**Comment by mariongalley** [comment]
@codemacabre Good question - when we spoke with Michael he said it would be set until cookies are deleted, so I don't know if it's considered poor practice to set the cookie indefinitely?

**Comment by codemacabre** [comment]
@mariongalley Cookie expiry needs to be proportionate and the [ICO states](https://ico.org.uk/for-organisations/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/how-do-we-comply-with-the-cookie-rules/#comply20) indefinite is never proportionate.

I propose 30 days to start with and we can assess going forward?

**Comment by mariongalley** [comment]
Thanks @codemacabre - that sounds good to me. Please can you let me know when it's implemented so I can advise the team?

**Comment by codemacabre** [comment]
Note that Matomo's cookies are by default set to be remembered forever (see https://developer.matomo.org/guides/tracking-consent). So the above issue must be caused by opting out of analytics, as we control that cookie.

**Comment by codemacabre** [comment]
This has now been deployed across the various sites / apps. Users might need to clear current cookies to make sure the existing cookie is replaced, but this should happen automatically whenever the existing cookie expires.

**Comment by mariongalley** [comment]
@codemacabre I've had another user report the cookie pop up returning every time they visit our site(s). They use Chrome on Mac. Are ODSC team able to test this and reproduce on different OSes/Browsers? And should this be a new issue?

**Comment by codemacabre** [comment]
@mariongalley I've tested this on various OSs and browsers including Chrome on Mac, and can't reproduce, with the exception of having browser privacy settings and extensions set to automatically clear cookies, etc. The only explanation I can give is that the users must have a setting or an extension which resets the cookie expiry.

In Chrome settings, under 'Privacy and Security', there is a section to explicitly allow cookies - if they add `threesixtygiving.org` there, that should override any browser-based settings.
![image](https://github.com/ThreeSixtyGiving/grantnav/assets/49149591/3b49c9fd-32da-4894-a9e6-4fe9d93c5e8b)

If they have any extensions active, they might need to try deactivating them to see which might be causing an issue.

**Comment by mariongalley** [comment]
Thanks @codemacabre !
