### ISSUE TITLE
Setting GrantNav calculation of grant amounts to match Insights

### ISSUE THREAD

**Issue by anambcodes** [ThreeSixtyGiving/grantnav#984]
**Describe the bug**
GrantNav filters and Summary show values that are on the upper bound of the amount range in the next range up, whereas Insights includes them in the original range.

**To Reproduce**
1. Select the 0 to 500 amount awarded in GrantNav
2. Note the numbers and the summary graph
3. Go into Insights for that filtered view
4. Note the different numbers in the Award Amount Graph

**Expected behavior**
Consistent treatment of numbers - GrantNav should match Insights i.e. grants worth 500 should appear in 0 to 500, instead of 500 to 1000.

**Screenshots**
![image](https://user-images.githubusercontent.com/128042420/229170265-db1aa303-bf8c-4d24-bbab-31dd2657e065.png)

![image](https://user-images.githubusercontent.com/128042420/229170434-4d73618e-08be-402d-9692-135f0ca85d8e.png)

**Comment by mariongalley** [comment]
This is fixed thanks to new Insights being based on GrantNav back end
