### ISSUE TITLE
Widget builder: choice of what columns to display

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#996]
**Is your feature request related to a problem? Please describe.**
We've had several users and prospective users of widgets ask us to display columns that are currently not displayed (Classifications, Programmes), hide columns that are currently shown (Funder) or move columns around (make Recipient the first column).

This is because funders are using the widgets to show their own grantmaking, and so all the grants displayed within it are from the same funder, whereas people accessing the widget are more likely to be interested in who the recipient was, or under what programme or theme the grant was awarded.

**Describe the solution you'd like**
I'd like users to have a choice of what columns to display. There are a couple of ways this could be done, for example the widget builder could provide total flexibility, and users can select columns from a picklist of required and recommended 360Giving fields, or the widget builder could provide a handful of preset column orders as different types of table in the picklist. There may be other ways this could be achieved too.

**Describe alternatives you've considered**
The alternative is to not provide alternative column ordering. Users can have some control over what columns are displayed by changing the width of the widget, which if reduced will collapse the right-most columns (currently Description, then Recipient, then Funder).

**Comment by mariongalley** [comment]
@codemacabre Just realised that some funders give all their grants within a programme the same Title, so actually if we don't have to require Title be displayed by default, that would be preferable.

**Comment by codemacabre** [comment]
@mariongalley A couple of thoughts:
1. It will be easier to not allow the columns to be reordered; are you happy with just allowing columns to be selected / hidden / displayed instead? This means that if someone doesn't select the Title, the first column will be Amount.
2. Having customisable columns means that the default setup (i.e. which ones are displayed or collapsed at different screen widths) will be unset as soon as any column customisation happens. Is that ok?

New (only 'Funder' selected):
![image](https://github.com/ThreeSixtyGiving/grantnav/assets/49149591/187dfb18-17ac-402d-86c9-e31232478223)

Original (all columns displayed but several collapsed by default):
![image](https://github.com/ThreeSixtyGiving/grantnav/assets/49149591/a8d1c0b2-dc28-4b8b-aa1e-5a192b91bb1b)

**Comment by mariongalley** [comment]
> Having customisable columns means that the default setup (i.e. which ones are displayed or collapsed at different screen widths) will be unset as soon as any column customisation happens. Is that ok?

I'm not sure I understand what you mean by this @codemacabre , does it mean that it's not possible to have any columns collapsed? Or that the number of collapsed columns will no longer be dynamic based on the width of the widget?

**Comment by codemacabre** [comment]
@mariongalley I think I was confusing myself here with the complex mix of custom and default responsiveness options we have for datatables. I think I've sorted it so this point is obsolete and columns always collapse into appropriate sub rows gracefully. I'll get it on dev for you to test.

**Comment by mariongalley** [comment]
Awesome, thank you!

**Comment by codemacabre** [comment]
@mariongalley This has been deployed on the dev server for testing.

**Comment by mariongalley** [comment]
Thanks @codemacabre - It seems to be that all the columns apart from Date & Amount (which are unnecessarily wide) are collapsed whenever a column selection is made, which doesn't meet the key user need to having the selected columns be visible.

Is there a way to have the maximum number of columns be visible with collapsing only "excess" columns?

![image](https://github.com/ThreeSixtyGiving/grantnav/assets/82958988/e8f382b4-11a4-4461-9c66-51aba6a796c8)

**Comment by codemacabre** [comment]
@mariongalley Updated. The problem is that datatables applies the majority of these responsive styles automatically, so we have very limited ability to customise the way columns collapse, etc. The more customisation we want, the more I'd consider moving away from datatables and using a different library.

It should be better now, though; please let me know what you think.

**Comment by codemacabre** [comment]
@mariongalley Hmm, I think it may be time to move to using a different library and move away from datatables. I'll investigate.
