### ISSUE TITLE
Highlighted grants are overwriting all recipients to be to individuals

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#997]
**Describe the bug**
Highlighted grants are overwriting all recipients to be to individuals

**To Reproduce**
1. Go to main search
2. Click on highlighted grants
3. See that they all show To Individual as Recipient

**Expected behavior**
Show the actual recipient of the grant.

**Screenshots**
![image](https://github.com/ThreeSixtyGiving/grantnav/assets/82958988/36a51cb0-3091-44d3-a793-dbd091c75aca)

**Comment by michaelwood** [comment]
@mariongalley Treated this as urgent and have pushed a fix #998 

Separately but related, we are currently are being affected by downtime on plotly graphing library which provides the visualisation in the summary area https://github.com/plotly/plotly.js/issues/6648 . I'll watch the ticket if there isn't a resolution today we can look for another source, or host the library within grantnav instead.

**Comment by michaelwood** [comment]
Moved the plotly issue into https://github.com/ThreeSixtyGiving/grantnav/issues/999
